### ISSUE TITLE
Not all data sources are found

### ISSUE THREAD

**Issue by DCrow** [rails-sqlserver/activerecord-sqlserver-adapter#1000]
## Issue
When using a database with multiple schemas, not all tables are found for method
```ruby
ActiveRecord::Base.connection.data_sources
```
It seems to stem from this [line](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/6-0-stable/lib/active_record/connection_adapters/sqlserver/schema_statements.rb#L322).
When `ActiveRecord::Base.connection.data_source_sql` is called, it's called without any parameters and because of that `quoted_scope `(inside that method) always returns `dbo`.
Maybe this adapter should search all schemas like [postgres adapter](https://github.com/rails/rails/blob/6-0-stable/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L749) not just `dbo`?

## Expected behavior
I'm expecting that all tables with different schemas are found.

## Actual behavior
Tables with schemas other than `dbo` are not found.

## How to reproduce
See [example](https://github.com/DCrow/activerecord-sqlserver-adapter/commit/78ba894766ba615ed6a2d055936866b283b4c49c)

## Details

- **Rails version**: `6.0.4.4`
- **SQL Server adapter version**: `6.0.4.4`
- **TinyTDS version**: `2.1.5`
- **FreeTDS details**:
```zsh
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.3.6
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: yes
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: yes
  ```

**Comment by KDGundermann** [comment]
See also: #998 
I assume the current user has the dbo schema as default schema. 
Why should we enumerate all others schemas?
How should it handled if there are duplicate names?

**Comment by DCrow** [comment]
> Why should we enumerate all others schemas?

We should enumerate since other database adapters support this.
For example rails postgres adapter. It also supports which schemas to enumerate using `schema_search_path` option in database.yml. 

> How should it handled if there are duplicate names?

I think data_sources should return names with schema, so that it will be possible to differentiate same table names with different schemas.
Also it should be noted that truncating tables doesn't always work if you use a table which has a different schema from default.

**Comment by DCrow** [comment]
Something like this should work
```SQL
ANY(SELECT DISTINCT TABLE_SCHEMA from INFORMATION_SCHEMA.TABLES)
```

**Comment by abhishekup5338** [comment]
Hi @DCrow  assign this task to me.

**Comment by aidanharan** [comment]
On the Rails 8 branch (main) the example passes if you include the schema when checking for tables in non-dbo schemas.

```ruby
# frozen_string_literal: true

require "cases/helper_sqlserver"

class ExecuteProcedureTestSQLServer < ActiveRecord::TestCase
  before do
    connection.execute("CREATE SCHEMA dbo1")
    connection.execute("CREATE SCHEMA dbo2")
    connection.execute("CREATE TABLE dbo1.super_employee(EmployeeID INT PRIMARY KEY CLUSTERED)")
    connection.execute("CREATE TABLE dbo2.villain_employee(EmployeeID INT PRIMARY KEY CLUSTERED)")
  end

  after do
    connection.execute("DROP TABLE dbo1.super_employee")
    connection.execute("DROP TABLE dbo2.villain_employee")
    connection.execute("DROP SCHEMA dbo1")
    connection.execute("DROP SCHEMA dbo2")
  end

  it "execute a simple procedure" do
    data_sources = ActiveRecord::Base.connection.data_sources

    assert_includes data_sources, 'dbo1.super_employee'
    assert_includes data_sources, 'dbo2.villain_employee'
  end
end
```
