### ISSUE TITLE
change_column_default cannot drop default constraint

### ISSUE THREAD

**Issue by nemesit** [rails-sqlserver/activerecord-sqlserver-adapter#1018]
## Issue
change_column_default and similar methods not working as intended

## Expected behavior

according to the documentation
[change_column_default](https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/change_column_default)(:users, :email, nil)

`change_column_default("SomeTable", "SomeColumn", nil)`

should drop the default constraint on SomeColumn.

## Actual behavior

`ALTER TABLE [SomeTable] ADD CONSTRAINT DF_SomeTable_SomeColumn DEFAULT NULL FOR [SomeColumn]`

gets executed which results in a `(Null)` default constraint.

## How to reproduce

use
`change_column_default("SomeTable", "SomeColumn", nil)`

## Details

- **Rails version**: `7.0.1`
- **SQL Server adapter version**: `7.0.0.0`
- **TinyTDS version**: `2.1.5`

**Comment by aidanharan** [comment]
The behavior of the `change_column_default` according to the [documentation](https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/change_column_default) is that "Setting the default to nil effectively drops the default". 

The current implementation of the SQL Server does this and allows the relevant tests to pass https://github.com/rails/rails/blob/f8f25907257f15fffeae4f7cd0010351994de145/activerecord/test/cases/migration/columns_test.rb

I checked the other adapters and the approach they use for `change_column_default` is not consistent. The MySQL adapter does the same as the MSSQL adapter and creates a column default of "NULL":

```
ALTER TABLE `test_models` CHANGE `first_name` `first_name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL
```

The PostgreSQL adapter takes the approach of dropping the column default:

```
ALTER TABLE "test_models" ALTER COLUMN "first_name" DROP DEFAULT
``` 

I think the MSSQL adapter should keep the current approach as it is also used by the MySQL adapter and any change could cause unforeseen issues for MSSQL adapter users.
