### ISSUE TITLE
ActiveRecord::ConnectionAdapters::SQLServerAdapter does not support upsert

### ISSUE THREAD

**Issue by felzend** [rails-sqlserver/activerecord-sqlserver-adapter#1044]
## Issue

Trying to use an upsert operation on my model, but it's showing an error telling this adapter has no implementation for that.

## Expected behavior

Upsert operation working with no exceptions.

## Actual behavior

Throwing an exception:

```ActiveRecord::ConnectionAdapters::SQLServerAdapter does not support upsert```

```raise ArgumentError, "#{connection.class} does not support upsert"``` 

## How to reproduce

Simply calling

![image](https://user-images.githubusercontent.com/10427954/226152871-a6e2900d-2034-4b69-9638-cb8aef3ddaf4.png)

## Details

- **Rails version**: `7.0.4.3 `
- **SQL Server adapter version**: ` 7.0.1.0`
- **TinyTDS version**: `2.1.5`
- **FreeTDS details**:

SQL SERVER 16.0.4003.1 - Developer Edition

**Comment by aidanharan** [comment]
The adapter doesn't support `upsert` as Microsoft SQL Server doesn't natively support it either. There were investigations in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/859 to see if `upsert` could be supported using `MERGE` but they have been unsuccessful.
