### ISSUE TITLE
[Rails 7.1] Upgrading the MSSQL adapter

### ISSUE THREAD

**Issue by aidanharan** [rails-sqlserver/activerecord-sqlserver-adapter#1067]
The `main` branch will now be used for Rails 7.1 development. Rails 7.0 development has moved to the https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/tree/7-0-stable branch. 

Since there is no tag yet for Rails 7.1 (still no alpha release) the CI tests run against the Rails `main` branch using the `RAILS_MAIN` gemfile option. To run the tests locally use:

```bash
RAILS_MAIN=1 bundle install
RAILS_MAIN=1 bundle exec rake test 
```

The CI tests are currently running but failing. These will need to be fixed. Since Rails 7.1 is still not released we will be developing the adapter against a moving target.

**Comment by aidanharan** [comment]
Rails 7.1.0.beta1 has been released. So to run the tests you can now use: 

```
bundle install
bundle exec rake test
```

**Comment by bf4** [comment]
Rails 7.1 is released 👯

**Comment by SujayPrabhu96** [comment]
Hi @aidanharan when can we expect the release for supporting Rails 7.1?

**Comment by aidanharan** [comment]
I have created [release v7.1.0.beta1](https://rubygems.org/gems/activerecord-sqlserver-adapter/versions/7.1.0.beta1) of the adapter for Rails 7.1. It would help greatly if you could test the release and open any issues you encounter. 

The tests are currently not passing consistently. This will need to be investigated as it could indicate an issue with the adapter.

**Comment by aidanharan** [comment]
Created release candidate [v7.1.0.rc1](https://rubygems.org/gems/activerecord-sqlserver-adapter/versions/7.1.0.rc1).

**Comment by aidanharan** [comment]
The [v7.1.0](https://rubygems.org/gems/activerecord-sqlserver-adapter/versions/7.1.0) of the ActiveRecord SQL Server Adapter has been released. Please report any bugs/issues.
