### ISSUE TITLE
`raw_connection_do` method removed in 7.1.0 but still referenced in Readme

### ISSUE THREAD

**Issue by owst** [rails-sqlserver/activerecord-sqlserver-adapter#1146]
## Issue

The [Readme](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/main/README.md#configure-connection) references `raw_connection_do` which was removed in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1121 and no longer exists in the released 7.1.0

## Expected behavior
The example in the Readme to configure the connection should work.

## Actual behavior

`undefined method 'raw_connection_do' for #<ActiveRecord::ConnectionAdapters::SQLServerAdapter version: 7.1.0, azure: true>`

## How to reproduce

Try and use the example in the readme to configure the connection

## Details

- **Rails version**: `7.1.2`
- **SQL Server adapter version**: `7.1.0`
- **TinyTDS version**: `2.1.5`
- **FreeTDS details**:

  ```
                            Version: freetds v1.3.19
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: yes
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: yes
  ```

**Comment by owst** [comment]
I suspect the fix is to call `internal_exec_query` instead of `raw_connection_do` but want to check that here

**Comment by aidanharan** [comment]
Fixed the [README](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/tree/main#configure-connection) to use the same method as the super's method.

```ruby
@raw_connection.execute("SET TEXTSIZE #{64.megabytes}").do
```
