### ISSUE TITLE
Update example in section "Configure Connection" in README.md

### ISSUE THREAD

**Issue by andsip** [rails-sqlserver/activerecord-sqlserver-adapter#1241]
The following example code [is proposed at the moment](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/68d1c0f4c822323f032cdba0f2ec7844259238c3/README.md?plain=1#L101-L118):
```ruby
module ActiveRecord
  module ConnectionAdapters
    class SQLServerAdapter < AbstractAdapter
      def configure_connection
        super
        @raw_connection.execute("SET TEXTSIZE #{64.megabytes}").do
      end
    end
  end
end
```

However, as of commit 4842d2e, this implementation no longer works, as far as I see it.

This is because method `#configure_connection` was defined on `SQLServerAdapter` in that commit, which means that the example in the Readme will override this method, causing a call to `super` to invoke `AbstractAdapter#configure_connection` and not `SQLServerAdapter#configure_connection` (as intended).

The following adaptation of the example code works for me:

```ruby
ActiveRecord::ConnectionAdapters::SQLServerAdapter.prepend(
  Module.new do
    def configure_connection
      super
      @raw_connection.execute("SET TEXTSIZE #{64.megabytes}").do
    end
  end
)

```

**Comment by aidanharan** [comment]
@andsip Good point! Could you review https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1242 and see what you think?
