### ISSUE TITLE
tiny_tds v3

### ISSUE THREAD

**Issue by andyundso** [rails-sqlserver/activerecord-sqlserver-adapter#1269]
Hello!

I am planning to release v3 of `tiny_tds` sometime this week. It's mostly just a maintenance release that drops support for a bunch of older Ruby and SQL server versions.

The only thing that I know will affect the `activerecord-sqlserver-adapter` is PR https://github.com/rails-sqlserver/tiny_tds/pull/560 which would make https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/main/lib/active_record/connection_adapters/sqlserver/database_statements.rb#L453 obsolete. But your existing code will still continue to work.

I am wondering, based on the [current changes](https://github.com/rails-sqlserver/tiny_tds/blob/d94efe60d6523929000bab5d6a9656f26093c7ac/CHANGELOG.md), do you see any other impact on the `activerecord-sqlserver-adapter`?

Additionally, should the used version for `tiny_tds` by the `activerecord-sqlserver-adapter` be locked to a certain major version? I am maybe getting ahead of myself, but I would like to release a v4 somewhere next year dropping support for Ruby 2.7, 3.0 and 3.1, which would have an impact for the v7.1 version of the adapter, since there the minimum specified Ruby version is 2.7.

**Comment by aidanharan** [comment]
> I am wondering, based on the [current changes](https://github.com/rails-sqlserver/tiny_tds/blob/d94efe60d6523929000bab5d6a9656f26093c7ac/CHANGELOG.md), do you see any other impact on the activerecord-sqlserver-adapter?

I don't see anything obvious in the changes that should impact activerecord-sqlserver-adapter. 

> Additionally, should the used version for tiny_tds by the activerecord-sqlserver-adapter be locked to a certain major version? 

I assume that bundler is smart enough to take the `tiny_tds`'s gemspec ruby version into account when updating gems. So if you are using Ruby 2.7 with `activerecord-sqlserver-adapter` v7.1, then bundler won't upgrade your `tiny_tds` dependency if v4's minimum ruby version is greater than 2.7.

**Comment by andyundso** [comment]
thanks for your feedback. therefore, I am going ahead and will release v3 sometime this week, and would submit a patch to the adapter soon removing this line of code I mentioned.
