### ISSUE TITLE
Use OUTPUT [INSERTED] For Inserted Primary Keys

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/activerecord-sqlserver-adapter#222]
As pointed out by Jeremy Evans, we could use this method for getting a returned primary key vs system functions like SCOPE_IDENTITY(). This conversation started in a core list about supporting UUID columns here. https://groups.google.com/forum/?fromgroups#!topic/rubyonrails-core/uvgu6B7ANuM

**Comment by metaskills** [comment]
So we are indeed using this now.

```ruby
def sql_for_insert(sql, pk, id_value, sequence_name, binds)
  sql = if pk
    quoted_pk = SQLServer::Utils.extract_identifiers(pk).quoted
    sql.insert sql.index(/ (DEFAULT )?VALUES/), " OUTPUT INSERTED.#{quoted_pk}"
  else
    "#{sql}; SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident"
  end
  super
end
```

The way the method is written, we only use for inserts with `VALUES` or `DEFAULT VALUES`. Working great.

**Comment by GasCreature** [comment]
The issue I ran into with this is this error message: "the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause." Triggers can't be avoided if the table is merge replicated since sp_addmergearticle inserts them.

**Comment by metaskills** [comment]
@GasCreature Are you asking for this to be changed to a config value?

**Comment by GasCreature** [comment]
I didn't have a specific solution in mind. I guess a config setting would be one way of doing it. The way I monkey-patched it so it would work was to comment out the if pk else end lines, leaving only the
   "#{sql}; SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident"
line ahead of the super. Yeah, I guess if that alternate flow could be set from a config value, it would work for me.
