### ISSUE TITLE
Malfunction with tables/views names containing '.' and column names in views with special characters

### ISSUE THREAD

**Issue by dguti** [rails-sqlserver/activerecord-sqlserver-adapter#226]
I was working with a legacy MS SQL Server database and I found several problems. In order to reproduce them:
- Create a view than contains a column containing a special character (i.e. '+'), then try to access that column.

This is the piece of code that would fail in file 'schema_statements.rb':

        def views_real_column_name(table_name,column_name)
          view_definition = view_information(table_name)[:VIEW_DEFINITION]
          
          match_data = view_definition.match(/([\w-]*)\s+as\s+#{column_name}/im)
          match_data ? match_data[1] : column_name
        end

- Create a view that contains a '.' in the name (i.e. 'My table.v1'). I not you shouldn't do that, but it is possible in MSSQL if you name the objects using square brackes (i.e., '[My table.v1]'). Then try to get information about the table (ActiveRecord::Base.connection.columns("[My table.v1]")).

I post here my solution. I could fork and make a pull request, but I'm not sure about the solution for the first problem.

#Patch that can be applied as an initializer modifing the SQLServerAdapter class.
#In the gem, the patch should be applied to the module ActiveRecord::ConnectionAdapters::Sqlserver::SchemaStatements

require 'active_record/base'
require 'active_record/connection_adapters/sqlserver_adapter'

module ActiveRecord

  module ConnectionAdapters

    class SQLServerAdapter

      #Overrides existing method
      def views_real_column_name(table_name,column_name)
        #I don't understand the purpose of the original code but it failed
        #when column_name contained characters reserved for regular expressions
        #like '+', etc.
        #Simply returning the original column_name is working fine in my case.
        column_name
      end

      #New helper method that splits fully qualified table name into its parts
      def table_name_tokens(table_name)
        #Tokens between square brackets [] may contain a dot, so we cannot use '.' to split the table name.
        #I detect tokens between square brackets and substitute '.' by the opening bracket '[', then
        #I split the table name using '.' into tokens, and finally I change the '[' in the tokens by '.'.
        table_name.gsub(/\[[^\]]*\]/) {|m| m.gsub(/\./,"[")[1..-2] }.split(".").map{|t| t.gsub(/\[/,".")}
      end

      #Overrides existing method
      def unqualify_table_name(table_name)
        table_name_tokens(table_name)[-1]
      end

      #Overrides existing method
      def unqualify_table_schema(table_name)
        table_name_tokens(table_name)[-2]
      end

      #Overrides existing method
      def unqualify_db_name(table_name)
        table_name_tokens(table_name)[-3]
      end

    end #class SQLServerAdapter < AbstractAdapter
    
  end #module ConnectionAdapters

end #module ActiveRecord

**Comment by metaskills** [comment]
There has been major changes in the 4.2 adapter WRT quoting. This issue is likely loved in that version and if not, we need a new issue opened that speaks to the updated code. Cheers and more info here. http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/
