### ISSUE TITLE
Initializing Schema Migrations with "dbo." in table prefix breaks on the "." in "dbo."

### ISSUE THREAD

**Issue by michiels** [rails-sqlserver/activerecord-sqlserver-adapter#230]
I configured ActiveRecord to include "dbo.Wdb_" as table prefix:

``` ruby
config.active_record.table_name_prefix = 'dbo.Wdb_'
```

When creating the schema migrations table for the first time, this breaks on adding the unique index to the version column:

```
TinyTds::Error: Incorrect syntax near '.'.: CREATE UNIQUE INDEX [dbo].[Wdb_unique_schema_migrations] ON [dbo].[Wdb_schema_migrations] ([version])
```

This is because it tries to create the Index with name "dbo.Wdb_unique_schema_migrations" and apparently, periods are not allowed in the index name.

This code is called in the ```initialize_schema_migrations_table``` in ActiveRecord:

``` ruby
      # Should not be called normally, but this operation is non-destructive.
      # The migrations module handles this automatically.
      def initialize_schema_migrations_table
        sm_table = ActiveRecord::Migrator.schema_migrations_table_name

        unless table_exists?(sm_table)
          create_table(sm_table, :id => false) do |schema_migrations_table|
            schema_migrations_table.column :version, :string, :null => false
          end
          add_index sm_table, :version, :unique => true,
            :name => "#{Base.table_name_prefix}unique_schema_migrations#{Base.table_name_suffix}"
````

In some way we need to make sure that Base.table_name_prefix does either not include "dbo." or sanitizes all periods in the index name.

I see two options here:

* Either overload ``initialize_schema_migrations_table``` in the sqlserver adapter. Which seems a bit overkill to replace this pretty bulky method to change only the Base.table_name_prefix.
* Or we overload add_index method in this sqlserver adapter to sanitize the index name.

A third option is of course, to make a patch for Rails to do this stuff but I guess this is pretty sqlserver specific, I think one of the first two would be best.

I have no problems writing this patch if I'd get some feeling of the direction to take.

Thanks!

**Comment by metaskills** [comment]
There has been major changes in the 4.2 adapter in the area of quoting. If this issue is not resolved already, we have a better chance at fixing it. More info here and closing this issue. http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/
