### ISSUE TITLE
RuntimeError (Unknown bind columns. We can account for this.):

### ISSUE THREAD

**Issue by CloCkWeRX** [rails-sqlserver/activerecord-sqlserver-adapter#239]
Similar to #118

$ cat Gemfile.lock | grep sql
    activerecord-sqlserver-adapter (3.2.10)
  activerecord-sqlserver-adapter (~> 3.2.0)

Creating a view with a lower case name fails to correctly map.

The below fails to map to a 'Views::ExampleViewName' class
            CREATE VIEW example_view_name AS ...

Combined with
Views::ExampleViewName.find(1)

produces:
RuntimeError (Unknown bind columns. We can account for this.):

Creating the view with uppercase appears to work
            CREATE VIEW EXAMPLE_VIEW_NAME AS ...

Misc other things:
$ dpkg -l | grep tds
ii  freetds-bin                               0.91-1build1                              amd64        FreeTDS command-line utilities
ii  freetds-common                            0.91-1build1                              all          configuration files for FreeTDS SQL client libraries
ii  freetds-dev                               0.91-1build1                              amd64        MS SQL and Sybase client library (static libs and headers)
ii  libjtds-java                              1.2.5+dfsg-2ubuntu1                       all          JDBC 3.0 driver for Microsoft SQL Server(tm) and Sybase(tm)
ii  tdsodbc:amd64                             0.91-1build1                              amd64        ODBC driver for connecting to MS SQL and Sybase SQL servers

**Comment by metaskills** [comment]
There is a change in master that fixes this for the upcoming 4.2 release which should be out in alpha later today. I have accounted for integer and string types and we can add more support later if needed.

**Comment by enwood** [comment]
I'm just going to add a comment here that might help anyone else searching for this problem. 

I hit this very same error message using version 4.0.0 of this gem under Rails 4.0.8.

My User model `has_many` Filings. And I had a Filing belonging to a User, but named as an *owner*, with the class name User:

```
belongs_to    :owner, :class_name => "User" 
```

When querying a specific user for filings, I was getting this error:
```
crs »  u = User.find(1)
crs »  u.filings
(pry) output error: # RuntimeError: Unknown bind columns. We can account for this.
```

When I changed a Filing to belong to a User (without the name owner and without expressly specify the class name):

```belongs_to :user```

the problem disappeared.

```
[1] crs »  u = User.find(1)
[2] crs »  u.filings
  Filing Load (5.0ms)  EXEC sp_executesql N'SELECT [filings].* FROM [filings] WHERE [filings].[user_id] = @0', N'@0 int', @0 = 1  [["user_id", 1]]
=> [
```

So, the adapter was having difficulty mapping the `owner_id` to the `User` class in the first example?

**Comment by enwood** [comment]
Okay, so I discovered my problem to be unrelated to the adapter. Phew! It was just my incomplete use of the "foreign_key" attribute.

Through some experimentation (and reading 4.3.2.5 of http://guides.rubyonrails.org/association_basics.html) I found that I also needed to specify the ```foreign_key``` attribute on the ```has_many``` statement *as well as* the ```belongs_to``` statement:

```
User.rb
  has_many  :filings, foreign_key: 'owner_id'
Filing.rb
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
```

I wasn't aware of having to specify the ```foreign_key``` on both sides, but it sure works. 

Tim

**Comment by krzcho** [comment]
@metaskills any chance on having that "https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/commit/ce570d6ab24706a9473a52b0c20eee88fede2b45" commit merged into 4.1 branch?

**Comment by aleksandrs-ledovskis** [comment]
FWIW, had same error appearing and being caused by Rails being "too smart and helpful".
In given application, two different DBMS are at use simultaneously, and having `has_one :foo_in_dbms_1, through: :bar_in_dbms_2` showed up the dreaded error when calling `#foo_in_dbms_1` on record, because obviously `JOIN` across separate non-customized DBMS do not work.

Interestingly enough, doing `includes(:foo_in_dbms_1)` when loading object caused association target to be preset - problem was only affecting "cold loaded" records.

Have trick-solved it by redefining reader after association setup (`delegate :foo_in_dbms_1, to: :bar_in_dbms_2`).

**Comment by rip747** [comment]
FYI... In case anyone else finds this page through Google. I got around this issue by casting the columns in my view to the same datatype as the table I was performing the association with in rails. So I changed my view definition to:

alter view myView
as
select
cast(id as int) as id
,columnA
,columnB
from Table
