### ISSUE TITLE
offset used with pluck results in row numbers, NOT the correct column values

### ISSUE THREAD

**Issue by mikesnare** [rails-sqlserver/activerecord-sqlserver-adapter#244]
If offset is called on a scope and you attempt to use pluck to retrieve a single column from that offset scope, you'll get the row numbers instead of the actual value, regardless of what you attempt to pluck.

E.g.

// This will yield the correct, expected values:
Model.where("some_column = 'test_value'").pluck(:id)

// This will not:
Model.where("some_column = 'test_value'").offset(1).pluck(:id)

Note that the column being plucked doesn't matter.  You'll always get row numbers if there's an offset.

**Comment by metaskills** [comment]
There has been major changes in the 4.2 adapter WRT limit/offset. More info here. http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/
