### ISSUE TITLE
remove_index when used as UNIQUE KEY is failing.

### ISSUE THREAD

**Issue by joshuairl** [rails-sqlserver/activerecord-sqlserver-adapter#260]
```
An explicit DROP INDEX is not allowed on index 'user_emails.IX_unique_email'. It is being used for UNIQUE KEY constraint enforcement.: DROP INDEX [IX_unique_email] ON [user_emails]
```
If you perform this SQL Server query, it does allow you to drop it.
`ALTER TABLE [dbo].[user_emails] DROP CONSTRAINT [IX_unique_email]`

Should we be using DROP INDEX or ALTER TABLE?
I'd say ALTER TABLE method will cover more bases than the DROP INDEX.

Please advise.

**Comment by metaskills** [comment]
I tried changing the implementation of `remove_index!` and received about a dozen errors. I would be open to a PR or change that addressed your issue and passed the tests. Could be something simple, but I will need someone to do the legwork and make a recommendation.
