### ISSUE TITLE
Stange issue using render json with a SQL View

### ISSUE THREAD

**Issue by ejstembler** [rails-sqlserver/activerecord-sqlserver-adapter#265]
I have a SQL View named 'projects', and I'm noticing a strange issue using render json from a controller.

Here's psuedo-code from the controller which renders the results of a SQL View as json:

```ruby
# GET /projects.json
def index
  respond_to do |format|
    format.json { render :json => @projects }
  end
end
```
This is what I'm seeing in the Rails development log (I've obfuscated the actual table name with DifferentTable):
<pre>
Started GET "/projects.json" for 127.0.0.1 at 2013-04-15 16:27:30 -0400
Processing by ProjectsController#index as JSON
  CACHE (0.0ms)  SELECT c.COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME = 'dbo.DifferentTable' AND c.COLUMN_NAME = ''
  CACHE (0.0ms)  SELECT c.COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME = 'dbo.DifferentTable' AND c.COLUMN_NAME = ''
  CACHE (0.0ms)  SELECT c.COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME = 'dbo.DifferentTable' AND c.COLUMN_NAME = ''
  CACHE (0.0ms)  SELECT c.COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME = 'dbo.DifferentTable' AND c.COLUMN_NAME = 'END'
  CACHE (0.0ms)  SELECT c.COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME = 'dbo.DifferentTable' AND c.COLUMN_NAME = 'END'
  CACHE (0.0ms)  SELECT c.COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME = 'dbo.DifferentTable' AND c.COLUMN_NAME = 'END'
  CACHE (0.0ms)  SELECT c.COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME = 'dbo.DifferentTable' AND c.COLUMN_NAME = 'Value'
  CACHE (0.0ms)  SELECT c.COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME = 'dbo.DifferentTable' AND c.COLUMN_NAME = 'Value'
  CACHE (0.0ms)  SELECT c.COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME = 'dbo.DifferentTable' AND c.COLUMN_NAME = ''
  CACHE (0.0ms)  SELECT c.COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME = 'dbo.DifferentTable' AND c.COLUMN_NAME = ''
  Project Load (1582.0ms)  EXEC sp_executesql N'SELECT [projects].* FROM [projects]'
</pre>
A couple of points which may be issues:
* I'm not sure why COLUMN_DEFAULT is being queried so many times for a table which is not my SQL View.
* The dbo alias prefix causes the result to be excluded anyway.  It should be 'DifferentTable' not 'dbo.DifferentTable'
* The COLUMN_NAME values are not actual column names in that table (DifferentTable). And sometimes it's a blank string which is probably wrong.

If I search for a snippet of the sql in the CACHE lines, I found this code reference which may be related:  [Line 224 in scheme_statements.rb](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/active_record/connection_adapters/sqlserver/schema_statements.rb#L224)

**Comment by metaskills** [comment]
There has been major changes in the 4.2 adapter WRT limit/offset since we now use OFFSET/FETCH. This issue is likely resolved in that version. Cheers and more info here. http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/
