### ISSUE TITLE
__rn exception with render json

### ISSUE THREAD

**Issue by cliche2004** [rails-sqlserver/activerecord-sqlserver-adapter#280]
Hey Guys,

I am having issue with the following setup - 

https://gist.github.com/cliche2004/df24bd5c2bfba3381e23

when render json -> it throw the __rn undefined method but once
I render it with xml its working fine .. I assume this is related to the sql-adapter?

**Comment by metaskills** [comment]
There has been major changes in the 4.2 adapter and this issue should not happen in there since we use OFFSET and FETCH now. More info here. http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/
