### ISSUE TITLE
retry_deadlock_victim turned on by default

### ISSUE THREAD

**Issue by kevinsheffield** [rails-sqlserver/activerecord-sqlserver-adapter#283]
The way the readme describes this feature it is something that has to be enabled, but it is actually turned on by default.

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/active_record/connection_adapters/sqlserver_adapter.rb#L359

If it is nil, the ternary returns true.

This should be disabled by default as suggested by the readme.

**Comment by metaskills** [comment]
There is no more deadlock retry logic in the 4.2 adapter.
