### ISSUE TITLE
Queries with limits and no offset return the last items instead of the first ones

### ISSUE THREAD

**Issue by gc-olivierho** [rails-sqlserver/activerecord-sqlserver-adapter#286]
When using Redmine with MS SQL, the search results are the 10 last issues instead of the 10 first.
After tracing the Redmine and then Ruby code, I ended up suspecting the following lines, in activerecord-sqlserver-adapter-3.2.12/lib/arel/visitors/sqlserver.rb:
<PRE>      def visit_Arel_Nodes_SelectStatementWithOutOffset(o, windowed=false)
(...)
        elsif eager_limiting_select_statement?(o)
          projections = projections.map { |x| projection_without_expression(x) }
          groups = projections.map { |x| projection_without_expression(x) }
          orders = orders.map do |x|
            expr = Arel.sql projection_without_expression(x.expr)
======>     x.descending? ? Arel::Nodes::Max.new([expr]) : Arel::Nodes::Min.new([expr])</font>
          end</PRE>

It seems that if x.descending is TRUE, then we apply a MAX() function, but we should also apply DESC ordering. However, this does not come into the query with this code.

Could someone give his opinion on this?

**Comment by metaskills** [comment]
There has been major changes in the 4.2 adapter WRT limit/offset since we now use OFFSET/FETCH. This issue is likely resolved in that version. Cheers and more info here. http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/
