### ISSUE TITLE
table prefixes break eager loading, cause long join

### ISSUE THREAD

**Issue by dgm** [rails-sqlserver/activerecord-sqlserver-adapter#287]
Related to #219 , We have a table prefix that generates sql like [dbo].[projects].  When that goes through rails 3.2.14, here:

https://github.com/rails/rails/blob/3-2-stable/activerecord/lib/active_record/relation.rb#L522

it ends up comparing ["dbo.projects"] to ["dbo","projects","dbo"]  and deciding that it references joined tables, when in fact it doesn't.

It seems that the standard tables_in_string doesn't find the full namespace/table format.

**Comment by metaskills** [comment]
Outdated, closing old issue.
