### ISSUE TITLE
Aggregate function(MAX) is ignored/removed when used with `offset`

### ISSUE THREAD

**Issue by ushavimal** [rails-sqlserver/activerecord-sqlserver-adapter#292]
I have the following query

>>User.select('first_name, MAX(created_at)').group(:first_name).order(:first_name).offset(10)

This gives me an error when i run it against sqlserver using activerecord-sqlserver-adapter. But it works fine with other databases like mysql/postgres

The error is

>> TinyTds::Error: Column 'User.created_at' is invalid in the select list
 because it is not contained in either an aggregate function or the
 GROUP BY clause:
 
 >>EXEC sp_executesql N'SELECT TOP (10) [__rnt].* FROM ( SELECT
 ROW_NUMBER() OVER (ORDER BY type ASC) AS [__rn], first_name,
 created_at FROM Users GROUP BY first_name ) AS [__rnt] WHERE
 [__rnt].[__rn] > (10) ORDER BY [__rnt].[__rn] ASC'**

You can see that the MAX aggregate function on created_at is ignored and because of that, the query is invalid.

Why is offset removing the aggregate function?

I also posted a question regarding this in SO and Google groups

http://stackoverflow.com/questions/20226051/tinytds-offset-removes-aggregate-function-from-select

https://groups.google.com/forum/#!topic/rails-sqlserver-adapter/ocQIELATNoI

Update:

I found the lines that are causing my problem

lib/arel/visitors/sqlserver.rb(line 373)

      # TODO: We use this for grouping too, maybe make Grouping objects vs SqlLiteral.
      def projection_without_expression(projection)
        Arel.sql(visit(projection).split(',').map do |x|
          x.strip!
          x.sub!(/^(COUNT|SUM|MAX|MIN|AVG)\s*(\((.*)\))?/,'\3')
          x.sub!(/^DISTINCT\s*/,'')
          x.sub!(/TOP\s*\(\d+\)\s*/i,'')
          x.strip
        end.join(', '))
      end

Could anyone please explain why these functions(COUNT, SUM, MAX, MIN, AVG) are stripped from select statement?

**Comment by metaskills** [comment]
This should not be the case anymore in 4.2.
