### ISSUE TITLE
Cannot update identity column

### ISSUE THREAD

**Issue by annaswims** [rails-sqlserver/activerecord-sqlserver-adapter#294]
When running the tests, I get an error:
```
PersistencesTest#test_update_column_changing_id:
ActiveRecord::StatementInvalid: TinyTds::Error: Cannot update identity column 'id'.: EXEC sp_executesql N'UPDATE [topics] SET [id] = 123 WHERE [topics].[id] = 1; SELECT @@ROWCOUNT AS AffectedRows'
 ```
Here's the test - 
```
  def test_update_column_changing_id
    topic = Topic.find(1)
    topic.update_column("id", 123)
    assert_equal 123, topic.id
    topic.reload
    assert_equal 123, topic.id
  end
```

I'm new to SQL Server, but it seems like it disallows updates on identity columns so this error would be the expected behavior.  Can someone more experienced with  SQL Server confirm this and I'll update the test?

P.S.  I know  it was listed in the [Current Expected Failures](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/b1516db613159c6c2c72e25c1311fd68a1563163/RUNNING_UNIT_TESTS.md#current-expected-failures) but I don't think that `rake test TEST_FILES="test/cases/aaaa_create_tables_test_sqlserver.rb,test/cases/persistence_test_sqlserver.rb"` actually runs that test.

**Comment by metaskills** [comment]
I coerced this test in the latest 4.2 work.
