### ISSUE TITLE
invalid ORDER BY clause generated if used with a function call with commas in it

### ISSUE THREAD

**Issue by sys-64738** [rails-sqlserver/activerecord-sqlserver-adapter#304]
As noted in #155 , the adapter fails to create a correct ORDER BY clause if the order criteria is an expression that contains commas. 53a248ae01c99f0f15eec2cd5d8ce3b3df4a0007 includes a code comment <code># Allow functions with comma(s) to pass thru.</code> which suggests that this is working, but it is not. The code of the <code>order</code> method initially splits the input string by commas, then adds ASC to each array element (i.e. <code>ORDER BY FOO(1,2,3)</code> becomes <code>ORDER BY FOO(1 ASC, 2 ASC, 3) ASC</code>.

To fix this, the code would have to match opening and closing brackets in order to catch only commas outside the outer brackets of the expression.

**Comment by metaskills** [comment]
This is not an issue in the 4.2 adapter since we now use OFFSET/FETCH.

**Comment by coin3d** [comment]
I've got exactly the same problem - is there a way to bypass this bug?

**Comment by metaskills** [comment]
Use an Arel.sql('...') literal string?
