### ISSUE TITLE
Second database timeout overrides first one

### ISSUE THREAD

**Issue by kirrmann** [rails-sqlserver/activerecord-sqlserver-adapter#307]
I'm using two different databases besides my rails database. Both of them are using the sqlserver adapter.

I got timeouts every time I ran **rake test** while some of the later controller tests was  executed. Executing the single test or using it inside the rails app didn't throw the error. I first tried to raise and than disabled the timeout for the database (even if the specific test didn't seem to take that long) but this didn't fixed the issue.

But setting the timeout to both databases fix the thrown errors. Even if the second isn't used for that test case. Seems like the second database definition for the timeout value in database.yml overrides the first one.

Happens with Rails 4 and actual git clone of  activerecord-sqlserver-adapter.

I initially defined the database.yml like:

```ruby
db1:
  adapter: sqlserver
  host: dbserver1
  port: 1433
  database: db1
  username: user1
  password: pwd
  timeout: 0

db2:
  adapter: sqlserver
  dataserver: dbserver2\i1
  database: db2
  username: user2
  password: pwd
```

Rails code:
```ruby
module ActiveRecord
  module ConnectionAdapters
    class SQLServerAdapter < AbstractAdapter
      def configure_connection
        raw_connection_do "SET LANGUAGE german"
      end
    end
  end
end

class Foo < ActiveRecord::Base
  establish_connection "db1"
  self.table_name = 'dbo.foo'

  ...
end

class Bar < ActiveRecord::Base
  establish_connection "db2"
  self.table_name = 'dbo.bar'

  ...
end
```

**Comment by metaskills** [comment]
If this were true, it would be an issue with ActiveRecord, not the adapter.
