### ISSUE TITLE
Database Tasks

### ISSUE THREAD

**Issue by agios** [rails-sqlserver/activerecord-sqlserver-adapter#334]
I wanted to add support for database rake tasks, but I am not sure what should be done for the structure_dump and structure_load tasks. All the other tasks work fine already making it at least possible to run migrations etc, but for these I could not find a satisfactory cross-platform solution. 

For loading, previously sqlcmd was used, but I was thinking it should be possible to read in the file and the just send it to the driver - haven't tested it though, because it makes no sense without dumping.

Unfortunately, things are worse for dumping. Solutions so far had used smoscript, which requires windows to run properly, or a bunch of wine hacks. Another consideration was using SQL as described [here](http://stackoverflow.com/questions/21547/in-sql-server-how-do-i-generate-a-create-table-statement-for-a-given-table), but that's an even bigger hack and will probably be a pita to maintain.

Alternatively, those two specific tasks could raise an error indicating they are unsupported.

What do you think?

**Comment by metaskills** [comment]
Closing, move talk PR.
