### ISSUE TITLE
4.1 upgrade throwing NameError

### ISSUE THREAD

**Issue by Paladin** [rails-sqlserver/activerecord-sqlserver-adapter#341]
Any idea why after doing a bundle update (going from Rails 3.2 to 4.1) I should be getting:

uninitialized constant ActiveRecord::ConnectionAdapters::SQLServerAdapter (NameError)

I can make it go away by requiring the gem as the first line in the initializer file, but that seems strange, at the least. And besides, that only leads to: 

`establish_connection': database configuration specifies nonexistent sqlserver adapter (ActiveRecord::AdapterNotFound)

which makes me think the adapter isn't getting loaded somehow.

Gemfile starts with 

gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter', '~> 4.1'
gem 'rails', '~> 4.1'

and Gemfile.lock reports:

    rails (4.1.1)
      actionmailer (= 4.1.1)
      actionpack (= 4.1.1)
      actionview (= 4.1.1)
      activemodel (= 4.1.1)
      activerecord (= 4.1.1)
      activesupport (= 4.1.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.1.1)
      sprockets-rails (~> 2.0)
 
and

    activerecord (4.1.1)
      activemodel (= 4.1.1)
      activesupport (= 4.1.1)
      arel (~> 5.0.0)
    activerecord-sqlserver-adapter (4.1.0)
      activerecord (~> 4.1.0)
      arel

**Comment by metaskills** [comment]
Please use the new 4.2 release.
