### ISSUE TITLE
Update Troubleshooting of Connecting for the First Time

### ISSUE THREAD

**Issue by jacobsmith** [rails-sqlserver/activerecord-sqlserver-adapter#342]
Here is a collection of things I had to do to get tests passing:

My environment:
    Running tests from Mac OS
    MS SQL running on VM
        Ports forwarded through 1433 both ways

Ensure that you are running on a local admin login to create the Rails user.

Disable Windows Firewall (Or allow 1433, depending on your setup/if you're already sandboxed)

Right click on your instance -> goto Server Properties -> Security -> then Change to SQL Server and Windows Authentication Mode

You might have to restart your intance.
(From http://serverfault.com/questions/2218/sql-server-issue-login-failed-for-user-username)

I'll try and write these up for the Wiki or in one of the md pages in the repo later, but just wanted to get one place with some of the things I had to do get everything working.

**Comment by metaskills** [comment]
Added, thanks y'all!
