### ISSUE TITLE
uuids should be lowercase to match other adapters

### ISSUE THREAD

**Issue by D1plo1d** [rails-sqlserver/activerecord-sqlserver-adapter#349]
Small issue with Rails 4 sqlserver uuids, their being returned as uppercase when the postgresql adapter returns them as lowercase.

In environments (like mine! :) where postgresql is used in dev and sqlserver on staging and production this difference in behaviour can cause false negatives when comparing uuids with expected lowercase strings (particularly in my unit tests).

Thanks!

**Comment by metaskills** [comment]
This should not be the case in the 4.2.0 version of the adapter. Please try that and if needed let me know and I can re-open this ticket.

**Comment by demersus** [comment]
I just upgraded to the 4.2 version, and UUIDS are still uppercase.

**Comment by metaskills** [comment]
Can you detail what you mean? Are you talking about the DB values? If so, that is DB specific and should not be altered.

**Comment by demersus** [comment]
Yes, the uuids are being returned from the database as uppercase.  I was looking for a way to normalize it when I found this issue.  I have an app where we are migrating data between postgresql and sqlserver.  I was comparing data based on UUIDs in the databases.  The postgresql adapter returns uuids all lowercase, and the sqlserver adapter returns them all uppercase.  Maybe this is expected.   If so, you can ignore my comments.  I have been transforming the uuids from sqlserver to lower case before making the comparison, and it has been working fine.

Thanks!

**Comment by metaskills** [comment]
> Maybe this is expected

It is expected. Each DB is different.

>  I have been transforming the uuids from sqlserver to lower case 

Yes, that is the best way. Not sure how you did it, but I would have made an attribute reader method named after the column and done something like this.

```ruby
def my_guid_column
  value = super
  value.nil? ? value : value.downcase
end
```

**Comment by demersus** [comment]
Yep, that's basically the same code I used.     Sorry for the misunderstanding.
