### ISSUE TITLE
Emoji and TinyTDS

### ISSUE THREAD

**Issue by callumj** [rails-sqlserver/activerecord-sqlserver-adapter#350]
Hey guys,

I have a client sending down emoji characters that fail to insert at the TinyTDS level with the error "Error converting characters into server's character set. Some character(s) could not be converted".

The target column is a NVARCHAR and I can see the query is successfully wrapping the string with `N`.

Do I need to change the encoding option on the database config file?

**Comment by metaskills** [comment]
Reopening this issue to discuss more. Related is this adapter topic. https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/390

**Comment by metaskills** [comment]
Was playing with this test on 2012 and Azure. I need to read back on #390 and grok the state of things.

```ruby
it 'can inset/select emoji' do
  id = @client.execute("INSERT INTO [datatypes] ([nvarchar_50]) VALUES (N'😃')").insert
  find_value(id, :nvarchar_50).must_equal '😃'
end
```

Expected: "😃"
  Actual: "�"

**Comment by metaskills** [comment]
I have a commit in the TinyTDS/FreeTDS 1.0 branch that takes about how Emoji support work in 0.95 and upward. Hope this helps! https://github.com/rails-sqlserver/tiny_tds/pull/265/commits/a9437697c5b8fb6efa3479f2f44fec5353dfbd8a

**Comment by metaskills** [comment]
I have a commit in the TinyTDS/FreeTDS 1.0 branch that takes about how Emoji support work in 0.95 and upward. Hope this helps! https://github.com/rails-sqlserver/tiny_tds/pull/265/commits/a9437697c5b8fb6efa3479f2f44fec5353dfbd8a

**Comment by vin-yu** [comment]
:stuck_out_tongue_winking_eye: :heart_eyes: woot!!
