### ISSUE TITLE
Bug when using composite primary keys

### ISSUE THREAD

**Issue by jmozmoz** [rails-sqlserver/activerecord-sqlserver-adapter#352]
There is a problem when inserting new values into a table using the composite_primary_key gem: https://github.com/composite-primary-keys/composite_primary_keys/issues/224

I am not sure where this bug has to be fixed (in the sql server adapter or the composite_primary_key gem)

**Comment by metaskills** [comment]
I made the same comment in #354. Closing this issue, I made a comment on the linked ticket. That project should freedom patch `sql_for_insert` for this adapter just like they did for PostgreSQL.
