### ISSUE TITLE
Getting errors on rake db:schema:load

### ISSUE THREAD

**Issue by rept** [rails-sqlserver/activerecord-sqlserver-adapter#356]
I run this command:

rake db:schema:load

And when it tries to create the table authentications I'm getting this error message:

-- create_table("authentications", {:force=>true})
   (0.8ms)  DROP TABLE IF EXISTS [dbo].[web_authentications] CASCADE
TinyTds::Error: Incorrect syntax near the keyword 'IF'.: DROP TABLE IF EXISTS [dbo].[web_authentications] CASCADE
rake aborted!
ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near the keyword 'IF'.: DROP TABLE IF EXISTS [dbo].[web_authentications] CASCADE

It seems like it isn't correctly building SQL syntax?  Anyone else having trouble with this?  Aren't the rake commands supported?

**Comment by metaskills** [comment]
Please try out v4.2.2, we now have full database task support.
