### ISSUE TITLE
TinyTDS error when using uniq function in has_many, through

### ISSUE THREAD

**Issue by mbratch** [rails-sqlserver/activerecord-sqlserver-adapter#357]
I am currently running:

Windows 7 64-bit
Rails 4.1.1
Ruby 2.0.0p481
tiny_tds [gem] 0.6.2

I have successfully started a rails application to access a remote SQL Server (I'm not sure what the version of the server is). I have a model, `resource.rb`, with the following association:

    class Resource < ActiveRecord::Base
      self.table_name = 'tResources'
      self.primary_key = 'emp_Id'

      has_many :project_resources, foreign_key: 'emp_Id'
      has_many :projects, through: :project_resources
      ...

      default_scope { order("#{Resource.table_name}.lastname ASC") }
      ...

The model `project_resource.rb` has the following:

    class ProjectResource < ActiveRecord::Base
      self.table_name = 'tProject_Resources'
      self.primary_key = 'key_Id'

      belongs_to :project
      belongs_to :resource, foreign_key: 'emp_Id'
      belongs_to :calendar
      ...

This all works great. If I have a resource, `r`, I can get all the projects associated with r by referencing r.projects. However, there are some duplicate projects in this association, so in my view, I'm currently successfully using r.projects.uniq.

I want to move the `uniq` to the `has_many` as follows:

    has_many :projects, -> { uniq }, through: :project_resources

With the association defined this way, the only reference to r.projects that I've tried which succeeds is: `r.projects.count` which does give me an accurate count of unique projects for resource `r`.

However, other references, such as simply `r.projects`, yields an TinyTDS error:

    irb(main):010:0> r.projects
      Project Load (290.0ms)  EXEC sp_executesql N'SELECT DISTINCT *, __order FROM (
     SELECT [tProjects].*, DENSE_RANK() OVER (ORDER BY name ASC) AS __order, ROW_NUM
    BER() OVER (PARTITION BY [tProjects].* ORDER BY name ASC) AS __joined_row_num FR
    OM [tProjects] INNER JOIN [tProject_Resources] ON [tProjects].[project_Id] = [tP
    roject_Resources].[project_id] WHERE [tProject_Resources].[emp_Id] = @0 ) AS __s
    q WHERE __joined_row_num = 1 ORDER BY __order', N'@0 int', @0 = 471  [["emp_Id",
     471]]
    TinyTds::Error: Incorrect syntax near '*'.: EXEC sp_executesql N'SELECT DISTINCT
     *, __order FROM ( SELECT [tProjects].*, DENSE_RANK() OVER (ORDER BY name ASC) A
    S __order, ROW_NUMBER() OVER (PARTITION BY [tProjects].* ORDER BY name ASC) AS _
    _joined_row_num FROM [tProjects] INNER JOIN [tProject_Resources] ON [tProjects].
    [project_Id] = [tProject_Resources].[project_id] WHERE [tProject_Resources].[emp
    _Id] = @0 ) AS __sq WHERE __joined_row_num = 1 ORDER BY __order', N'@0 int', @0
    = 471
    ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near '*'.: EXEC
     sp_executesql N'SELECT DISTINCT *, __order FROM ( SELECT [tProjects].*, DENSE_R
    ANK() OVER (ORDER BY name ASC) AS __order, ROW_NUMBER() OVER (PARTITION BY [tPro
    jects].* ORDER BY name ASC) AS __joined_row_num FROM [tProjects] INNER JOIN [tPr
    oject_Resources] ON [tProjects].[project_Id] = [tProject_Resources].[project_id]
     WHERE [tProject_Resources].[emp_Id] = @0 ) AS __sq WHERE __joined_row_num = 1 O
    RDER BY __order', N'@0 int', @0 = 471

I'm looking for some guidance as to why this error is occurring. Thanks

**Comment by metaskills** [comment]
Please try the v4.2.0 version of the adapter.

**Comment by mbratch** [comment]
The latest available Ruby Gem I can see is 0.6.2 at rubygems.org, which is what I am using. Last update was May 19,  2014. So my problem is unresolved.

**Comment by metaskills** [comment]
Please use the v4.2.0 version "OF THE ADAPTER", not TinyTDS.

**Comment by mbratch** [comment]
Oops nevermind. Brain fart.

**Comment by mbratch** [comment]
When I do my "gem update active records alder versa adapter" it says there's nothing to update. Do I need to upgrade Rails to 4.2 in order to use adapter 4.2.0?

**Comment by metaskills** [comment]
Indeed good sir, we track major/minor versions of Rails for obvious reasons. It may be a small amount of work for you, but 4.2 is the last in the 4.x line and everyone in 4.0 or 4.1 should be upgrading. We do not have the resources to keep working on older 4.x versions. Don't worry, you will love the new 4.2 stuff too. It is highly optimized and works for SQL Server 2012 and upward. Cheers.

http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/

**Comment by mbratch** [comment]
Thanks. I'm not worried. I'm fairly savvy with this stuff. I just needed to know if there was a dependency.

**Comment by mbratch** [comment]
I appreciate all the prompt assistance!

**Comment by mbratch** [comment]
After successfully installing 4.2.0 versions, something else stopped working and one if my other model references started generating invalid SQL. I went back to 4.1.0 since I already have a work around for the original problem.

**Comment by metaskills** [comment]
@mbratch Were you on SQL Server 2012 or higher? The 4.2 adapter is for those versions and higher since we now use OFFSET & FETCH. http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/

**Comment by mbratch** [comment]
Good question. I'll need to confirm with our IT department, as I'm not totally sure. But now that you mention it, I believe the error I say had to do with the use of OFFSET, so that would make total sense. It wouldn't surprise me if we're on an earlier version of SQL Server. I'll report back.

**Comment by mbratch** [comment]
Just confirmed: SQL Server 2005. Oy! Thanks for all the help, Ken. This was a very useful discussion.
