### ISSUE TITLE
ActiveRecord-sqlserver-adapter times out

### ISSUE THREAD

**Issue by tengchh** [rails-sqlserver/activerecord-sqlserver-adapter#360]
I am having a timeout issue ActiveRecord. The query to my MS SQL 2008 is very slow. I changed freetds.conf to use TDS Protocol Version 7.2 and tsql now works fine, but ActiveRecord-sqlserver-based apps are still very slow. I tried changing the database.yml and they are still very slow. What could I do? I am using ruby-1.9.3-p547, activerecord-sqlserver-adapter-3.1.6. Thanks.

**Comment by metaskills** [comment]
Please show me the output of `tsql -C`

**Comment by metaskills** [comment]
1) Show me `tsql -C` output.
2) Did you read [these notes](https://github.com/rails-sqlserver/tiny_tds#freetds-compatibility--configuration) on what different versions mean at different times, compile time, etc?
3) Do not use `td_version` in your adapter conf. You even got the wrong string too per the TinyTDS [source](https://github.com/rails-sqlserver/tiny_tds/blob/master/lib/tiny_tds/client.rb#L7-L17). Either way, I have found no value in any of these other than lowering. Assuming you compiled FreeTDS with a good default `--with-tdsver=7.1` then messing with these things are likely going to bring you grief. 

Please review this and show me what is in that output too. Thanks!
