### ISSUE TITLE
change_column doesn't work when a default_constraint exists

### ISSUE THREAD

**Issue by mwlang** [rails-sqlserver/activerecord-sqlserver-adapter#362]
When running a migration, the change_column method will fail if the table/field has a default constraint.

For example:

    class ExtendAccountNumberLength < ActiveRecord::Migration
      def up
        change_column :business_accounts, :account_number, :string, limit: 25
      end
    end

This produces the following error:

    -- change_column(:business_accounts, :account_number, :string, {:limit=>25})
    rake aborted!
    StandardError: An error has occurred, this and all later migrations canceled:

    TinyTds::Error: The object 'DF__business___a__22401542' is dependent on column 'account_number'.: ALTER TABLE [business_accounts] ALTER COLUMN [account_number] nvarchar(25)/Users/mwlang/.rvm/gems/ruby-2.1.2/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:369:in `do'
    /Users/mwlang/.rvm/gems/ruby-2.1.2/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:369:in `raw_connection_do'
    /Users/mwlang/.rvm/gems/ruby-2.1.2/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:318:in `block (2 levels) in do_execute'
    /Users/mwlang/.rvm/gems/ruby-2.1.2/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver_adapter.rb:387:in `with_sqlserver_error_handling'
    /Users/mwlang/.rvm/gems/ruby-2.1.2/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:318:in `block in do_execute'
    /Users/mwlang/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
    /Users/mwlang/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /Users/mwlang/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
    /Us

The solution is to detect and drop the constraint before changing the column's definition:

    class ExtendAccountNumberLength < ActiveRecord::Migration
      def up
        if constraint = constraint_name(:business_accounts, :account_number)
          puts "Dropping constraint #{constraint}"
          ActiveRecord::Base.connection.execute("ALTER TABLE dbo.business_accounts DROP CONSTRAINT #{constraint}")
        end
        change_column :business_accounts, :account_number, :string, limit: 25
      end
  
      def constraint_name table, column
        sql = <<-SQL
        SELECT 
            dc.Name
        FROM sys.tables t
        INNER JOIN (
            SELECT object_definition(o.object_id) [definition], OBJECT_NAME(o.OBJECT_ID) [Name],
            o.parent_object_id, o.type_desc [ConstraintType], c.colid [parent_column_id]
            FROM sys.objects o
            join sys.sysconstraints c on o.object_id = c.constid
            WHERE type_desc in ('DEFAULT_CONSTRAINT', 'CHECK_CONSTRAINT')) dc ON t.object_id = dc.parent_object_id
        INNER JOIN sys.columns c ON dc.parent_object_id = c.object_id AND c.column_id = dc.parent_column_id
        where t.name = '#{table}' and c.name = '#{column}'
        SQL
        ActiveRecord::Base.connection.select_one(sql)["Name"] rescue nil
      end
    end

Although this worked fine for me since the default constraint was simply "(NULL)" the more correct solution is probably to DROP follow by ADD to restore the default constraint's functionality.  The default value can be found in "dc.definition" (not added to the SELECT clause of the SQL above, but is part of the inner joined select statement).

**Comment by metaskills** [comment]
Can you test the latest v4.2.0.pre http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/

**Comment by mwlang** [comment]
Looks like this release only works on SQL Server 2012.  Does it work at all on SQL Server 2005?  If so, I'll be happy to invest time in testing further.

**Comment by metaskills** [comment]
No, it is for 2012 and up. I have marked this issue 4-1-stable.

**Comment by metaskills** [comment]
Closing this issue for 4-1-stable unless a patch is submitted.
