### ISSUE TITLE
Rake tasks not supported by 'sqlserver' adapter - (Patching from) Rails 4.1.7 to Rails 4.1.8

### ISSUE THREAD

**Issue by bigtunacan** [rails-sqlserver/activerecord-sqlserver-adapter#363]
Running `rake db:setup` or `rake db:schema:load` generates the following error output when moving from Rails 4.1.7 to Rails 4.1.8

This was working correctly up until Rails 4.1.7 and I know that the sqlserver adapter gem has not been updated yet; this appears to be a breaking change in the latest patch version of Rails (4.1.8), but I thought I would open it here as well in case someone can be of help.

The Rails issue has been opened here https://github.com/rails/rails/issues/17693

    ActiveRecord::Tasks::DatabaseNotSupported: Rake tasks not supported by 'sqlserver' adapter
    /Users/bigtunacan/.rvm/gems/ruby-2.1.5@eiacuc/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:215:in `class_for_adapter'
    /Users/bigtunacan/.rvm/gems/ruby-2.1.5@eiacuc/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:144:in `purge'
    /Users/bigtunacan/.rvm/gems/ruby-2.1.5@eiacuc/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:170:in `load_schema_for'
    /Users/bigtunacan/.rvm/gems/ruby-2.1.5@eiacuc/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:185:in `block in load_schema_current'
    /Users/bigtunacan/.rvm/gems/ruby-2.1.5@eiacuc/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:227:in `block in each_current_configuration'
    /Users/bigtunacan/.rvm/gems/ruby-2.1.5@eiacuc/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:226:in `each'
    /Users/bigtunacan/.rvm/gems/ruby-2.1.5@eiacuc/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:226:in `each_current_configuration'
    /Users/bigtunacan/.rvm/gems/ruby-2.1.5@eiacuc/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:184:in `load_schema_current'
    /Users/bigtunacan/.rvm/gems/ruby-2.1.5@eiacuc/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:238:in `block (3 levels) in <top (required)>'
    /Users/bigtunacan/.rvm/gems/ruby-2.1.5@eiacuc/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:242:in `block (3 levels) in <top (required)>'
    /Users/bigtunacan/.rvm/gems/ruby-2.1.5@eiacuc/bin/ruby_executable_hooks:15:in `eval'
    /Users/bigtunacan/.rvm/gems/ruby-2.1.5@eiacuc/bin/ruby_executable_hooks:15:in `<main>'

I'm still digging into this to see if I can find where the issue is, but I've been at it for the last 2 days straight with no luck so far.  Just trying to get this in place for the latest security patch.

**Comment by metaskills** [comment]
I'm in it again, but the database support still needs some help. Moved to here.

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/380
