### ISSUE TITLE
Default pessimistic lock should be update lock

### ISSUE THREAD

**Issue by yellowKompressor** [rails-sqlserver/activerecord-sqlserver-adapter#368]
Default pessimistic lock (i.e. Model.lock) is implemented as 'WITH(HOLDLOCK, ROWLOCK)'.
The purpose of the lock is to prevent deadlocks in case of select, update sequence. It translates to SELECT ... FOR UPDATE for most databases. 

HOLDLOCK, ROWLOCK does not provide that level of protection.
UPDLOCK is the equivalent of FOR UPDATE in SQL server.

**Comment by metaskills** [comment]
Thanks for that information. I have fixed this in the latest 4.2.x work ongoing in master. The 4.2 version of the adapter should be release in a week or so. Cheers!
