### ISSUE TITLE
Conversion failed when converting the varchar value 'null' to data type int.

### ISSUE THREAD

**Issue by anujaware** [rails-sqlserver/activerecord-sqlserver-adapter#370]
I have upgraded version to 4.1.0. But while creating a record its not setting default values to fields and throwing above error.

**Comment by anujaware** [comment]
Thank you!

**Comment by metaskills** [comment]
This should be fixed in the latest 4.2 pre-release that just hit.
http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/
