### ISSUE TITLE
Database Task Support

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/activerecord-sqlserver-adapter#380]
Here are some notes I made while working on 4.2.

```ruby
def truncate(table_name, name = nil)
  raise NotImplementedError
end
```

* Add a truncate method to the connection.
*  The `db:schema:load` and `db:structure:load` no longer purge the database before loading the schema. This is left for the user to do. `db:test:prepare` will still purge the database. Closes #17945.
* Bring back `db:test:prepare` to synchronize the test database schema. Manual synchronization using `bin/rake db:test:prepare` is required when a migration is rolled-back, edited and reapplied. `ActiveRecord::Base.maintain_test_schema` now uses `db:test:prepare` to synchronize the schema. Plugins can use this task as a hook to provide custom behavior after the schema has been loaded. NOTE: `test:prepare` runs before the schema is synchronized.Fixes #17171, #15787.
* Add `bin/rake db:purge` task to empty the current database.
* No verbose backtrace by `db:drop` when database does not exist.
* Schema loading rake tasks (like `db:schema:load` and `db:setup`) maintain the database connection to the current environment.

**Comment by metaskills** [comment]
Tons of work in #351 cc @agios

**Comment by metaskills** [comment]
More work in #366

**Comment by metaskills** [comment]
Rather than pull in each PR, I learned from them and implemented something very similar. Thank you so much to both @agios and @bigtunacan for your work. Feedback on my commit is very much welcome. Here are my thoughts on the implementation.

* I am not a fan of the stubbed and mocked testing. Easily passing those tests did not ensure things actually worked. I crated a 4.1 test project (https://github.com/rails-sqlserver/ss_app) that smoke tested too. If you look at the new tests, you will see how they actually exercise the real code. And, it looks much much cleaner if you ask me.
* I even fixed a case where `defncopy` would report the length for a nvarchar as 8000 vs 4000.

**Comment by metaskills** [comment]
Also, I made `structure_load` just execute the SQL file. Much easier if you ask me.

**Comment by metaskills** [comment]
Real commit is here: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/commit/348361d94553c49033c2698200485cda1915e8d2

**Comment by rebelweb** [comment]
Will changes to the database tasks be able, to be backported to the adapter for 4.1.x? I am bound to SQL Server 2008 R2 for the time being, so I will be unable to upgrade to Rails 4.2 at this point.

**Comment by metaskills** [comment]
Yes, If someone were to make a comprehensive and tested PR to our 4-1-stable branch.

**Comment by ike** [comment]
Hey there! I have recently started working on a huge Rails application that is connecting to several legacy systems. I am loving this gem, and I need the 4.1.x backport. Has anyone been working on it who I could help out? Otherwise, we'll work on a PR for this.

Thanks so much for everything – this gem has made a huge difference for us.

**Comment by metaskills** [comment]
I don't know of one. Please have at it.
