### ISSUE TITLE
Provide A SQL For Insert Configuration

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/activerecord-sqlserver-adapter#381]
Due to supporting UUID inserts, our `sql_for_insert` now uses `OUTPUT INSERTED.#{quoted_pk}`. This causes issue with tables that have triggers as noted by issue #339. Let's either do one of the following:

1) Check if we are doing an insert for a UUID table. May be kind of hard since we are loosing potential table/column reflection since `binds` is not guaranteed to have these.
2) Provide a user configuration to globally disable this and always use `SCOPE_IDENTITY()`.
3) Something else?

**Comment by petervandenabeele** [comment]
Thank you!

I can confirm the patch works for solving https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/339 in our case (was introduced by an upgrade from Rails 4.1.5 to 4.2.0).

With version 4.2.3 of activerecord-sqlserver-adapter (which was pulled in with the recent upgrade to Rails 4.2.0), I added this code to an initializer along these lines and this solved it:

```
if ActiveRecord::Base.connection.class.name.match(/SQLServerAdapter/)
  ActiveRecord::ConnectionAdapters::SQLServerAdapter.use_output_inserted = false
end
```

**Comment by oneiros** [comment]
I have this exact issue, but am stuck on 4.1 for now. Any chance this fix will get backported?

**Comment by metaskills** [comment]
Sure, I have stated before that I am ready to take an tested patch to our 4-1-stable branch. I just don't have the time myself but can take it from there if someone else does.

**Comment by oneiros** [comment]
Thanks a lot for the quick reply.

7acfc14f0bb8135a57ffc0858588dc0cce3ff077 is pretty simple and it should be easy to incorporate this into 4-1-stable. But sadly it includes no tests.

Could you provide me with a hint, where the most appropriate place to add tests for this would be? And can this be tested without a running mssql server?

If yes, I would be happy to prepare a PR.

**Comment by metaskills** [comment]
Tested does not have to mean new tests are added. It could mean you run them to see if things break.
