### ISSUE TITLE
Incorrect syntax near 'OFFSET' when using Limit

### ISSUE THREAD

**Issue by aridnei** [rails-sqlserver/activerecord-sqlserver-adapter#382]
Hi,

Using rails 4.2.0 + activerecord-sqlserver-adapter 4.2.0 + tiny_tds 0.6.2 + SQLServer 2008 R2, I get query syntax error like that...

TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [company].* FROM [company]  ORDER BY [company].[IDCompany] ASC OFFSET 0 ROWS FETCH NEXT 5 RO
WS ONLY'

Here rails console error ...
 
2.1.3p242 :018 >   Company.limit(5)
  Company Load (40.3ms)  EXEC sp_executesql N'SELECT  [company].* FROM [company]  ORDER BY [company].[IDCompany] ASC OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY'
TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [company].* FROM [company]  ORDER BY [company].[IDCompany] ASC OFFSET 0 ROWS FETCH NEXT 5 RO
WS ONLY'
ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [company].* FROM [company]  ORDER BY [company].[IDCompany] A
SC OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-sqlserver-adapter-4.2.0/lib/active_record/connection_adapters/sqlserver/database_statements.r
b:401:in `each'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-sqlserver-adapter-4.2.0/lib/active_record/connection_adapters/sqlserver/database_statements.r
b:401:in `handle_to_names_and_values_dblib'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-sqlserver-adapter-4.2.0/lib/active_record/connection_adapters/sqlserver/database_statements.r
b:390:in `handle_to_names_and_values'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-sqlserver-adapter-4.2.0/lib/active_record/connection_adapters/sqlserver/database_statements.r
b:365:in `_raw_select'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-sqlserver-adapter-4.2.0/lib/active_record/connection_adapters/sqlserver/database_statements.r
b:360:in `block in raw_select'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-sqlserver-adapter-4.2.0/lib/active_record/connection_adapters/sqlserver/database_statements.r
b:360:in `raw_select'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-sqlserver-adapter-4.2.0/lib/active_record/connection_adapters/sqlserver/database_statements.r
b:309:in `sp_executesql'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-sqlserver-adapter-4.2.0/lib/active_record/connection_adapters/sqlserver/database_statements.r
b:19:in `exec_query'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-sqlserver-adapter-4.2.0/lib/active_record/connection_adapters/sqlserver/database_statements.r
b:264:in `select'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all
'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.2.0/lib/active_record/querying.rb:39:in `find_by_sql'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.2.0/lib/active_record/relation.rb:638:in `exec_queries'
... 4 levels...
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
        from /Users/aridneicarmo/Documents/Aptana Studio 3 Workspace/Guazzelli-TimeSheet/bin/rails:8:in `<top (required)>'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/aridneicarmo/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
        from /Users/aridneicarmo/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/aridneicarmo/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by metaskills** [comment]
>  SQLServer 2008 R2

This is an unsupported version of SQL Server. Please read this title.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter

**Comment by colepanike** [comment]
Does this mean that in order to use rails with a 2008 server I have to downgrade rails?

**Comment by metaskills** [comment]
@colepanike That statement is not entirely true. If you are on SQL Server 2008 and this is a new project, then you are not downgrading, you are just limited to Rails 4.1 which is still supported and in some ways faster than 4.2 too. Downgrading implies that you are already at 4.2 which can not be the case since it requires 2012 and higher. HTH. You can read more info in #397 if you are curious as to why this happened.

**Comment by neohunter** [comment]
So, SQLSERVER 2008 works with this gem only till rails 4.1? Please confirm @metaskills

**Comment by neohunter** [comment]
I just confirmed that downgrade to rails 4.1.2 fixes the problem.

**Comment by tommyalvarez** [comment]
@metaskills I already have a Rails 5.0.1 project that i **can't** downgrade down to Rails 4.1. I need to connect to a sql server 2005 database. I only need the adapter to support limit and offset because the only queries i will be doing are _selects_ . Is there a monkey patch or something that can be done in order to support Rails 5 and sql server 2005/2008 LIMIT and OFFSET?

**Comment by metaskills** [comment]
> Is there a monkey patch or something that can be done in order to support Rails 5 and sql server 2005/2008 LIMIT and OFFSET?

No.

**Comment by metaskills** [comment]
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/571#issuecomment-283443927
