### ISSUE TITLE
4.2.0 private method "include" error

### ISSUE THREAD

**Issue by natematykiewicz** [rails-sqlserver/activerecord-sqlserver-adapter#383]
On 4.2.0, when I try to start Rails 4.2.0, I get an error about private method "include" being called by ActiveRecord::ConnectionAdapters::Transaction

Looking at this file,
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/v4.2.0/lib/active_record/connection_adapters/sqlserver/transaction.rb, I assume it will also get mad when RealTransaction tries to include a module.

I tried on ruby-1.9.3-p547, got the error, and thought maybe "include" is a public method in Ruby 2, but it also errors on ruby-2.0.0-p0.

**Comment by metaskills** [comment]
Thanks, I forgot 4.2 was for 1.9+. I just released v4.2.1 which should fix this. Enjoy.

**Comment by natematykiewicz** [comment]
Perfect, thanks!
