### ISSUE TITLE
Problem with '.first' and '.find_by' in 4.2.1 and Rails 4.2.0

### ISSUE THREAD

**Issue by ydkn** [rails-sqlserver/activerecord-sqlserver-adapter#384]
When using *first* or *find_by* with 4.2.1 and Rails 4.2.0 an invalid sql query is being executed.

```
Loading development environment (Rails 4.2.0)
2.1.5 :001 > User.first
  User Load (26.5ms)  EXEC sp_executesql N'SELECT  [users].* FROM [users]  ORDER BY [users].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'
TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [users].* FROM [users]  ORDER BY [users].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'
ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [users].* FROM [users]  ORDER BY [users].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-sqlserver-adapter-4.2.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:401:in `each'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-sqlserver-adapter-4.2.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:401:in `handle_to_names_and_values_dblib'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-sqlserver-adapter-4.2.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:390:in `handle_to_names_and_values'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-sqlserver-adapter-4.2.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:365:in `_raw_select'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-sqlserver-adapter-4.2.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:360:in `block in raw_select'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-sqlserver-adapter-4.2.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:360:in `raw_select'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-sqlserver-adapter-4.2.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:309:in `sp_executesql'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-sqlserver-adapter-4.2.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:19:in `exec_query'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-sqlserver-adapter-4.2.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:264:in `select'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/querying.rb:39:in `find_by_sql'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation.rb:638:in `exec_queries'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation.rb:514:in `load'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation.rb:243:in `to_a'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:512:in `find_nth_with_limit'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:496:in `find_nth'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:139:in `first'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/querying.rb:3:in `first'
	from (irb):1
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/fl/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by metaskills** [comment]
Are you not on 2012 and higher?
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter#readme

**Comment by ydkn** [comment]
Damn, I totally missed that fact that it's now 2012 and higher - it's a 2008 R2 Server.

So I guess the only way is to stick with Rails 4.1.x and activerecord-sqlserver-adapter 4.1.0?

**Comment by metaskills** [comment]
Yes, that's true. I myself wont be putting any more work into our 4-1-stable branch, but if you ever find issues and submit a tested PR, will will get them in and publish new 4.1.x gems. Cheers.

**Comment by clsoemail** [comment]
I am using Rails 4.2.1 connecting to SQL server 2008 r2 SP 3 and getting error TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [u
sers].* FROM [users]  ORDER BY [users].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS
ONLY' ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near 'OFFSET'.:
 EXEC sp_executesql N'SELECT  [users].* FROM [users]  ORDER BY [users].[id] ASC
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'. Any advice would be help full. I am following Ruby on Rails Tutorial (3rd Ed.) And getting this on Chapter 7

**Comment by clsoemail** [comment]
I have activerecord-sqlserver-adapter (4.2.4, 4.1.0) installed

**Comment by clsoemail** [comment]
Any Advice were I am going "haywire". irb(main):003:0> User.first
  User Load (0.0ms)  EXEC sp_executesql N'SELECT  [users].* FROM [users]  ORDER
BY [users].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'
TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [u
sers].* FROM [users]  ORDER BY [users].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS
ONLY'
ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near 'OFFSET'.:
 EXEC sp_executesql N'SELECT  [users].* FROM [users]  ORDER BY [users].[id] ASC
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'

**Comment by theangryangel** [comment]
What version of sql server are you using? The 4.2 version only supports 2012 r2 and newer. In prior versions the fetch and offset statements don't exist.

**Comment by clsoemail** [comment]
SQL Server 2008 R2 Service Pack 3

**Comment by clsoemail** [comment]
tiny_tds (0.7.0 x86-mingw32, 0.6.2 x86-mingw32)
activerecord-sqlserver-adapter (4.2.4, 4.1.0)

**Comment by clsoemail** [comment]
This the entry in my GemFile: gem 'activerecord-sqlserver-adapter'

**Comment by clsoemail** [comment]
Here is the strange part that I don't understand is that I can create my tables and fields successfully but not query or update those field with my current SQL adapater

**Comment by metaskills** [comment]
Because...

> The 4.2 version only supports 2012 r2 and newer. In prior versions the fetch and offset statements don't exist.

**Comment by clsoemail** [comment]
Thanks so much. So help me here how should I a just my gem file with the correct entry ?

**Comment by clsoemail** [comment]
then I l can update it with the bundle install command

**Comment by metaskills** [comment]
Your Rails version should be set in your Gemfile. We automatically go by that version. So if you have Rails `~> 4.1.x` then you will get the right version of the adapter.

**Comment by clsoemail** [comment]
currently I am running: Rails 4.2.1

**Comment by clsoemail** [comment]
So can I a just it with: gem 'rails', '4.1'

**Comment by metaskills** [comment]
> currently I am running: Rails 4.2.1

That's the problem... each adapter is coupled to the Rails version. You can not use the 4.2 adapter with anything below 2012. That means you can not use Rails 4.2.

**Comment by metaskills** [comment]
> So can I a just it with: gem 'rails', '4.1'

Nope.

**Comment by clsoemail** [comment]
Which rails version for SQL server 2008 R2 SP 3 would you recommend. Thanks so much for Assisting !

**Comment by metaskills** [comment]
> So can I a just it with: gem 'rails', '4.1'

So if you set that in your gem file, you would be downgrading your app. Which would allow the adapter to work. Without knowing where you are in the process, it is hard to say. But just know... if you are on 2008 DB, then you need to use Rails 4.1

**Comment by metaskills** [comment]
> Which rails version for SQL server 2008 R2 SP 3 would you recommend. Thanks so much for Assisting !

Rails 4.1... we maintain the 4-1-stable branch of the adapter. So you are in good hands.

**Comment by clsoemail** [comment]
Sweet thanks a  million, Let me try and then advise

**Comment by clsoemail** [comment]
And I guess it does not matter what version of tiny_tds I use ?

**Comment by metaskills** [comment]
> And I guess it does not matter what version of tiny_tds I use?

Not at all! Just go with latest release on that one.

**Comment by clsoemail** [comment]
Does Any one have guide into incorporating WMI commands and queries on my rails apps ?

**Comment by clsoemail** [comment]
For instance I have my scripts that is running WMI queries but I want to incorporate that into my rails application.

**Comment by clsoemail** [comment]
And then import that data into the SQL database via my RAILS app

**Comment by clsoemail** [comment]
For example: get-wmiobject -namespace root\cimv2 -class win32_bios | select serialnumber,manufacturer
