### ISSUE TITLE
Something broke between 4.2.0 and 4.2.2

### ISSUE THREAD

**Issue by zacharyabresch** [rails-sqlserver/activerecord-sqlserver-adapter#385]
I had this working perfectly in one app but, when I started a new app today, I was getting errors when trying to access the *very same* data that my original app was able to access.

```ruby
ItemMaster.all
  SQL (42.9ms)  USE [TCOS]
  ItemMaster Load (3675.4ms)  EXEC sp_executesql N'SELECT [IV00101].* FROM [IV00101]'
(Object doesn't support #inspect)
```

I did some comparisons between gem installations (i.e. `bundle list`) and found one difference:

## Original App
* `activerecord-sqlserver-adapter (4.2.0 2554ffe)`

## New App
* `activerecord-sqlserver-adapter (4.2.2 bfa8cab)`

When I updated my new app's `Gemfile` with this line: `gem 'activerecord-sqlserver-adapter', git: "https://github.com/rails-sqlserver/activerecord-sqlserver-adapter.git", :ref => '2554ffe'` and everything worked fine!!

I don't know what specifically caused the issue and didn't have time to dig any deeper. I wasted plenty of time just tracking and fixing it as above.

Let me know if you need any more information. Cheers!

**Comment by metaskills** [comment]
Sorry, I need some more info. The 2554ffe SHA was prior to any 4.2.0 work. Despite what the version says. SHA bfa8cab is the latest master. Can you just use the real gem versions and show me a complete stack trace?

**Comment by metaskills** [comment]
Wait a minute, is this even an issue? I think that is just new Rails behavior. The `all` method does not return an array, it is a ActiveRecord relation. Treat it as a enumerable collection if you want to see all the objects it returns.
