### ISSUE TITLE
Timeout issues

### ISSUE THREAD

**Issue by jwoertink** [rails-sqlserver/activerecord-sqlserver-adapter#386]
I'm using the latest gem `4.2.2` with TinyTds `0.6.2` on SQL Azure 11.0.9, but I still seem to be getting these weird timeout issues. 

If I go into the rails console in production and make a query, then step away for ~15 min then make another simple query like `SELECT @@Version` I'll get a timeout error:

```
irb(main):014:0> ActiveRecord::Base.connection.execute("SELECT @@Version")
TinyTds::Error: Adaptive Server connection timed out: SELECT @@Version
```

Then of course making a second call will have the process is dead error

```
irb(main):017:0* ActiveRecord::Base.connection.execute("SELECT @@Version")
TinyTds::Error: DBPROCESS is dead or not enabled: SELECT @@Version
```

My issue is that I have an app that works more like a kiosk than a normal rails web app. It might lie dormant for up-to an hour at a time. When loading the app for the first time, it takes more than a minute to get going, and in the logs it says that the connection is dead, so it has to create a new connection. Once it's "awake", then each request runs fine and rather fast. 

I've tried different things like changing the `timeout` in the database.yml. I changed the `pool`, and even added the `reaping_frequency`, but I'm running out of ideas on what causes this. It's probably just a setting I'm doing, but I'm more of a mongodb guy so I'm not used to this lol. Thanks!

**Comment by metaskills** [comment]
I believe this issue duplicates https://github.com/rails-sqlserver/tiny_tds/pull/162

**Comment by jwoertink** [comment]
Ah, yeah! This totally looks like what I'm seeing. Maybe I'll try that fork with the pull request and see if that fixes my issue. I'll report back on that issue if it does.
