### ISSUE TITLE
can't support sqlserver 2005/2008/2008R2 under rails 4.2

### ISSUE THREAD

**Issue by gzliudan** [rails-sqlserver/activerecord-sqlserver-adapter#388]
When can support sqlserver 2005/2008/2008R2 under rails 4.2?

**Comment by metaskills** [comment]
Never, that's not happening. Please use 4.1 or lower. http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/

**Comment by gzliudan** [comment]
Then does activerecord-sqlserver-adapter 4.1 can support sqlserver 2005, 2008, 2008R2, 2012, 2014 under rails 4.1?

**Comment by metaskills** [comment]
Yes.

**Comment by gzliudan** [comment]
thank you very much! 
I have to use rails 4.1.




------------------ 原始邮件 ------------------
发件人: "Ken Collins";<notifications@github.com>;
发送时间: 2015年2月8日(星期天) 晚上8:45
收件人: "rails-sqlserver/activerecord-sqlserver-adapter"<activerecord-sqlserver-adapter@noreply.github.com>; 
抄送: "广州刘丹"<139250065@qq.com>; 
主题: Re: [activerecord-sqlserver-adapter] can't support sqlserver2005/2008/2008R2 under rails 4.2 (#388)




Yes.
