### ISSUE TITLE
Getting error while saving record with column "id" with type UUID using activerecord-sqlserver-adapter (4.1.0)

### ISSUE THREAD

**Issue by anujaware** [rails-sqlserver/activerecord-sqlserver-adapter#389]
I have a table with primary_key id of type uuid.  When I am trying to save object with id value as follows:
"\<Visit id\: \#\<UUID\:0x38a3efc UUID\:b2553d47-81c0-4b3d-85dc-caa37bb20de7\>\>"

This id is getting converted into a string while saving object as follows:
"x'b2553d4781c04b3d85dccaa37bb20de7'"

And I am getting error:
**TinyTds::Error: Incorrect syntax near 'b2553d4781c04b3d85dccaa37bb20de7'.: EXEC sp_executesql N'INSERT INTO [visits] ([id]) OUTPUT inserted.id VALUES (@0)', N'@0 uniqueidentifier', @0 = x'b2553d4781c04b3d85dccaa37bb20de7'**

After debug I observed as follows:
In this file lib/active_record/connection_adapters/sqlserver/quoting.rb following method:

    def quote(value, column = nil)
          case value
          when String, ActiveSupport::Multibyte::Chars
            if column && column.type == :integer && value.blank?
              value.to_i.to_s
            elsif column && column.type == :binary
              column.class.string_to_binary(value)
            elsif column && [:uuid, :uniqueidentifier].include?(column.type)
              "'#{quote_string(value)}'"
          ...
          ...
    end

In above method we need to handle UUIDTools::UUID class or column with type [:uuid, :uniqueidentifier].
Because in old rails (as I was using is 3.2.15) we were getting id column value as a String so we were returning value "'#{quote_string(value)}'" which will be something like 
"\<Visit id\: \#\<UUID\:0x38a3efc UUID\:b2553d47-81c0-4b3d-85dc-caa37bb20de7\>\>"

But now rails returns this by typecasting it and returning:
"x'b2553d4781c04b3d85dccaa37bb20de7'"

I am not able to resolve this in activerecord but in our gem if we handle above mentioned column types its working. 

    def quote(value, column = nil)
          if column && [:uuid, :uniqueidentifier].include?(column.type)
            return "'#{quote_string(value)}'"
          end
          case value
          when String, ActiveSupport::Multibyte::Chars
            if column && column.type == :integer && value.blank?
              value.to_i.to_s
            elsif column && column.type == :binary
              column.class.string_to_binary(value)
            elsif column && [:uuid, :uniqueidentifier].include?(column.type)
              "'#{quote_string(value)}'"
          ...
          ...
    end

OR

     def quote(value, column = nil)
          case value
          when String, ActiveSupport::Multibyte::Chars, UUIDTools::UUID
            if column && column.type == :integer && value.blank?
              value.to_i.to_s
            elsif column && column.type == :binary
              column.class.string_to_binary(value)
            elsif column && [:uuid, :uniqueidentifier].include?(column.type)
              "'#{quote_string(value)}'"
          ...
          ...
    end

Please help me to figure this out.

**Comment by metaskills** [comment]
I am a little confused, I think I hear you saying that you are using the latest 3.2.x version of Rails and/or the Adapter. However, that insert SQL is not from our 3.2 adapter. We did not yet use `OUTPUT inserted.id`. Are you working with your own version of the adapter or what is happening here?

**Comment by anujaware** [comment]
Sorry forgot to mention version details. I was using rails 3.2.15 and it was working there because activerecord was not typecasting uuid column and we were getting String activerecord. So it was matching with first case in 'quote' method and its working in this rails version

But now I upgraded rails version to 4.1.8 and activerecord-sqlserver-adapter to 4.1.0.
And as I observed in this rails version when we are trying to access this uuid column value it returns object of UUIDTools::UUID class. 

In "quote" method we have not handle column with type uuid and it goes in else part and in active record (rails's activerecord) at one point its getting converted into "x'b2553d4781c04b3d85dccaa37bb20de7'" this format and it breaking when I am trying to save object.

If we handle this in our code as I specified above (either of two) its working fine.

**Comment by metaskills** [comment]
Are you able to use the 4.2 version of the adapter? This is fixed in that version.

**Comment by anujaware** [comment]
Thank you for response. 
Since we are upgrading our rails app from 3.2.15 to rails 4.1.8, for now we can not use 4.2 version. Can we use above patch as I mentioned in above comment? Or please let me know if there is any other change that I need to do to make this work using 4.1?

**Comment by metaskills** [comment]
The first looks like it may work. Not a fan of the second that is specific to your domain. I will happily take a pull request that has a tested (meaning you run our tests) patch for this if you find time.

**Comment by anujaware** [comment]
Yes I thought same about second option so I suggested first one.  I would like to send pull request. I will try to add test case for this and will send pull request.

**Comment by anujaware** [comment]
I am trying to do set-up 4-1-stable branch on my local machine but getting  lot of errors.. 

1st Its just stuck while fetching **'rails',  git: "git://github.com/rails/rails.git", tag: "v#{version}"**. Since I am using rails 4.1.8, I tried with **gem 'rails', '4.1.8'**

After this I am trying to run test suit but getting errors for missing files and undefined variables. Can you please help me if I am missing anything?

**Comment by metaskills** [comment]
Works great here. Did you forget to whack your Gemfile.lock?

```
$ git checkout 4-1-stable
$ rm Gemfile.lock
$ bundle install
```

**Comment by anujaware** [comment]
I have cloned 4-1-stable branch. I tried by removing Gemfile.lock and bundle but there are some missing files. 
For example:

**`require': cannot load such file -- cases/helper (LoadError)**  (test/cases/sqlserver_helper.rb:29)
**`require': cannot load such file -- models/topic (LoadError)**  (test/cases/sqlserver_helper.rb:30)
**`require': cannot load such file -- cases/test_case.rb (LoadError)** (test/cases/sqlserver_test_case.rb:1)
**`<class:SQLCounter>': undefined local variable or method `ignored_sql' for ActiveRecord::SQLCounter:Class (NameError)** (/test/cases/sqlserver_test_case.rb:12)
`read': No such file or directory @ rb_sysopen - /home/anuja/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/test/schema/schema.rb (activerecord-sqlserver-adapter/test/cases/sqlserver_helper.rb:121:in )
...

I was trying by commenting lines one by one and getting above errors.

And I tried running it on master branch and there its giving following error:

Using dblib
Info: Undefined coerced test: ActiveRecord::AdapterTest#test_update_prepared_statement
Info: Undefined coerced test: AttributeMethodsTest#test_typecast_attribute_from_select_to_false
Info: Undefined coerced test: AttributeMethodsTest#test_typecast_attribute_from_select_to_true
Info: Undefined coerced test: BasicsTest#test_column_names_are_escaped
Info: Undefined coerced test: BasicsTest#test_numeric_fields
Info: Undefined coerced test: BasicsTest#test_respect_internal_encoding
Info: Undefined coerced test: BelongsToAssociationsTest#test_belongs_to_does_not_use_order_by
Info: Undefined coerced test: BelongsToAssociationsTest#test_belongs_to_with_primary_key_joins_on_correct_column
Info: Undefined coerced test: ActiveRecord::BindParameterTest#test_binds_are_logged
Info: Undefined coerced test: ActiveRecord::BindParameterTest#test_binds_are_logged_after_type_cast
Info: Undefined coerced test: CalculationsTest#test_should_return_decimal_average_of_integer_field
Info: Undefined coerced test: CalculationsTest#test_limit_is_kept
Info: Undefined coerced test: CalculationsTest#test_limit_with_offset_is_kept
Info: Undefined coerced test: ActiveRecord::Migration::ChangeSchemaTest#test_create_table_with_bigint
Info: Undefined coerced test: ActiveRecord::Migration::ChangeSchemaTest#test_create_table_with_defaults
Info: Undefined coerced test: ActiveRecord::Migration::ChangeSchemaWithDependentObjectsTest#test_create_table_with_force_cascade_drops_dependent_objects
Info: Undefined coerced test: ActiveRecord::Migration::ColumnAttributesTest#test_add_column_without_limit
Info: Undefined coerced test: ActiveRecord::Migration::ColumnsTest#test_rename_column_preserves_default_value_not_null
Info: Undefined coerced test: ActiveRecord::Migration::ColumnsTest#test_remove_column_with_multi_column_index
Info: Undefined coerced test: CoreTest#test_pretty_print_persisted
Info: Undefined all tests: ActiveRecord::ConnectionAdapters::TypeLookupTest
Info: Undefined all tests: ActiveRecord::ConnectionAdapters::MergeAndResolveDefaultUrlConfigTest
Info: Undefined coerced test: ActiveRecord::DatabaseTasksCreateAllTest#test_ignores_remote_databases
Info: Undefined coerced test: ActiveRecord::DatabaseTasksCreateAllTest#test_warning_for_remote_databases
Info: Undefined coerced test: ActiveRecord::DatabaseTasksDropAllTest#test_ignores_remote_databases
Info: Undefined coerced test: ActiveRecord::DatabaseTasksDropAllTest#test_warning_for_remote_databases
Info: Undefined coerced test: DefaultScopingTest#test_order_in_default_scope_should_not_prevail
Info: Undefined coerced test: EachTest#test_find_in_batches_should_quote_batch_order
Info: Undefined coerced test: EagerAssociationTest#test_count_with_include
Info: Undefined coerced test: EagerAssociationTest#test_0013_including association based on sql condition and no database column
Info: Undefined coerced test: FinderTest#test_0006_find_by doesn't have implicit ordering
Info: Undefined coerced test: FinderTest#test_0010_find_by! doesn't have implicit ordering
Info: Undefined coerced test: FinderTest#test_find_doesnt_have_implicit_ordering
Info: Undefined coerced test: FinderTest#test_exists_does_not_select_columns_without_alias
Info: Undefined coerced test: FinderTest#test_string_sanitation
Info: Undefined coerced test: FinderTest#test_take_and_first_and_last_with_integer_should_use_sql_limit
Info: Undefined coerced test: FinderTest#test_find_with_order_on_included_associations_with_construct_finder_sql_for_association_limiting_and_is_distinct
Info: Undefined coerced test: ActiveRecord::Migration::ForeignKeyTest#test_add_on_delete_restrict_foreign_key
Info: Undefined coerced test: HasOneAssociationsTest#test_has_one_does_not_use_order_by
Info: Undefined coerced test: InheritanceTest#test_a_bad_type_column
Info: Undefined coerced test: InheritanceTest#test_eager_load_belongs_to_primary_key_quoting
Info: Undefined coerced test: MigrationTest#test_add_table_with_decimals
Info: Undefined coerced test: NamedScopingTest#test_scopes_honor_current_scopes_from_when_defined
Info: Undefined coerced test: NestedRelationScopingTest#test_merge_options
Info: Undefined coerced test: PersistenceTest#test_update_columns_changing_id
Info: Undefined coerced test: PersistenceTest#test_update_all_doesnt_ignore_order
Info: Undefined coerced test: PersistenceTest#test_update_attributes
Info: Undefined coerced test: ActiveRecord::PredicateBuilderTest#test_registering_new_handlers
Info: Undefined coerced test: QueryCacheTest#test_cache_does_not_wrap_string_results_in_arrays
Info: Undefined coerced test: RelationTest#test_0005_find_by doesn't have implicit ordering
Info: Undefined coerced test: RelationTest#test_0009_find_by! doesn't have implicit ordering
Info: Undefined coerced test: RelationTest#test_order_using_scoping
Info: Undefined coerced test: RelationTest#test_to_sql_on_eager_join
Info: Undefined coerced test: RelationTest#test_default_scope_order_with_scope_order
Info: Undefined coerced test: SanitizeTest#test_sanitize_sql_like_example_use_case
Info: Undefined coerced test: SchemaDumperTest#test_schema_dump_keeps_large_precision_integer_columns_as_decimal
Info: Undefined coerced test: SchemaDumperTest#test_types_line_up
Info: Undefined coerced test: TestAdapterWithInvalidConnection#test_0001_inspect on Model class does not raise
Info: Undefined coerced test: TransactionTest#test_releasing_named_savepoints
Info: Undefined coerced test: TransactionIsolationTest#test_0002_read committed
Info: Undefined coerced test: TransactionIsolationTest#test_0003_repeatable read
Info: Undefined coerced test: ActiveRecord::WhereChainTest#test_not_eq_with_array_parameter
Info: Undefined coerced test: ViewWithPrimaryKeyTest#test_does_not_assume_id_column_as_primary_key
Info: Undefined coerced test: YamlSerializationTest#test_types_of_virtual_columns_are_not_changed_on_round_trip
/home/anuja/.rvm/gems/ruby-2.1.5/bundler/gems/rails-a6cfe96cb88e/activesupport/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- guard (LoadError)
	from /home/anuja/.rvm/gems/ruby-2.1.5/bundler/gems/rails-a6cfe96cb88e/activesupport/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/anuja/.rvm/gems/ruby-2.1.5/bundler/gems/rails-a6cfe96cb88e/activesupport/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/anuja/.rvm/gems/ruby-2.1.5/bundler/gems/rails-a6cfe96cb88e/activesupport/lib/active_support/dependencies.rb:274:in `require'
	from /home/anuja/.rvm/gems/ruby-2.1.5/gems/guard-minitest-2.4.4/lib/minitest/guard_minitest_plugin.rb:4:in `<top (required)>'
	from /home/anuja/.rvm/gems/ruby-2.1.5/bundler/gems/rails-a6cfe96cb88e/activesupport/lib/active_support/dependencies.rb:274:in `require'
	from /home/anuja/.rvm/gems/ruby-2.1.5/bundler/gems/rails-a6cfe96cb88e/activesupport/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/anuja/.rvm/gems/ruby-2.1.5/bundler/gems/rails-a6cfe96cb88e/activesupport/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/anuja/.rvm/gems/ruby-2.1.5/bundler/gems/rails-a6cfe96cb88e/activesupport/lib/active_support/dependencies.rb:274:in `require'
	from /home/anuja/.rvm/gems/ruby-2.1.5/gems/minitest-5.3.3/lib/minitest.rb:90:in `block in load_plugins'
	from /home/anuja/.rvm/gems/ruby-2.1.5/gems/minitest-5.3.3/lib/minitest.rb:84:in `each'
	from /home/anuja/.rvm/gems/ruby-2.1.5/gems/minitest-5.3.3/lib/minitest.rb:84:in `load_plugins'
	from /home/anuja/.rvm/gems/ruby-2.1.5/gems/minitest-5.3.3/lib/minitest.rb:113:in `run'
	from /home/anuja/.rvm/gems/ruby-2.1.5/gems/minitest-5.3.3/lib/minitest.rb:55:in `block in autorun'
rake aborted!
Command failed with status (1):
...

**Comment by metaskills** [comment]
I did another read thru of this issue and I am not certain this is something that 4.1 should fix. The core issue is that UUIDs are strings and somewhere in your stack you have a UUID object type that needs quoting. You should make sure you assign a string to the model, not an object in 4.1. In later versions of Rails 4.2 and up, you can create your own custom types that do this for you. But again, this would not be the responsibility of the adapter. 

Closing issue... but comments welcome.
