### ISSUE TITLE
unscope not correctly removing 'order' when limit is used causing MSSQL Error

### ISSUE THREAD

**Issue by dsadaka** [rails-sqlserver/activerecord-sqlserver-adapter#391]
As we know, In sqlserver-adapter 4.2, when limit() is specified, the new OFFSET and FETCH modifiers to the ORDER BY clause are used.  

However, in this case, instead of the unscope method *removing* the ORDER BY clause, it appears to change the ORDER BY <whatever> clause to ORDER BY table.id.  My guess is it's doing this so it can retain the OFFSET and FETCH clauses for performance?

## Demo 1:  No limit() clause, unscope works as it should

`@prod = Spree::Product.select(:updated_at).joins(:variants).order('spree_products.updated_at desc').group('spree_products.updated_at')`

@prod.to_sql ->
`SELECT [spree_products].[updated_at] FROM [spree_products] INNER JOIN [spree_variants] ON [spree_variants].[product_id] = [spree_products].[id] AND [spree_variants].[is_master] = 0 AND [spree_variants].[deleted_at] IS NULL WHERE [spree_products].[deleted_at] IS NULL GROUP BY spree_products.updated_at  ORDER BY spree_products.updated_at desc`

@prod.unscope(:order).to_sql ->
`SELECT [spree_products].[updated_at] FROM [spree_products] INNER JOIN [spree_variants] ON [spree_variants].[product_id] = [spree_products].[id] AND [spree_variants].[is_master] = 0 AND [spree_variants].[deleted_at] IS NULL WHERE [spree_products].[deleted_at] IS NULL GROUP BY spree_products.updated_at`

## Demo 2: Using limit clause.

`@prod = Spree::Product.select(:updated_at).joins(:variants).order('spree_products.updated_at desc').group('spree_products.updated_at').limit(1)`

@prod.to_sql ->
`SELECT  [spree_products].[updated_at] FROM [spree_products] INNER JOIN [spree_variants] ON [spree_variants].[product_id] = [spree_products].[id] AND [spree_variants].[is_master] = 0 AND [spree_variants].[deleted_at] IS NULL WHERE [spree_products].[deleted_at] IS NULL GROUP BY spree_products.updated_at  ORDER BY spree_products.updated_at desc OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY`

@prod.unscope(:order).to_sql ->
`SELECT  [spree_products].[updated_at] FROM [spree_products] INNER JOIN [spree_variants] ON [spree_variants].[product_id] = [spree_products].[id] AND [spree_variants].[is_master] = 0 AND [spree_variants].[deleted_at] IS NULL WHERE [spree_products].[deleted_at] IS NULL GROUP BY spree_products.updated_at  ORDER BY [spree_products].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY`

MS-SQL refuses to execute this query and instead spits back:

`Column "spree_products.id" is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause.`

**Comment by metaskills** [comment]
> However, in this case, instead of the unscope method removing the ORDER BY clause, it appears to change the ORDER BY clause to ORDER BY table.id.

The proper statement would be that `unscope` would remove any previous scopes of the relation BUT if that relation does end up having either a limit or offset the adapter needs an order for that statement and thus will insert one using first, the primary key of the table or the first ordinal column. You can see this by looking into our visitor. https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/arel/visitors/sqlserver.rb#L106

**Comment by metaskills** [comment]
OK, after reading the examples, I am still not able to help because I have no idea what the relation object of `@prod` is. I can tell you are doing some type of join or association maybe and even tacking on some further scopes to that association. But I am still lacking what the exact problem is... FYI, you will need an order if you want to limit/offset in SQL Server. This is different that other DBs.

**Comment by dsadaka** [comment]
Jeff, I define the @prod instance variable above in the example.  The basic problem is that if the unscope(:order) method is applied to any query with a LIMIT clause, it is not removing it.  The execute_simple_calculation at

activerecord-4.2.0/lib/active_record/relation/calculations.rb:239

the unscope method is used (this is called by--among others--the *maximum* method).  

If the coder wishes to remove the ORDER clause from a query than unscope must remove the OFFSET and FETCH clauses as well if they exist.  Correct?

To test on your end, make any query with the LIMIT clause and then try to unscope(:order).  You will get the error in question.

@p = Product.limit(10)
@p.maximum(:updated_at)

Boom!

Thanks,
Dan

**Comment by metaskills** [comment]
> The basic problem is that if the unscope(:order) method is applied to any query with a LIMIT clause, it is not removing the ORDER clause

Dan, that's not true. Read what I said above. It is removed. Are just adds it back cause we need it for deterministic fetch/offset. Again, this is different that other DBs.

> relation/calculations.rb:239

Oh I am super familiar with [this line of code](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/relation/calculations.rb#L239). Let me give you a few back story links. You can learn everything we have talked about in this https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/376 issue of ours when I was working on 4.2. Quasi related is this one https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/374 but focus on the first. Here is a FYI on the commit (https://github.com/rails/rails/issues/14621) that added those lines in Rails cause I thought I was going to be clever and see if I can fix this. Let me know after you have read these.

**Comment by metaskills** [comment]
@dsadaka You OK on this?

**Comment by dsadaka** [comment]
Not exactly Ken. Thanks for asking. I'm just avoiding it I'm overriding the
methods in Spree that call the maximum function and so far I'm able to
avoid it. I wish I had time to drill down further and help you with this
but I got a deadline--for a change.

If the problem still exists at the end of the month when we go live I'll
jump back in here.

Thanks, dan

**Comment by zaj** [comment]
I also have to build a rails/spree app on sqlserver and, so, am experiencing the same issues as @dsadaka.

Is there a solution to the issue he's uncovered? Seems like he's left with hacking into spree which I'd really like to avoid at the moment - other fish to fry and seems fragile in the event of changes to spree.

Is it a "will not fix" situation or might there be some further resolution? TIA

**Comment by metaskills** [comment]
> Is it a "will not fix" situation

The core issue addressed is not an issue since the SQL Server adapter needs to do things that other adapters do not. Specifically, since we switched to using FETCH and OFFSET for windowing support, we have to use an ORDER BY. If we undid this behavior, it would break many other things. 

The solution IMO is to push back on Spree to update their ruby to be a little bit less clever and more cross DB friendly. Unless someone points out a Rails core tests that we are failing or can feasibly pass?

**Comment by zaj** [comment]
Thx @metaskills for the quick response. Unfortunately, for me, I wouldnt expect the spree team to make the suggested changes quickly enough for us to move our project forward. I might have more control on our end to push for use of a diff DB than SQL Server.

**Comment by dsadaka** [comment]
Ken,

I respectfully disagree with you here.  The visitor for the sql adapter
simply needs to eliminate the duplicate columns in the order clause.  The
issue occurs when the column name appears qualified and unqualified:

e.g.  product.price and price.

I have never written an AREL visitor but I have written compilers.  Perhaps
another pass through to eliminate dups is what is needed.

Thanks,
Dan








*Dan Sadaka, PresidentPristineEmail.com a service ofWebsite One, Inc.(305)
999-0151, (877) 706-7481*

*“The price of success is hard work, dedication to the job at hand, and
the determination that whether we win or lose, we have applied the best
of ourselves to the task at hand.” - Vince Lombardi*

**Comment by metaskills** [comment]
That’s cool. I would be happy to consider any patch.

 - Ken

On April 20, 2015 at 3:09:56 PM, Dan Sadaka (notifications@github.com) wrote:

Ken,

I respectfully disagree with you here. The visitor for the sql adapter
simply needs to eliminate the duplicate columns in the order clause. The
issue occurs when the column name appears qualified and unqualified:

e.g. product.price and price.

I have never written an AREL visitor but I have written compilers. Perhaps
another pass through to eliminate dups is what is needed.

Thanks,
Dan








*Dan Sadaka, PresidentPristineEmail.com a service ofWebsite One, Inc.(305)
999-0151, (877) 706-7481*

*“The price of success is hard work, dedication to the job at hand, and
the determination that whether we win or lose, we have applied the best
of ourselves to the task at hand.” - Vince Lombardi*

**Comment by MisinformedDNA** [comment]
Maybe an example would help (I know I'm confused). Also, I'm still on 4.2, but hopefully the same logic can apply.

When I run the default page for Spree with Postgres, this is the generated SQL

```sql
SELECT  MAX("spree_products"."updated_at") AS max_id 
FROM "spree_products" 
INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" 
  AND "spree_variants"."is_master" = 't' 
  AND "spree_variants"."deleted_at" IS NULL 
INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" 
  AND "spree_prices"."deleted_at" IS NULL 
WHERE "spree_products"."deleted_at" IS NULL 
  AND ("spree_products".deleted_at IS NULL or "spree_products".deleted_at >= '2015-04-24 19:34:42.932617') 
  AND ("spree_products".available_on <= '2015-04-24 19:34:42.933452') 
  AND (spree_prices.amount IS NOT NULL) 
  AND "spree_prices"."currency" = 'USD' LIMIT 12 OFFSET 0
```

The result is a single record and is a datetime called max_id.

First off, this code makes no sense to me. What is the `LIMIT` even doing? We are getting a max, so there will only be one result, right? I changed the `LIMIT` to 1 and 1000000, but the result is always the same.

Now let's look at the generated SQL running against the activerecord-sqlserver-adapter:

```sql
SELECT t.* FROM (
	SELECT ROW_NUMBER() OVER(ORDER BY [spree_products].[id]) AS _row_num, 
		MAX([spree_products].[updated_at]) AS max_id 
	FROM [spree_products] 
	INNER JOIN [spree_variants] ON [spree_variants].[product_id] = [spree_products].[id] 
		AND [spree_variants].[is_master] = 1 
		AND [spree_variants].[deleted_at] IS NULL 
	INNER JOIN [spree_prices] ON [spree_prices].[variant_id] = [spree_variants].[id] 
		AND [spree_prices].[deleted_at] IS NULL 
	WHERE [spree_products].[deleted_at] IS NULL 
		AND ([spree_products].deleted_at IS NULL or [spree_products].deleted_at >= '2015-04-24 18:29:59.793') 
		AND ([spree_products].available_on <= '2015-04-24 18:29:59.795') 
		AND (spree_prices.amount IS NOT NULL) 
		AND [spree_prices].[currency] = N'USD'
) AS t 
WHERE t._row_num BETWEEN 1 AND 12
```

This fails with "Column 'spree_products.id' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause."

Again, if we are doing a MAX, then we should only get one row. With the MAX there, I don't see how OVER(ORDER BY) could ever be correct. So it would seem to me that Spree is calling something that doesn't quite make sense.

But where is `OVER(ORDER BY [spree_products].[id])` coming from? There is no equivalent in the generated Postgres. Is it arbitrarily chosen so that ROW_NUMBER can be used to do ordering? 

If so, maybe the OVER(ORDER BY) should surround the inner query?

```sql
SELECT t.* FROM (
	SELECT ROW_NUMBER() OVER(ORDER BY max_id) AS _row_num
	FROM (
		SELECT MAX([spree_products].[updated_at]) AS max_id 
		FROM [spree_products] 
		INNER JOIN [spree_variants] ON [spree_variants].[product_id] = [spree_products].[id] 
			AND [spree_variants].[is_master] = 1 
			AND [spree_variants].[deleted_at] IS NULL 
		INNER JOIN [spree_prices] ON [spree_prices].[variant_id] = [spree_variants].[id] 
			AND [spree_prices].[deleted_at] IS NULL 
		WHERE [spree_products].[deleted_at] IS NULL 
			AND ([spree_products].deleted_at IS NULL or [spree_products].deleted_at >= '2015-04-24 18:29:59.793') 
			AND ([spree_products].available_on <= '2015-04-24 18:29:59.795') 
			AND (spree_prices.amount IS NOT NULL) 
			AND [spree_prices].[currency] = N'USD'
	) s
) AS t 
WHERE t._row_num BETWEEN 1 AND 12
```

I'm pretty new to Ruby and my database query mapping is not existent at this point, so forgive me if I'm not making any sense? But if Postgres, SqlLite and MySql can interpret it, it seems like there should be a way to get SQL Server to interpret it as well?

**Comment by MisinformedDNA** [comment]
UPDATE: I realized that I was using `activerecord-jdbcmssql-adapter` when I generated the above SQL (I'm experimenting with JRuby).  Looks like they are having similar issue. I will try to improve the Spree code.

**Comment by metaskills** [comment]
Cool, closing this issue is OK then?

**Comment by MisinformedDNA** [comment]
I wasn't the original author, so my mistake doesn't solve their problem.

**Comment by dsadaka** [comment]
This issue still exists.

On Thursday, May 28, 2015, Dan Friedman <notifications@github.com> wrote:

> I wasn't the original author, so my mistake doesn't solve their problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/391#issuecomment-106673473>
> .
>


-- 





*Dan Sadaka, PresidentPristineEmail.com a service ofWebsite One, Inc.(305)
999-0151, (877) 706-7481*

*“The price of success is hard work, dedication to the job at hand, and
the determination that whether we win or lose, we have applied the best
of ourselves to the task at hand.” - Vince Lombardi*

**Comment by metaskills** [comment]
But is it an issue? The adapter needs to add an order when using limit/offset or both. This is just what "we" have to do.

**Comment by dsadaka** [comment]
It's duplicating the order since one is aliased, it doesn't catch it but
MS-SQL does.  IT doesn't like duplicate columns in ORDER clause.  So... to
your answer is yes.

Dan






*Dan Sadaka, PresidentPristineEmail.com a service ofWebsite One, Inc.(305)
999-0151, (877) 706-7481*

*“The price of success is hard work, dedication to the job at hand, and
the determination that whether we win or lose, we have applied the best
of ourselves to the task at hand.” - Vince Lombardi*
