### ISSUE TITLE
Invalid usage of the option NEXT in the FETCH statement

### ISSUE THREAD

**Issue by maxstudener** [rails-sqlserver/activerecord-sqlserver-adapter#392]
rails (4.2.0)
      actionmailer (= 4.2.0)
      actionpack (= 4.2.0)
      actionview (= 4.2.0)
      activejob (= 4.2.0)
      activemodel (= 4.2.0)
      activerecord (= 4.2.0)
      activesupport (= 4.2.0)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.0)
      sprockets-rails

activerecord-sqlserver-adapter (4.2.2)
      activerecord (~> 4.2.0)

```User.where(USERSID: params[:id]).first```

TinyTds::Error: Invalid usage of the option NEXT in the FETCH statement.: EXEC sp_executesql N'SELECT [USERS].* FROM [USERS] WHERE [USERS].[USERSID] = @0 ORDER BY [USERS].[USERSID] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY', N'@0 bigint', @0 = 35797

**Comment by metaskills** [comment]
I see nothing wrong with that SQL. Did you perhaps [miss the fact](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter#activerecord-sql-server-adapter-for-sql-server-2012-and-higher) that this version is for 2012 and upward?

**Comment by metaskills** [comment]
More info here: http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/
