### ISSUE TITLE
ActiveRecord::StatementInvalid (TinyTds::Error: Cannot insert the value NULL into column...

### ISSUE THREAD

**Issue by raihan29s** [rails-sqlserver/activerecord-sqlserver-adapter#393]
I m new to ruby as well as in redmine. When i am going to create a new user in redmine it is showing 
![capture](https://cloud.githubusercontent.com/assets/10660626/6276517/1e83cbd8-b84d-11e4-9386-ce1c4358a94c.PNG)

I checked the development.log file. it is showing following error:

ActiveRecord::StatementInvalid (TinyTds::Error: Cannot insert the value NULL into column 'status', table 'Table-1'; column does not allow nulls. INSERT fails.: EXEC sp_executesql N'INSERT INTO [users] ([admin], [auth_source_id], [created_on], [firstname], [hashed_password], [identity_url], [language], [last_login_on], [lastname], [login], [mail], [mail_notification], [salt], [status], [type], [updated_on]) VALUES (@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15); SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident', N'@0 bit, @1 int, @2 datetime, @3 nvarchar(30), @4 nvarchar(40), @5 nvarchar(255), @6 nvarchar(5), @7 datetime, @8 nvarchar(255), @9 nvarchar(255), @10 nvarchar(60), @11 nvarchar(255), @12 nvarchar(64), @13 int, @14 nvarchar(255), @15 datetime', @0 = 1, @1 = NULL, @2 = '2015-02-19T15:40:19.239', @3 = N'Brick', @4 = N'674e6d855f354edae2e92c021718798ba2912edf', @5 = NULL, @6 = N'en', @7 = NULL, @8 = N'Fill', @9 = N'olx', @10 = N'xxxx@gmail.com', @11 = N'only_my_events', @12 = N'9375cf7435ac289920a9336fe8e5f34c', @13 = NULL, @14 = N'User', @15 = '2015-02-19T15:40:19.239'):
  app/controllers/users_controller.rb:93:in `create'

Please help if anyone went through similar problem!

**Comment by metaskills** [comment]
I understand you are new and need help, but this is not an adapter issue. You should look for help on this topic within whatever process the Redmine community has. Note, I have no idea what that is as I have never used Redmine. But I would suspect they have something in place to help people out.

That said, your error states that for some reason you are trying to create a user with a NULL status. If Redmine is open source, then perhaps you can trace their their controller action and model to find out why. Cheers!
