### ISSUE TITLE
Getting error while saving records into table which has '.' in name

### ISSUE THREAD

**Issue by petarcurkovic** [rails-sqlserver/activerecord-sqlserver-adapter#394]
I have table with name 'dbo.some.Name'. When I'm trying to save object to table, I've got an error:

TinyTds::Error: Incorrect syntax near ')'.

```SQL
EXEC sp_executesql N'INSERT INTO [some.Name] ([Path], ...) OUTPUT INSERTED.[ID] 
VALUES (@0, @1, @2, @3, @4, @5, @6, @7, @8)', 
N'@0 float, @1 float, @2 float, @3 float, @4 varchar(), @5 int, @6 int, @7 varchar(), @8 int', 
@0 = 41.872668000000004, @1 = 17.291462, @2 = 9.137186, @3 = 9.137186, @4 = N'somestring', @5 = N'125708', @6 = N'39318', @7 = N'GUID', @8 = N'0'
```
Notice that @4 varchar() doesn't have value in parenthesis.
In table which doesn't contains '.' in name, it works.

**Comment by metaskills** [comment]
If you have a table/object name with a period in it, then you are going to have to tell the adapter what you mean. The identifier formatted as `database.schema.object` is just that. So in your case you want to set the table name to `[dbo].[some.Name]`

I can confirm that I tested our new Name identifier object to do the right thing here too.

```ruby
table_name = '[dbo].[some.Name]'
Utils = ActiveRecord::ConnectionAdapters::SQLServer::Utils
Utils.extract_identifiers(table_name).object         # => "some.Name"
Utils.extract_identifiers(table_name).object_quoted  # => "[some.Name]"
```

So just do this in your model `self.table_name = '[dbo].[some.Name]'`

**Comment by petarcurkovic** [comment]
Yes, I have already defined in my model table name '[dbo].[some.Name]'. I think the problem is when I have table name with period in it and data type varchar. In SQL query are missing parameters for varchar. When I copy this query and manually add parameters in varchar(255) then query is successfully executed.

**Comment by metaskills** [comment]
Interesting, then this is likely an issue that we maybe be able to test and fix. I will put it on the list for the next release which I am working on now.

**Comment by petarcurkovic** [comment]
OK, thanks!

Best regards,
Petar

**Comment by metaskills** [comment]
OK, so this was a bug in the schema definitions not returning the proper limit for char/varchar.

**Comment by metaskills** [comment]
This is in master now and will be published in a day or too since master is for Rails 4.2.1.rc1 right now and that wont be released for a few days.
