### ISSUE TITLE
"Invalid column name" error when using with composite_primary_keys gem

### ISSUE THREAD

**Issue by krpec** [rails-sqlserver/activerecord-sqlserver-adapter#396]
Hi, I'm using activerecord-sqlserver-adapter (4.1.0 due to SQL Server 2008 R2). This error occured to me  when trying to insert a new record to a table which has composite PK set over 4 columns. After heavy googling nothing helped, so I dig to the problem and found quick fix:

When using composite_primary_keys, the PK is Array containing all columns that are in the composite PK. Problem was in `sql_for_insert` method from `datababase_statements.rb`, because the method is not prepared to handle an array as a PK, so the `OUTPUT inserted.PKPart1,PKPart2,PKPart3,PKPart4` isn't generated properly as there should be the `inserted.` before each column of composite PK. Quick fix (code based on 4.1.0 method) is listed here:

```ruby
def sql_for_insert(sql, pk, id_value, sequence_name, binds)
	sql =
		if pk
			if pk.is_a? Array
				output_str = " OUTPUT"

				pk.each_with_index do |item, index|
					if index == 0
						output_str += " inserted.#{item}"
					else
						output_str += ", inserted.#{item}"
					end
				end

				sql.insert(sql.index(/ (DEFAULT )?VALUES/), output_str)
			else
				sql.insert(sql.index(/ (DEFAULT )?VALUES/), " OUTPUT inserted.#{pk}")
			end
		else
			"#{sql}; SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident"
		end
	super
end
```

There's maybe a better solution to this, but this quick fix works for me, so I wanted to share it with all of you. Also, I'm pretty sure the issue will be the same when using the latest version. Anyway, thanks for the gem, it really makes my life much easier! :)

**Comment by metaskills** [comment]
Thanks! This issue is much like #352. The solution is for the `composite_primary_keys` gem to monkey patch 4.1 differently than 4.2. So this is their problem. We have solved it in 4.2 by allowing a configuration and the `composite_primary_keys` knows where to override our work.
