### ISSUE TITLE
TinyTds :: Error: Error converting data type nvarchar to datetime2 

### ISSUE THREAD

**Issue by sist01** [rails-sqlserver/activerecord-sqlserver-adapter#401]
Problem with upgrade bitnami redmine-3.0.1-0 from bitnami-redmine 2.6.3 on windows server 2008 r2 and sqlserver 2012

In environment Windows 2008 and sqlsever 2012 redmine 2.6.3 works perfectly.... but the upgrade to version 3.0.1-0 redmine I get the following error:
  
Started POST "/ redmine / projects / pwf / issues" for 127.0.0.1 at 3/30/2015 13:22:12 +0200
Processing by IssuesController # created as HTML
  Parameters: {"utf8" => "✓" "authenticity_token"=>"p4/9RwHLDpa7GcHaiuxXY+PRNOsfmiqX6wIEMP/rm0cRO7BYO/zVHQN7/FC+ROWw/l5eleqShh/rz6UdGpKN3g==", "Issue" => {"is_private" => "0", "tracker_id" => "15", "subject" => "ssss", "description" => "ssss", "status_id" => "1" , "priority_id" => "4", "assigned_to_id" => "84", "fixed_version_id" => "", "parent_issue_id" => "", "start_date" => "", "due_date" => "" , "estimated_hours" => "", "done_ratio" => "0", "custom_field_values" => {"1" => "ALL", "71" => "To be determined"}}, "was_default_status" => "1", "commit" => "Create", "project_id" => "pwf"}
  Current user: sist01 (id = 84)

TinyTds :: Error: Error converting data type nvarchar to datetime2 .: EXEC sp_executesql N'INSERT INTO [issues] ([project_id], [author_id], [tracker_id], [status_id] [subject] [description], [priority_id ], [assigned_to_id], [updated_on], [created_on]) OUTPUT INSERTED. [id] VALUES ( 0, 1, 2, 3 4 5 6 7 8 9) ', N' 0 int, int 1, 2 int, int 3, 4 nvarchar (255), 5 nvarchar (max), 6 int, int 7, 8 datetime2 , 9 datetime2 ', 0 = 67 = 84 1, 2 = 15, 3 = 1 4 = N'ssss', 5 = N'ssss', 6 = 4 7 = 84, 8 = N'2015-03-30 13:22:12 +0200 ', 9 = N'2015-03-30 13:22:12 +0200'
Completed 500 Internal Server Error in 118ms

ActiveRecord :: StatementInvalid (TinyTds :: Error: Error converting data type nvarchar to datetime2 .: EXEC sp_executesql N'INSERT INTO [issues] ([project_id], [author_id], [tracker_id], [status_id], [subject], [ description], [priority_id], [assigned_to_id], [updated_on], [created_on]) OUTPUT INSERTED. [id] VALUES ( 0, 1, 2, 3 4 5 6 7 , 8 9) ', N' 0 int, int 1, 2 int, int 3, 4 nvarchar (255), 5 nvarchar (max), 6 int, int 7, 8 datetime2, 9 datetime2 ', 0 = 67, 1 = 84, 2 = 15 , 3 = 1 4 = N'ssss', 5 = N'ssss', 6 = 4 7 = 84, 8 = N'2015-03-30 13:22:12 +0200 ', 9 = N'2015-03-30 13:22:12 +0200'):
  app / models / issue.rb: 174: in `create_or_update '
  app / controllers / issues_controller.rb: 141: in `created '

Can anyone help?
thanks

**Comment by metaskills** [comment]
Seems like an adapter issue, not TinyTDS. What version of the SQL Server adaptr are you using?

**Comment by sist01** [comment]
HI Ken, thank you for your answer.
The error is very strange because with version 2.6.3 of redmine and sqlserver 2014 express works very well, and works very well with sql server 2008 sp2 (no express).
The error occurs when I decide to upgrade to redmine 3.0.1. Whether you use sql server 2012 express whether use sqlserver 2008 sp2.
Available for any test you need.

Da: Ken Collins [mailto:notifications@github.com]
Inviato: domenica 26 aprile 2015 17:50
A: rails-sqlserver/activerecord-sqlserver-adapter
Cc: PETA Antonio Silvio
Oggetto: Re: [activerecord-sqlserver-adapter] TinyTds :: Error: Error converting data type nvarchar to datetime2 (#401)


Seems like an adapter issue, not TinyTDS. What version of the SQL Server adaptr are you using?

**Comment by metaskills** [comment]
Please consider that I have no idea what redmine is and how it versions it dependences. To answer my questions, I need to know what version of "activerecord-sqlserver-adapter" are being used in your Gemfile.lock. This is the critical info. Anything else is unrelated.

**Comment by sist01** [comment]
ok Ken, I apologize ..

activerecord-sqlserver-adapter (3.2.13)
3.2.13




Da: Ken Collins [mailto:notifications@github.com]
Inviato: lunedì 27 aprile 2015 12:16
A: rails-sqlserver/activerecord-sqlserver-adapter
Cc: PETA Antonio Silvio
Oggetto: Re: [activerecord-sqlserver-adapter] TinyTds :: Error: Error converting data type nvarchar to datetime2 (#401)


Please consider that I have no idea what redmine is and how it versions it dependences. To answer my questions, I need to know what version of "activerecord-sqlserver-adapter" are being used in your Gemfile.lock. This is the critical info. Anything else is unrelated.

**Comment by metaskills** [comment]
> activerecord-sqlserver-adapter (3.2.13)

OK, so that is a real old version. That means the redmine application is also Rails 3.2. So... back to your error... what are the `8 datetime2 , 9 datetime2` columns?

**Comment by sist01** [comment]
Hi Ken
Below is the error that is reported in the application log "redmine"
I highlighted in red what you ask me.
Thank you very much for your time
Antonio.
Started POST "/ redmine / projects / pwf / issues" for 127.0.0.1 at 3/30/2015 13:22:12 +0200
Processing by IssuesController # created as HTML
  Parameters: {"utf8" => "✓" "authenticity_token"=>"xxxxxxxxxx", "Issue" => {"is private" => "0", "tracker_id" => "15", "subject" => "ssss", "description" => "ssss", "status_id" => "1" , "priority_id" => "4", "assigned_to_id" => "84", "fixed_version_id" => "", "parent_issue_id" => "", "start_date" => "", "due_date" => "" , "estimated_hours" => "", "done_ratio" => "0", "custom_field_values" => {"1" => "ALL", "71" => "To be determined"}}, "was_default_status" => "1", "commit" => "Create", "project_id" => "pwf"}
  Current user: sist01 (id = 84)
TinyTds :: Error: Error converting data type nvarchar to datetime2 .: EXEC sp_executesql N'INSERT INTO [issues] ([project_id], [author_id], [tracker_id], [status_id] [subject] [description], [priority_id ], [assigned_to_id], [updated_on], [created_on]) OUTPUT INSERTED. [id] VALUES ( 0, 1, 2, 3 4 5 6 7 8 9) ', N' 0 int, int 1, 2 int, int 3, 4 nvarchar (255), 5 nvarchar (max), 6 int, int 7, 8 datetime2 , 9 datetime2 ', 0 = 67 = 84 1, 2 = 15, 3 = 1 4 = N'ssss', 5 = N'ssss', 6 = 4 7 = 84, 8 = N'2015-03-30 13:22:12 +0200 ', 9 = N'2015-03-30 13:22:12 +0200'
Completed 500 Internal Server Error in 118ms
ActiveRecord :: StatementInvalid (TinyTds :: Error: Error converting data type nvarchar to datetime2 .: EXEC sp_executesql N'INSERT INTO [issues] ([project_id], [author_id], [tracker_id], [status_id], [subject], [ description], [priority_id], [assigned_to_id], [updated_on], [created_on]) OUTPUT INSERTED. [id] VALUES ( 0,1, 2, 3 4 5 6 7 , 8 9) ', N' 0 int, int 1, 2 int, int 3, 4 nvarchar (255), 5 nvarchar (max), 6 int, int 7, 8 datetime2, 9 datetime2 ', 0 = 67, 1 = 84, 2 = 15, 3 = 1 4 = N'ssss', 5 = N'ssss', 6 = 4 7 = 84, 8 = N'2015-03-30 13:22:12 +0200 ', 9 = N'2015-03-30 13:22:12 +0200'):
  app / models / issue.rb: 174: in `create_or_update '
  app / controllers / issues_controller.rb: 141: in `created '


Da: Ken Collins [mailto:notifications@github.com]
Inviato: martedì 28 aprile 2015 14:48
A: rails-sqlserver/activerecord-sqlserver-adapter
Cc: PETA Antonio Silvio
Oggetto: Re: [activerecord-sqlserver-adapter] TinyTds :: Error: Error converting data type nvarchar to datetime2 (#401)


activerecord-sqlserver-adapter (3.2.13)

OK, so that is a real old version. That means the redmine application is also Rails 3.2. So... back to your error... what are the 8 datetime2 , 9 datetime2 columns?

**Comment by metaskills** [comment]
Please help me here... I am having to dig and count your SQL. I would be better if you could tell me. By that post (again), then the column that generate the errors are ` [priority_id]` and `[assigned_to_id]`? Which columns are generating the wrong data types?

**Comment by sist01** [comment]
Ken I reproduced the error on another table easier with fewer fields.

Processing by RepositoriesController#create as HTML
  Parameters: {"utf8"=>"?", "authenticity_token"=>"zGQPbvuKXTWNtDvYWmxrki218DVHQ4ctqjd/QgOuAnrq6KK4EAeAIfCuuj4BBz5Bm/QauMKEHPnynMjhXlf8oQ==", "repository_scm"=>"Subversion", "repository"=>{"is_default"=>"1", "identifier"=>"icsc2", "url"=>"file:///c:/svnrepository/icsc", "login"=>"sist01", "password"=>"[FILTERED]"}, "commit"=>"Crea", "project_id"=>"pwf"}
  Current user: sist01 (id=84)
TinyTds::Error: Error converting data type nvarchar to datetime2.: EXEC sp_executesql N'INSERT INTO [repositories] ([type], [is_default], [identifier], [url], [login], [password], [project_id], [created_on]) OUTPUT INSERTED.[id] VALUES (@0, @1, @2, @3, @4, @5, @6, @7)', N'@0 nvarchar(255), @1 smallint, @2 nvarchar(255), @3 nvarchar(255), @4 nvarchar(60), @5 nvarchar(255), @6 int, @7 datetime2', @0 = N'Repository::Subversion', @1 = 1, @2 = N'icsc2', @3 = N'file:///c:/svnrepository/icsc', @4 = N'sist01', @5 = N'sist01', @6 = 67, @7 = N'2015-04-28 17:16:54 +0200'
Completed 500 Internal Server Error in 10ms

ActiveRecord::StatementInvalid (TinyTds::Error: Error converting data type nvarchar to datetime2.: EXEC sp_executesql N'INSERT INTO [repositories] ([type], [is_default], [identifier], [url], [login], [password], [project_id], [created_on]) OUTPUT INSERTED.[id] VALUES (@0, @1, @2, @3, @4, @5, @6, @7)', N'@0 nvarchar(255), @1 smallint, @2 nvarchar(255), @3 nvarchar(255), @4 nvarchar(60), @5 nvarchar(255), @6 int, @7 datetime2', @0 = N'Repository::Subversion', @1 = 1, @2 = N'icsc2', @3 = N'file:///c:/svnrepository/icsc', @4 = N'sist01', @5 = N'sist01', @6 = 67, @7 = N'2015-04-28 17:16:54 +0200'):
  app/controllers/repositories_controller.rb:55:in `create'


I can confirm that the error is in the field

Field wrong ----    [created_on]

if you can be of help I turned executesql manually in the database.

Well the exec is ok if cancell '+0200' "otherwise it fails.
Wrong:
EXEC sp_executesql N'INSERT INTO [repositories] ([type], [is_default], [identifier], [url], [login], [password], [project_id], [created_on]) OUTPUT INSERTED.[id] VALUES (@0, @1, @2, @3, @4, @5, @6, @7)', N'@0 nvarchar(255), @1 smallint, @2 nvarchar(255), @3 nvarchar(255), @4 nvarchar(60), @5 nvarchar(255), @6 int, @7 datetime2', @0 = N'Repository::Subversion', @1 = 1, @2 = N'icsc2', @3 = N'file:///c:/svnrepository/icsc', @4 = N'sist01', @5 = N'sist01', @6 = 67, @7 = N'2015-04-28 17:16:54 +0200'):

Right
EXEC sp_executesql N'INSERT INTO [repositories] ([type], [is_default], [identifier], [url], [login], [password], [project_id], [created_on]) OUTPUT INSERTED.[id] VALUES (@0, @1, @2, @3, @4, @5, @6, @7)', N'@0 nvarchar(255), @1 smallint, @2 nvarchar(255), @3 nvarchar(255), @4 nvarchar(60), @5 nvarchar(255), @6 int, @7 datetime2', @0 = N'Repository::Subversion', @1 = 1, @2 = N'icsc2', @3 = N'file:///c:/svnrepository/icsc', @4 = N'sist01', @5 = N'sist01', @6 = 67, @7 = N'2015-04-28 17:16:54’):

Da: Ken Collins [mailto:notifications@github.com]
Inviato: martedì 28 aprile 2015 15:35
A: rails-sqlserver/activerecord-sqlserver-adapter
Cc: PETA Antonio Silvio
Oggetto: Re: [activerecord-sqlserver-adapter] TinyTds :: Error: Error converting data type nvarchar to datetime2 (#401)


Please help me here... I am having to dig and count your SQL. I would be better if you could tell me. By that post (again), then the column that generate the errors are [priority_id] and [assigned_to_id]? Which columns are generating the wrong data types?

**Comment by metaskills** [comment]
Apologies for taking a while to come to the conclusion of this. Been multi-tasking a bit to much lately.

So TinyTDS does not support datetime2 because FreeTDS does not. See: https://github.com/rails-sqlserver/tiny_tds#data-types there. Any non-supported datatype is just read as a string, so the adapter does not know what to do with it. 

I believe we have a chance to do something about this in the 4.2 and upward versions of the adapter with the help of the [new type objects](http://metaskills.net/2015/01/06/activerecord-42s-type-casting/). But that means you have to (a) use Rails 4.2 which may not be an option for you and (b) assist us by doing some leg work and testing. I left some placeholders in the 4-2-stable work here:

* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/schema/datatypes/2012.sql#L52
* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/cases/column_test_sqlserver.rb#L281-L422

You can even see how I already shimmed the [time] support in already.

**Comment by sist01** [comment]
sorry Ken a little help,
how do I run the program that you suggested for test
I defined the database and created the table but as I run the program I load the following error:


E:\CustomRedmine>ruby TESTKEN.rb
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- cases/helper_sqlserver (LoadError)
        from C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'   from TESTKEN.rb:2:in `<main>'



Da: Ken Collins [mailto:notifications@github.com]
Inviato: giovedì 30 aprile 2015 03:11
A: rails-sqlserver/activerecord-sqlserver-adapter
Cc: PETA Antonio Silvio
Oggetto: Re: [activerecord-sqlserver-adapter] TinyTds :: Error: Error converting data type nvarchar to datetime2 (#401)


Apologies for taking a while to come to the conclusion of this. Been multi-tasking a bit to much lately.

So TinyTDS does not support datetime2 because FreeTDS does not. See: https://github.com/rails-sqlserver/tiny_tds#data-types there. Any non-supported datatype is just read as a string, so the adapter does not know what to do with it.

I believe we have a chance to do something about this in the 4.2 and upward versions of the adapter with the help of the new type objects<http://metaskills.net/2015/01/06/activerecord-42s-type-casting/>. But that means you have to (a) use Rails 4.2 which may not be an option for you and (b) assist us by doing some leg work and testing. I left some placeholders in the 4-2-stable work here:

  *   https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/schema/datatypes/2012.sql#L52
  *   https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/cases/column_test_sqlserver.rb#L281-L422

You can even see how I already shimmed the [time] support in already.

**Comment by metaskills** [comment]
> how do I run the program that you suggested for test

It is not a program, this is our test suite. Most, if not all, gems have a test directory that can be run using the `$ rake test` command. We have a doc that talks about specific test setup needs if you are interested.

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/RUNNING_UNIT_TESTS.md

**Comment by sist01** [comment]
Ok Ken, I ask you to forgive me for my stupidity, I had not realized
I look at the site you suggested and I try to understand better.
Sorry.

Da: Ken Collins [mailto:notifications@github.com]
Inviato: giovedì 30 aprile 2015 13:26
A: rails-sqlserver/activerecord-sqlserver-adapter
Cc: PETA Antonio Silvio
Oggetto: Re: [activerecord-sqlserver-adapter] TinyTds :: Error: Error converting data type nvarchar to datetime2 (#401)


how do I run the program that you suggested for test

It is not a program, this is our test suite. Most, if not all, gems have a test directory that can be run using the $ rake test command. We have a doc that talks about specific test setup needs if you are interested.

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/RUNNING_UNIT_TESTS.md

**Comment by metaskills** [comment]
You are good, no worries. I do not mind helping. Sometimes I sound curt only because I am doing things quickly.

**Comment by KDGundermann** [comment]
Reading your post I see you want to insert  N'2015-03-30 13:22:12 +0200 ' in a datetime2 field.

But a datetime2 field has no timezone offset, you should use a datetimeoffset field , see https://msdn.microsoft.com/en-us/library/ms186724(v=sql.110).aspx)

**Comment by metaskills** [comment]
I'll be getting to this issue after TinyTDS uses v0.95.x of FreeTDS which supports the datetime2 type. https://github.com/rails-sqlserver/tiny_tds/pull/233

**Comment by metaskills** [comment]
FYI, these types will not be supported mostly likely till FreeTDS v0.99. Please check track this issue on TinyTDS for updates too. https://github.com/rails-sqlserver/tiny_tds/issues/244

**Comment by metaskills** [comment]
I am going to close this issue since the latest master branch of the adapter, future v4.2.7, has this fixed under https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/433 issue. Please be aware that you have to use the latest version of TinyTDS. If you are on Windows, I have precompiled binary gems. Just use `0.9.5.beta.7` or higher. If you are compiling TinyTDS against your own version of FreeTDS, please make sure to use the latest version of FreeTDS v0.95 or higher. Remember too, you have to use TDSVER=7.3 too. That is not the default yet in the adapter.
