### ISSUE TITLE
4.1.x locks you to Rails 4.1.x

### ISSUE THREAD

**Issue by kwerle** [rails-sqlserver/activerecord-sqlserver-adapter#406]
Yes, my organization needs to update SQL Server.

Is it really not possible to use the 4.1.x series with Rails 4.2.x?  Or is that an artificial gem restriction...

**Comment by metaskills** [comment]
This is at the top of the [readme](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter#code-name-kantishna):

> We follow a rational versioning policy that tracks ActiveRecord. That means that our 4.2.x version of the adapter is only for the latest 4.2 version of Rails. We also have stable branches for each major/minor release of ActiveRecord.

So the latest 4.1.x adapter is for the latest 4.1.x rails/activerecord release. The reasons the 4.2.x version of the adapter is locked to 2012 and upward is mentioned here. http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/

**Comment by kwerle** [comment]
Yeah, read that.

I would like to upgrade to Rails 4.2.X.  Since my organization is still on SqlServer 2008, I'm restricted to adapter 4.1.X.  The 4.2 adapter sounds great - and I'm looking forward to using it.

In the meantime, however, I'd like to know if the 4.1 adapter would *work* with Rails 4.2, or if it is actually incompatible.  If it's not incompatible, then I'd like to request an easement of the gem version restriction.

**Comment by metaskills** [comment]
From an Adapter perspective, 4.1 to 4.2 is as different from Rails 3.2 to 4.2. ActiveRecord changed so much of the internals for what adapters like this have to do to conform. 

To be clear. There is no way 4.1 is going to work with 4.2.

**Comment by kwerle** [comment]
I appreciate the clarification.  Thanks!

**Comment by metaskills** [comment]
No problem. 

It is technically possible for someone to fork our current 4-2-stable branch and remove all the FETCH/OFFSET 2012 specific implementations and go back to the crazy limit offset we had till that point using ROW_NUMBER. It is much harder than it sounds. I would estimate if someone were really good with the adapter internals it would take 4-6 weeks of their time to accomplish it and pass all ActiveRecord tests.

That said, If someone did that, I would pull that work in and maintain a special branch here for others to use it. Cheers.

**Comment by kwerle** [comment]
Ain't gonna be me!  The organization is working on migrating to 2014.  This
really was a casual question of whether or not it was trivial to use the
older adapter with the newer Rails.

Thanks for all your work!
Kurt
​

**Comment by metaskills** [comment]
LOL, cheers again!

**Comment by neongrau** [comment]
Ouch, so ActiveRecord has changed from 4.1 to 4.2 so massively that so much work had to be put into the Adapter to work with it that you'd consider it easier to re-write the SQL changes from the current 4.2 branch back to older 2008 compatible SQL?

So a downgrade to Rails 4.1 seems necessary :(

**Comment by metaskills** [comment]
Ouch, so ActiveRecord has changed from 4.1 to 4.2 so massively that so much work had to be put into the Adapter to work with it that you'd consider it easier to re-write the SQL changes from the current 4.2 branch back to older 2008 compatible SQL?

Yes.

So a downgrade to Rails 4.1 seems necessary :(

There are two other options.

1) Upgrade the server from 2008 to 2012

2) Sponsor the OS work or make the adapter changes internally.

Not to put any FUD in the equation… but I was not responsible for the 4.1 work. I stepped back from the adapter work during that time. I have never run the 4.1 tests and there are a few open issues on GitHub for it. No show stoppers, but I am not a fan of the 4-1-stable branch in the adapter. 

Given all this info, you should be able to make a call on which is right for “you” and “your business"



 - Hope that helps!

   Ken

**Comment by neongrau** [comment]
Option 2) was on my mind but your estimate of 4-6 weeks made that idea sound unrealistic.

**Comment by neongrau** [comment]
Then again, by 4-6 weeks did you mean 4-6 man weeks of work or just the time to get it done? If so you Tell me how we can compensate/sponsor that development branch. If that would be cheaper than downgrading to Rails 4.1 and also helping others that still have to rely on older SQL Servers i'm up for it. You got my mail address. 

Ralf

**Comment by neongrau** [comment]
Hey!
Have you thought about a sum for sponsoring the development of a SQL Server 2005 compatible Adapter for Rails 4.2 ? Still very interested.

**Comment by metaskills** [comment]
Hey @neomindryan, no I have not. I can put time to the project, but I do not think I have the time now to put to the 4-1-stable branch.

**Comment by neomindryan** [comment]
@metaskills I think you meant @neongrau?

**Comment by rept** [comment]
Was posting a new question about this but then I found this (and many other) thread.  Too bad this locks you at 4.1 since the lifecycle support end date of SQL 2008 ends in 2019 and SQL2008R2 is being used by lots of companies who can't simply upgrade (at least not without a decent cost).

BTW Still very grateful for the gem! ;-)

**Comment by metaskills** [comment]
See here for an alternative. https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/426
