### ISSUE TITLE
Listing Table names on Azure SQL server

### ISSUE THREAD

**Issue by jwoertink** [rails-sqlserver/activerecord-sqlserver-adapter#407]
I'm not very familiar with SQL Server, so not sure if this is a normal thing, or TinyTDS thing, or this gem, but here goes...

I want to list all the names of the tables in my database that I'm connected to, but every example I've found on how to do this, I always get back an Integer instead of a list of table names..

```ruby
ActiveRecord::Base.connection.execute("SELECT db.name, t.TABLE_NAME FROM sys.databases db INNER JOIN INFORMATION_SCHEMA.TABLES t ON db.name = t.TABLE_CATALOG")
# (77.3ms)  SELECT db.name, t.TABLE_NAME FROM sys.databases db INNER JOIN INFORMATION_SCHEMA.TABLES t ON db.name = t.TABLE_CATALOG
# => 62 

ActiveRecord::Base.connection.execute("SELECT * FROM sys.Tables")
# (50.5ms)  SELECT * FROM sys.Tables
# => 61

ActiveRecord::Base.connection.execute("SELECT * FROM sys.indexes")
# (48.0ms)  SELECT * FROM sys.indexes
# => 183

ActiveRecord::Base.connection.execute("SELECT * FROM INFORMATION_SCHEMA.TABLES")
# (44.9ms)  SELECT * FROM INFORMATION_SCHEMA.TABLES
# => 62
```

Is there something this gem does when running these SQL commands that require anything in particular, or are these the correct results?

**Comment by theangryangel** [comment]
You need to call select or select_values instead. Execute will only return number of rows, iirc.

There is a convenience function called tables which will do this for you. See https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/active_record/connection_adapters/sqlserver/schema_statements.rb

**Comment by jwoertink** [comment]
Oh man! That's a lot nicer! Thanks :) I'll plug this into the wiki

**Comment by metaskills** [comment]
Thanks for the wiki addition, but this is a core feature of ActiveRecord. So the documentation is on them and likely on their API docs.

Where we do differ from core AR is the aritary and arguments for that method. See [here](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/active_record/connection_adapters/sqlserver/schema_statements.rb#L10-L12). We use that `table_type` argument with our `views` method too. HTH

```ruby
def views
  tables('VIEW')
end
```

**Comment by jwoertink** [comment]
Ah, well, learn something new everyday! Thanks for the help

**Comment by metaskills** [comment]
:)
