### ISSUE TITLE
table_exists? is not working for non default schema

### ISSUE THREAD

**Issue by vnazarenko** [rails-sqlserver/activerecord-sqlserver-adapter#408]
Hi, we have several schemas in our db. And when in migration i try to do something like that:
```
    drop_table "users" if table_exists? "auth.users"
```
table_exists returns true, but users table exists only in dbo schema.
So it try to delete it and i get an exception.

**Comment by metaskills** [comment]
Thanks, please use `execute` and the needed SQL to avoid this issue now. Not sure we can handle all these schema scenarios.
