### ISSUE TITLE
"stack level too deep" when try to create on SQL Server 2005

### ISSUE THREAD

**Issue by cbezares** [rails-sqlserver/activerecord-sqlserver-adapter#409]
My configuration:
- activerecord-sqlserver-adapter 4.1.0
- Rails 4.1.0
- Ruby 1.9.3
- Windows 7
- SQL Server 2005
- Tiny TDS 0.6.2 x86-mingw32

And I'm getting the following error when I try to create a new element:

```
    ←[1m←[35mSQL (1.0ms)←[0m  BEGIN TRANSACTION
    ←[1m←[36mSQL (9.0ms)←[0m  ←[1mEXEC sp_executesql N'INSERT INTO [my_model] ([created_at], [title], [updated_at]) OUTPUT inserted.id VALUES (@0, @1, @2)', N'@0 datetime, @1 nvarchar(max), @2 datetime, @0 = '2015-07-27T13:19:53.336', @1 = N'My Title', @2 = '2015-07-27T13:19:53.336'←[0m  [["created_at", Mon, 27 Jul 2015 10:19:53 CLT -03:00], ["title", "ASDASD"], ["updated_at", Mon, 27 Jul 2015 10:19:53 CLT -03:00]]
    ←[1m←[35mSQL (1.0ms)←[0m  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
Completed 500 Internal Server Error in 146ms

SystemStackError - stack level too deep:
    actionpack (4.1.0) lib/action_dispatch/middleware/reloader.rb:79:in `'
```

This is happenning only when I use datetime fields.
I tested inserting a row into the table using only Tiny TDS from Rails console and there is no problem.

What's wrong?
Thanks

**Comment by metaskills** [comment]
Interesting... it is hard to imagine that this would happen in the adapter stack. Can you post a full stack trace? From what you posted this is happening in Rails or a middleware of some sort? IE, does this error happen only when using request/response from a form or can you show a full stack trace when in a console with simple ActiveRecord code? TIA!

**Comment by cbezares** [comment]
Hi @metaskills, thanks for your answer.

If I try to create an element from rails console i get the same error but pointing to another file `C:/Ruby193/lib/ruby/1.9.1/irb/workspace.rb:80`. This is the full stack trace that I receive from Rails:

    Loading development environment (Rails 4.1.0)
    irb(main):001:0> m = MyModel.new(title: 'My Title')
        ←[1m←[36mSQL (0.0ms)←[0m  ←[1mUSE [Perfil_Corporativo]←[0m
    => #<MyModel id: nil, title: "My Title", created_at: nil, updated_at: nil>
    irb(main):002:0> m.save
        ←[1m←[35mSQL (0.0ms)←[0m  BEGIN TRANSACTION
        ←[1m←[36mSQL (0.0ms)←[0m  ←[1mEXEC sp_executesql N'INSERT INTO [my_models] ([created_at], [title], [updated_at]) OUTPUT inserted.id VALUES (@0, @1, @2)', N'@0 datetime, @1 nvarchar(255), @2 datetime', @0 = '2015-7-28T16:17:00.466', @1 =N'My Title', @2 = '2015-07-28T16:17:00.466'←[0m  [["created_at", Tue, 28 Jul 2015 13:17:00 CLT -03:00], ["title", "My Title"], ["updated_at", Tue, 28 Jul 2015 13:17:00 CLT -03:00]]
        ←[1m←[35mSQL (0.0ms)←[0m  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
    SystemStackError: stack level too deep
            from C:/Ruby193/lib/ruby/1.9.1/irb/workspace.rb:80
    Maybe IRB bug!

I've created other two applications to do this test (using SQL Server 2005):
1. App A using Rails 4.0.0 and activerecord-sqlserver-adapter 4.0.0. All actions (select, update, insert and delete) works fine.
2. App B using last versions of both Rails (v. 4.2.3) activerecord-sqlserver-adapter (v. 4.2.4). And it is possible to insert but I can't do a select action, surely due to compatibility issues with SQL Server 2005, but the strange thing here is that is possible to do an insert action even not being compatible.

**Comment by metaskills** [comment]
This is odd... most `stack level too deep` messages have more to them than just irb/workspace. Is there more there? If not, then have you tried debuting your irbrc file or something?

**Comment by metaskills** [comment]
Closing this old issue. Please ping me back with more info if any is available.

**Comment by pakerimus** [comment]
Hi @metaskills, @cbezares!
I'm having the same issue here... did you find a solution? a workaround?

I'm working on
- windows 8.1 64 bits
- sqlserver 2005
- ruby 2.0.0p195 (2013-05-14) [i386-mingw32]
- Rails 4.1.4
- activerecord-sqlserver-adapter 4.1.0
- tiny_tds 0.6.2-x86-mingw32

When I try to create an element using the console:
`m = MyModel.find_or_create_by(attr1: "some", attr2: "thing")`
I get
`irb(main):042:0> b = MyModel.find_or_create_by(attr1: "some", attr2: "thing")`
`  MyModel Load (1.0ms)  EXEC sp_executesql N'SELECT TOP (1) [my_models].* FROM [my_models] WHERE [my_models].[attr1] = N''some'' AND [my_models].[attr2] = N''thing'''`
`  SQL (0.0ms)  BEGIN TRANSACTION`
`  SQL (11.7ms)  EXEC sp_executesql N'INSERT INTO [my_models] ([attr1], [attr2], [created_at], [updated_at]) OUTPUT inserted.id VALUES (@0, @1, @2, @3)', N'@0 nvarchar(255), @1  nvarchar(255), @2 datetime, @3 datetime', @0 = N'some', @1 = N'thing', @2 = '2016-03-08T19:33:56.763', @3 = '2016-03-08T19:33:56.763'  [["attr1","some"], ["attr2","thing"], ["created_at", Tue, 08 Mar 2016 19:33:56 UTC +00:00], ["updated_at", Tue, 08 Mar 2016 19:33:56 UTC +00:00]]`
`  SQL (1.0ms)  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION`
`SystemStackError: stack level too deep`
`        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/irb/workspace.rb:86`
`Maybe IRB bug!`

**Comment by pakerimus** [comment]
I tried on my test server:
- Ubuntu 12.04
- ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]
- Rails 4.1.4
- activerecord-sqlserver-adapter (4.1.0)
- tiny_tds (0.6.2)

Same result.

`SystemStackError: stack level too deep`
`        from /home/deployer/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/irb/workspace.rb:86`
`Maybe IRB bug!`

**Comment by metaskills** [comment]
* Have you tried the latest version of TinyTDS? The `0.9.5.rc.3` is the latest pre-release.
* Does your `[my_models]` table have anything like triggers associated with it?

Searching for the same error on TinyTDS.

* https://github.com/rails-sqlserver/tiny_tds/issues/25
* https://github.com/rails-sqlserver/tiny_tds/issues/246

Have you tried making sure a shorter password helps or not?

**Comment by pakerimus** [comment]
I'll try with the latest version of tiny_tds.
My server password's length is less than 30 chars.
My tables are triggers free.

**Comment by pakerimus** [comment]
Tried with 0.9.5.rc.3, same result.

Perhaps is something about the timestamps columns, as @cbezares suggested?
How could I skip using those columns (created_at, updated_at)? Dropping them?

Thanks!!!

**Comment by metaskills** [comment]
I would try to ignore those columns and see what happens. A quick Google search on that topic showed a couple of neat hacks to try that out.

* http://devblog.bluefuton.com/post/2976251392/ignore-columns-in-a-legacy-database-with-activerecord
* https://github.com/nthj/ignorable

**Comment by pakerimus** [comment]
Ignoring those columns works!

**Comment by metaskills** [comment]
OK... so now we should find out why. Is it one column vs the other? Are both the same datatypes? What are those datatypes?

**Comment by pakerimus** [comment]
The datatype is "datetime" in both columns.
I tried ignoring just one, and the errror shows again, no matter which one.

**Comment by metaskills** [comment]
Can you show me a full stack trace of the error?

**Comment by pakerimus** [comment]
Hi. I don't know how to get a full stack error... 
I do this in the console:
begin
  x = MyModel.create(attrib1: "something")
rescue Exception => e
  puts e.backtrace
  raise
end

And I see this

  SQL (0.0ms)  BEGIN TRANSACTION
  SQL (1.0ms)  EXEC sp_executesql N'INSERT INTO ...
  SQL (0.0ms)  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.4/lib/active_record/transactions.rb:286
SystemStackError: stack level too deep
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/irb/workspace.rb:86
Maybe IRB bug!

**Comment by metaskills** [comment]
That shows a little... what happens when you do just this in console?

```
x = MyModel.create(attrib1: "something")
```

**Comment by metaskills** [comment]
Link to line number for my records https://github.com/rails/rails/blob/v4.1.4/activerecord/lib/active_record/transactions.rb#L286

@pakerimus Can you do a simple insert to that table via the TinyTDS connection? For example:

```ruby
insert_sql = "..."
tinytds_conn = MyModel.connection.raw_connection
tinytds_conn.execute(insert_sql).do
```

See what breaks, what does not, if errors happen, what the stack trace is, etc.

**Comment by pakerimus** [comment]
Hello Ken!
Here is my code:
```
begin
  record = MyModel.new(attrib1: "some", attrib2: "thing", created_at: Time.now)
  my_statement = record.class.arel_table.create_insert.tap { |im|
    im.insert(record.send(:arel_attributes_with_values_for_create, record.attributes.compact.keys))
  }.to_sql
  puts my_statement
  tinytds_conn = MyModel.connection.raw_connection
  tinytds_conn.execute(my_statement).do
rescue Exception => e
  puts e.backtrace
  raise
end
"INSERT INTO [my_models] ([attrib1], [attrib2], [created_at]) VALUES (N'some', N'thing', '2016-03-11T11:29:19.904')"
=> 1
```
There is no error...

**Comment by metaskills** [comment]
Well, that puts it squarely on the adapter. I did not have a lot to do with 4-1-stable work, but I will re-open this issue and see what I can do.

**Comment by pakerimus** [comment]
Thanks a lot man!
Tell me if is anything I can help you with!
