### ISSUE TITLE
Spatial/GIS support

### ISSUE THREAD

**Issue by cobracmder** [rails-sqlserver/activerecord-sqlserver-adapter#41]
Does the SQL Server adapter support Spatial/GIS data types? If so, is it stand alone or with GeoRuby extensions?

**Comment by ansonhoyt** [comment]
@cobracmder did you end up finding a SQL Server adapter that supports spatial types? It looks like [spatial_adapter](https://github.com/pdeffendol/spatial_adapter) is no longer maintained, and [rgeo](https://github.com/rgeo/rgeo) is now the preferred choice. However, rgeo only has adapters for PostGIS, MySQL and SQLite. Like you, I'm hoping to find something for SQL Server.

**Comment by cobracmder** [comment]
@ansonhoyt we ended up ditching ruby/rails and sql server altogether for that project and went with python/django and postgresql/postgis.

**Comment by metaskills** [comment]
FWIW, I've found that even when using MySQL's spatial functions that I end up using stored procedures when needed with Rails. Whatever works best for you.
