### ISSUE TITLE
null values written into the database

### ISSUE THREAD

**Issue by hbzhang** [rails-sqlserver/activerecord-sqlserver-adapter#410]
There, I tried to use 

gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter'

I am able to write to sql server database on another server. However, the string I am trying to write turns out to be 'NULL' values in the database tables. 

What is wrong here?

I used the latest version of tiny_tds,activerecord-sqlserver-adapter, rails 4.2, sql server 2014.

**Comment by metaskills** [comment]
Please explain the issue you are having in more detail. I can not understand at all.

**Comment by hbzhang** [comment]
sorry for the posting of this between two projects.

After db:migrate, I tried to use db:seed for writing some values into the database. However, the string values written into the sql server database is 'NULL'.

**Comment by metaskills** [comment]
I wont be able to help till you identify what your db/seed code is doing. Why do you think this is an adapter issue?

**Comment by hbzhang** [comment]
Sorry. Figure this out. I removed the attr_writer in the model, it causes trouble. I do not know why add this too file names causing trouble. This is somehow surprise to me.
