### ISSUE TITLE
Please release a 4.1.x with 2014 support

### ISSUE THREAD

**Issue by l8nite** [rails-sqlserver/activerecord-sqlserver-adapter#413]
I noticed that there is 2014 support on the 4.1-stable branch -- can you guys please cut a release for that change?

**Comment by faisalmansoor** [comment]
@l8nite +1

**Comment by metaskills** [comment]
Whoops... forgot about that. Just tagged and pushed v4.1.1

**Comment by l8nite** [comment]
:beers:
