### ISSUE TITLE
Issues with synonyms, adapter cant find the information schema tables when using synonyms

### ISSUE THREAD

**Issue by agacode** [rails-sqlserver/activerecord-sqlserver-adapter#415]
I'm working on a project migrating a solution from C# - SQLSRV to Rails - SQLSRV

We are using a MasterDB and a lot of Secondary DBs for the business, in the MasterDB we have all the synonyms for all the other objects in the Secondary DBs, because the objects (tables, view etc.) tend to change their location, so we only use the synonyms from the app.

I'm having issues consuming those synonyms from rails. I have tables named like DB2.dbo.Table3, but I actually have to do this in the code: 
```ruby
self.table_name = 'MasterDB.Table3'
```
Because I'm forced to use the synonyms, so, methods like find, create, new, find_or_initialize_by, and some others, don't work for me, because rails goes to the INFORMATION SCHEMA tables to find the definition of the tables, and of course inside MasterDB is not going to find the definition of DB2.dbo.Table3.
I'm stocked on this issue. Do you have any solution for synonyms targeting tables in some other DB?

**Comment by metaskills** [comment]
Thanks for the repot. I have not heard of this issue before nor has sanonymn support been on our radar before either. Do you think this is an easy way to update our `column_definitions` method to help with this?
