### ISSUE TITLE
Problem when order by field name is a T-SQL keyword

### ISSUE THREAD

**Issue by paulewetzel** [rails-sqlserver/activerecord-sqlserver-adapter#417]
The following SQL

EXEC sp_executesql N'SELECT [phrasing_phrases].* FROM [phrasing_phrases] WHERE [phrasing_phrases].[locale] = ''en'' AND (value is not null)  ORDER BY phrasing_phrases.key

errors out because phrasing_phrases.key needs to be formatted as phrasing_phrases.[key] in order for it to work, as "key" is a T-SQL keyword

I experimented with formatting  [ phrasing_phrases].[key] in visitors/sqlserver.visit_Orders_And_Let_Fetch_Happen, but that caused an error in Arel. Also note that  [phrasing_phrases].[locale] = ''en'' is actually single quoted twice and not double quoted as it look here.

Here is a relevant chunk of the trace:

TinyTds::Error: Incorrect syntax near the keyword 'key'.: EXEC sp_executesql N'SELECT [phrasing_phrases].* FROM [phrasing_phrases] WHERE [phrasing_phrases].[locale] = ''en'' AND (value is not null)  ORDER BY phrasing_phrases.key'
Completed 500 Internal Server Error in 31ms

TinyTds::Error - Incorrect syntax near the keyword 'key'.:
  activerecord-sqlserver-adapter (4.2.3) lib/active_record/connection_adapters/sqlserver/database_statements.rb:340:in `handle_to_names_and_values_dblib'
  activerecord-sqlserver-adapter (4.2.3) lib/active_record/connection_adapters/sqlserver/database_statements.rb:329:in `handle_to_names_and_values'
  activerecord-sqlserver-adapter (4.2.3) lib/active_record/connection_adapters/sqlserver/database_statements.rb:304:in `_raw_select'
  activerecord-sqlserver-adapter (4.2.3) lib/active_record/connection_adapters/sqlserver/database_statements.rb:299:in `block in raw_select'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
  activerecord-sqlserver-adapter (4.2.3) lib/active_record/connection_adapters/sqlserver/database_statements.rb:299:in `raw_select'
  activerecord-sqlserver-adapter (4.2.3) lib/active_record/connection_adapters/sqlserver/database_statements.rb:244:in `sp_executesql'
  activerecord-sqlserver-adapter (4.2.3) lib/active_record/connection_adapters/sqlserver/database_statements.rb:19:in `exec_query'
  activerecord-sqlserver-adapter (4.2.3) lib/active_record/connection_adapters/sqlserver/database_statements.rb:199:in `select'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
  activerecord (4.2.0) lib/active_record/querying.rb:39:in `find_by_sql'
  activerecord (4.2.0) lib/active_record/relation.rb:638:in `exec_queries'
  activerecord (4.2.0) lib/active_record/relation.rb:514:in `load'
  activerecord (4.2.0) lib/active_record/relation.rb:243:in `to_a'
  activerecord (4.2.0) lib/active_record/relation/delegation.rb:132:in `method_missing'
  activerecord (4.2.0) lib/active_record/relation/delegation.rb:99:in `method_missing'
  phrasing (3.2.9) app/controllers/phrasing_phrases_controller.rb:22:in `index'

**Comment by paulewetzel** [comment]
Update on this issue, the SQL was not being generated, but was provided view the .order() method as raw SQL. So I think you can close this ticket.

**Comment by paulewetzel** [comment]
This is where the SQL that caused the problem originated. query.order("#{query.table_name}.key").

I was able to get it working using  query.order(:key), but it would not work using  query.order('key') as it did not wrap it in brackets such as '[key]'

**Comment by metaskills** [comment]
Yea... if you give a string to an `order` relation, ActiveRecord considers it a SQL literal. The symbol interface looks up the appropriate relation column and does all the quoting. Cheers!
