### ISSUE TITLE
Is it possible to use it with ActiveRecord 4.2 and MS-SQL Server 2008?

### ISSUE THREAD

**Issue by AlfredoRoca** [rails-sqlserver/activerecord-sqlserver-adapter#418]
I'm using Rails 4.2.0 with Ruby 2.2.0 and I have to connect to a SQL Server 2008. 
Can I do it with activerecord-sqlserver-adapter? How?

**Comment by metaskills** [comment]
No... you have to use Rails 4.1 and the matching 4.1.x version of the adapter.

**Comment by AlfredoRoca** [comment]
I'm using it anyway and at this moment it's working. I'm just doing simple SELECT queries. Still happy :-)

**Comment by metaskills** [comment]
Well, as soon as you hit limit/offset on those selects... you are going to have a bad time :) closing this issue. Cheers.
