### ISSUE TITLE
Azure - Graceful Disable Referential Integrity

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/activerecord-sqlserver-adapter#421]
We use the `sp_MSforeachtable` stored procedure for the `disable_referential_integrity` method of the adapter. This stored procedure does not exist on Azure SQL databases. In the past we have recommended copying this procedures implementation from an older database (https://gist.github.com/metaskills/893599) to Azure. We can do better than this. Possible ideas include:

* Bundle that procedure SQL with the adapter.
* Possible shim that procedure in during db:setup and/or db:test:prepare.

**Comment by metaskills** [comment]
Exploring these. I think what I like is that we focus on just how to turn off constraints, we may not need the hack/patch for that SP. 

* http://edspencer.me.uk/2013/02/25/drop-all-tables-in-a-sql-server-database-azure-friendly/
* http://blog.sqlauthority.com/2015/05/01/sql-azure-how-to-disable-and-enable-all-constraint-for-table-and-database/

**Comment by metaskills** [comment]
OK, so I really like how this went down. Commit https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/commit/4517ba673eb808844841e8fe2ed050533d414f35 basically removes `sp_MSforeachtable` in favor of just selecting the `schema.table` names we need that have referential integrity. This new method need not reflect on Azure or not. It is just a more pragmatic way of doing this. In this way, we have a clean simple way to use Azure.

With this change out of the way, I am now able to run tests on Azure and start fixing a few failures. 

cc @TigerMint

**Comment by TigerMint** [comment]
This is awesome. Thanks @metaskills !

 sp_MSforeachtable is one of those unsupported/undocumented store procs and never worked on Azure.
