### ISSUE TITLE
4-1-stable, columns with spaces breaks with rails versions > 4.1.1

### ISSUE THREAD

**Issue by nicpillinger** [rails-sqlserver/activerecord-sqlserver-adapter#424]
Trying to get a project up and running using the 4-1-stable branch (SQL Server is 2008). If I upgrade rails past 4.1.1 I get the following problem:

SyntaxError: /Users/nicpillinger/.rvm/gems/ruby-2.2.2@mic-uk-data-connector/gems/activerecord-4.1.2/lib/active_record/attribute_methods/time_zone_conversion.rb:36: formal argument cannot be a constant
              def Creation Date=(time)

for all columns which have a space in them. Works fine in 4-1-stable with rails 4.1.1.

The 4.1 branch of rails is up to 4.1.13 with security and patches.

Presumably something changed in AR between 4.1.1 and 4.1.2 that broke this? Any ideas? Help!

**Comment by metaskills** [comment]
Interesting. I just ran the tests for Rails v4.1.13 with the adapter v4.1.2 and found no errors. Both us and ActiveRecord has tests for method with spaces in them. So I can say with a strong level of confidence that this should not be an issue and it might be coming from some other place in your code. Can you investigate further and let me know?

**Comment by nicpillinger** [comment]
OK thats positive, thanks! Could it be to do with Datetime fields? This is a sql server datetime field - is AR trying to do some coercion on it?

**Comment by nicpillinger** [comment]
If I do an AR select on anything it falls over on that field. If I do a Model.pluck("Creation Date").first it all works ok. This suggests to me it is AR mapping that field across and going bang? Thoughts?

**Comment by metaskills** [comment]
Well... what you are doing is giving it a SQL literal there. Maybe if you use a symbol it would work? Can you try `.pluck(:"Creation Date")` to see if that helps?

**Comment by nicpillinger** [comment]
I was saying pluck works fine. select on the other hand does not - presumably because that then maps the whole table back into an AR object.

**Comment by metaskills** [comment]
Same applies. It is a SQL literal. Please try `.select(:"Creation Date")` or maybe better yet. `.select("[Creation Date]")` which quotes the string for SQL Server.

**Comment by nicpillinger** [comment]
Thanks @metaskills - tried both those and they both result in the same error I pasted in the initial issue. It looks like AR is trying to create a writer method...

def Creation Date=(time)

which then fails for obv reasons. Just wondering if any of the specs you have for field names with spaces cover fields of type Datetime?

**Comment by metaskills** [comment]
Type is moot IMO. ActiveRecord creates column accessor methods since day one. Lemme know what else you find.

**Comment by nicpillinger** [comment]
Not sure what else to try. I can successfully retrieve records from the db fine with 4.1.1 - if I delete my Gemfile.lock and change rails version to 4.1.2 and bundle install it starts failing. My ActiveRecord class is simple enough  -

    class Legacy::Model < ActiveRecord::Base

      establish_connection :mydb
      self.table_name = "[db].[tblModel]"

It does seem to cope with fields with spaces in as the [Creation Date] field it fails on is definitely not the first in the list. Thats why I was guessing it might be to do with the datetime stuff.

**Comment by metaskills** [comment]
OK, I did change out test to use a :date type columned and all hell broke loose. If it helps, it works just fine in the latest 4.2 work. 

This sounds like a Rails/ActiveRecord regression, but I'm open to anything. Just not sure I have time to track that down now since it feels like a Rails issue and I am working on TinyTDS updates and Rails 5 work now. Either way, hope this info is helpful.
