### ISSUE TITLE
Document & Test New Rails Applications Using Azure

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/activerecord-sqlserver-adapter#425]
This ticket is to discuss the details of how we streamline setting up new applications on Azure. Topics could include things like what binaries we want to strategize on using for the DB setup and structure tasks. For example, my working theory is that when TinyTDS includes native bin stub wrappers (https://github.com/rails-sqlserver/tiny_tds/issues/227) that we will use `tsql` for the console and setup binary.

**Comment by TigerMint** [comment]
I am currently going through this experience from a perspective of a total newbie. =) will have a write up to share shortly after RubyCon.
