### ISSUE TITLE
ActiveRecord::Base doesn't belong in a hierarchy descending from ActiveRecord

### ISSUE THREAD

**Issue by wconrad** [rails-sqlserver/activerecord-sqlserver-adapter#428]
If I do _all_ of these things:

* Use the activerecord-sqlserver-adapter
* Define the model before connecting to the database
* on a table that has no _id_ column

And then call #exists? on a relation for that model:

    DataStagePropertyAttributes.where(property_id: 'ABC').exists?

Then the query raises the exception:

    ActiveRecord::Base doesn't belong in a hierarchy descending from ActiveRecord (ActiveRecord::ActiveRecordError)

# Versions

* activerecord 4.2.5
* activerecord-sqlserver-adapter 4.2.5
* SqlServer 12.0.2000
* Ruby 2.2.2p95
* Debian Linux "jessie" (stable as of 2015-12-01)

# Gists

[This gist][1] has:

* [fail.rb][2] -- A stand-alone program to reproduce the problem
* [stack_trace][3] -- The full stack trace from running fail.rb
* [model_defined_after_connecting.rb][6] -- Shows that the query works if the model is defined after the connection is defined.
* [model_has_id.rb][4] -- Shows that the query works if the table has an ID column
* [sqlite3.rb][5] -- Shows that the query works in sqlite3

[1]: https://gist.github.com/wconrad/9d0b85dbf0b34476ad7f
[2]: https://gist.github.com/wconrad/9d0b85dbf0b34476ad7f#file-fails-rb
[3]: https://gist.github.com/wconrad/9d0b85dbf0b34476ad7f#file-stack_trace
[4]: https://gist.github.com/wconrad/9d0b85dbf0b34476ad7f#file-model_has_id-rb
[5]: https://gist.github.com/wconrad/9d0b85dbf0b34476ad7f#file-sqlite3-rb
[6]: https://gist.github.com/wconrad/9d0b85dbf0b34476ad7f#file-model_defined_after_connecting-rb

**Comment by metaskills** [comment]
I think the model should be defined after the connection is defined. That wold mimic the Rails boot behavior too.

**Comment by wconrad** [comment]
@metaskills That is how I fixed my application.  I implemented lazy loading for models, as Rails does.

Is it a requirement of ActiveRecord that the models are defined only after the connection is established?  If so, then it is reasonable to declare this "not a bug" and move on.  Otherwise, it seems that this behavior is a bug (although I admit that it is a very edgy case, given the several uncommon circumstances that are needed to trigger it).

I've written non-Rails ActiveRecord apps against Oracle, Postgresql, and Mysql.  They don't have this behavior.  That alone doesn't say that this behavior is a bug, but it does does say that it's a little unusual.

I want to emphasize that although I suspect this may be a bug, I am _not_ arguing that it is a important one.  It's quite an edge case, and it has a workaround.  It did took me a day to figure out what was going on, so if the behavior can be made to go away, that could save some trouble for the next person in my circumstance (if there ever is one).

**Comment by metaskills** [comment]
> Is it a requirement of ActiveRecord that the models are defined only after the connection is established? If so, then it is reasonable to declare this "not a bug" and move on.

Well, when you define a model, depending on how you use that constant, you could be hitting the database for it to lookup the schema and column information. 

I think what your script reflects most is that you are defining the schema after the model and connection. In this situation, it is much like a migration set where the model, if used in another migration, would have an incorrect schema cache. This is why the recommendation is to use ad-hoc inline models in migrations or if you absolutely have to use the global model name, you call `MyModel.reset_column_information` in the next migration.

This is what your script may be exposing. For example, in fail.rb, call `DataStagePropertyAttributes.reset_column_information` before the last line.

**Comment by metaskills** [comment]
Going to close this issue. Thanks so much, if you think there is something we can do to change the adapter, please open a patch. I am not seeing anything here that I can a) prioritize and/or b) could fix real quick.
