### ISSUE TITLE
Counting when using select gives an error

### ISSUE THREAD

**Issue by rept** [rails-sqlserver/activerecord-sqlserver-adapter#429]
Hi,

I have this code:

```ruby
def cases
  Case.joins(:file_actors)
    .where('fileactors.FA_TPTID = ?', third_party_type)
    .where('fileactors.FA_TPID in (?)', self.thirdparties.ids)
    .select('files.*, fileactors.FA_Reference')
end
```

I include the FA_Reference because I want to avoid extra queries later down the line.

This is used in a search.  When there isn't anything returned I give a message.  When once result it found I redirect to the case found, if many are found I show a grid with the results.

Now I'm getting this error message:

```
TinyTds::Error: Incorrect syntax near '*'.: EXEC sp_executesql N'SELECT COUNT(files.*, fileactors.FA_Reference) FROM [files] INNER JOIN [fileactors] ON
```

Is this a known issue?  Why doesn't it always uses count(*), since that will work all the time.

BTW I'm using v4.1.2 because of SQL2008R2.

**Comment by metaskills** [comment]
Well finder SQL and counter SQL is usually different. I am not sure you can use the projections (the select clauses) as part of the relation like that and have it work for both count/find. That just looks like a limitation of ActiveRecord. Do you have examples of where this works in Rails core adapters?

**Comment by rept** [comment]
@metaskills I just tested this in PG and you are absolutely correct.  This doesn't work there as well so it's indeed a limitation of ActiveRecord!
