### ISSUE TITLE
ActiveRecord::Base.connection.execute is returning a FixNum ?

### ISSUE THREAD

**Issue by rept** [rails-sqlserver/activerecord-sqlserver-adapter#430]
Hi,

With postgres I've used ActiveRecord::Base.connection.execute on multiple occasion to be able to get fast reporting.

I'm trying to do the same with SQL server.  I have this code:

```ruby
  def open_files_last_weeks
    query = ActiveRecord::Base.connection.execute(
    %Q[WITH Dates AS
      (select top 20 Year, Week, MIN(caldate) as MinDate, MAX(caldate) as MaxDate from calendar
      where caldate <= getdate() group by Year, Week order by Year desc, Week desc)
      select MinDate, COUNT(*) as OpenCases from Dates inner join Files on FI_CreationDate <= MaxDate and (FI_ClosingDate IS NULL or FI_ClosingDate >= MinDate)
      where dbo.GetFileActor(FI_ID, 1) in (#{ @user.thirdparty_ids.join(', ') })
      group by MinDate;])
    query
  end
```

The query executes fine and when I check profiler it returns records as it should.  However when I check query, the class is a FixNum and the content is 20?  There seems to go something wrong while parsing the result?

I'm using version 4.1 of the gem.

**Comment by metaskills** [comment]
Perhaps the identity insert expression is getting caught up. For example, what does this return?

```ruby
ActiveRecord::Base.connection.execute "SELECT 'test' AS [result]"
```

If the answer is that key/value. Then the the identity insert could be catching this. FWIW, the #execute is not the interface you want to use. Most people make this mistake, but Rails internals does not really guarantee the return value here. Please use one of these which is more inline with your expectations. https://github.com/rails/rails/blob/4-1-stable/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L21-L51

**Comment by metaskills** [comment]
Closing this issue since #execute is not a return value guarantee, but please feel free to reply with questions or comments.

**Comment by rept** [comment]
Hi @metaskills indeed, ActiveRecord::Base.connection.select_rows works perfectly!  Thanks.
