### ISSUE TITLE
Display chinese characters in array

### ISSUE THREAD

**Issue by lethunder** [rails-sqlserver/activerecord-sqlserver-adapter#432]
I have an issue with my rails app. I want to display non-ASCII characters (like Chinese) in an array.

When I display the array content, I have this:

puts array_table  => ["a","b","\xE6\x80\xBB\xE8\xA1\xA8 Main Report"]
The third element is in English + Chinese but displays like you can see.

If I try to display the third element only:

PUTS array_table[2] => "总表 Main Report"
What I need to run my app is to have my array like this:

["a","b","总表 Main Report"]

	
i added this in application.rb file config.encoding = "utf-8" and this to environment.rb Encoding.default_external = Encoding::UTF_8 Encoding.default_internal = Encoding::UTF_8 but stil not working 

I don't have this issue with postgrel database.
Any idea?

I have windows 2012 server R2 with SQL Azure latest connecting trough ODBC driver with activerecord-sqlserver-adpater 4.2.3, rails 4.1.6 with ruby 2.

**Comment by metaskills** [comment]
The adapter has nothing to do with Arrays and display of chars. I believe what you are trying to say is that the encoding of the data is not coming back correctly from the DB/Adapter. 

If you are using RubyODBC, it does not handle this, please use TinyTDS instead and your problem will go away.
