### ISSUE TITLE
Support 2008 Datatypes Using TDSVER=7.3 

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/activerecord-sqlserver-adapter#433]
TinyTDS now supports these datatypes via the 7.3 TDS protocol in 0.95 and up of FreeTDS.

* [date]
* [datetime2]
* [datetimeoffset]
* [time]

Like the TInyTDS docs say, these types have long returned strings in older versions and/or when not using a newer version that is not running the TDS protocol of 7.3 or higher. The 4.2 adapter and upward needs to optimize for these types a default supported and error gracefully. 

This means we are going too create out own type objects which assume that the proper ruby primitive comes from the raw connection. If this is not the case due to running an old version of FreeTDS or a lower protocol version, we will just return string types and let what has always happened happen, for the end user to figure it out.

**Comment by metaskills** [comment]
@sgrif I now remember EXACTLY why the adapter needed column and type object casting. It all boils down that we have ~6 date/time types which need different quoting. The issue only seems to be when there is no implicit column associated with the predicate value. I believe this only happens when using the older `where(['written_on = ?', written_on])` array style. Differences seen in these two tests. https://github.com/rails/rails/blob/4-2-stable/activerecord/test/cases/finder_test.rb#L679-L695

In the case of the array conditions, I believe things fall thru to the `quoted_date` methods responsibility. You can see how I simple delegate here (http://git.io/vuYfS) now to two simple types. But imaging if the `written_on` column is a `datetimeoffset` column where no zone casting should happen. I would never be able to quote it properly. 

I think the lesson here is that if you want proper quoting, you have to use the hash predicate notation, for example `where(written_on: obj)` which would find the right type and hence column quoting. Do you agree? Also, is there any documentation in Rails about how predicate strings loose strict column/type quoting and should perhaps be avoided? TIA!

**Comment by sgrif** [comment]
> I think the lesson here is that if you want proper quoting, you have to use the hash predicate notation

If that's an option, you should always be doing it. You should never be doing string form for simple equality or inequality.

> Also, is there any documentation in Rails about how predicate strings loose strict column/type quoting and should perhaps be avoided?

No, I'm not sure there's a great place to document it specifically. I've been meaning to write up a full guide on our type casting behavior for some time, which would cover that.

> In the case of the array conditions, I believe things fall thru to the quoted_date methods responsibility. You can see how I simple delegate here (http://git.io/vuYfS) now to two simple types.

Yeah, this is a common issue in Ruby, where we just don't have enough types to represent what we want. (e.g. We should have a better type to represent, binary, but AR just uses ACII-8BIT strings for it for lack of a better option).
