### ISSUE TITLE
SQL 2008 R2 and AR sqlserver adapter 4.1.2 - error

### ISSUE THREAD

**Issue by Jirka1111** [rails-sqlserver/activerecord-sqlserver-adapter#434]
ActiveRecord::StatementInvalid (TinyTds::Error: Incorrect syntax near 'OFFSET'

I have even downgraded Rails to 4.1.14 and this issue is still in my log and my app does not work. So what version of gem do I need to have to properly works with my SQL server?

Thank you.

**Comment by Jirka1111** [comment]
Nevermind, I am a moron. Development was working, but production wasn't. I have just forgotten to make a git push.

Thank you and please close this issue.

**Comment by metaskills** [comment]
No worries! Thanks for posting back too!
