### ISSUE TITLE
Connection to both postgres & sql server

### ISSUE THREAD

**Issue by rept** [rails-sqlserver/activerecord-sqlserver-adapter#441]
Hi,

Most of my application is in postgres but there are some queries I need to execute to SQL server.

For this I found this link: http://stackoverflow.com/questions/6122508/connecting-rails-3-1-with-multiple-databases

Set up the following model:

```ruby
class Azure < ActiveRecord::Base
  establish_connection("azure_#{Rails.env}".to_sym)

  def database_list
    query = ActiveRecord::Base.connection.select_rows (
        %Q[select * from sys.databases where database_id > 1;])
    query
  end
end
```

When I do:

```
[1] pry(main)> a = Azure.new
=> #<Azure:0x007fd2a71fa960>
[2] pry(main)> a.database_list
   (4.8ms)  select * from sys.databases where database_id > 1;
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "sys.databases" does not exist
LINE 1: select * from sys.databases where database_id > 1;
                      ^
: select * from sys.databases where database_id > 1;
from .rvm/gems/ruby-2.3.0@rails-devise/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
[3] pry(main)> 
```

It seems to connect fine but ActiveRecord::Base.connection seems to use postgres instead of SQL server.  I also tried connection without the ActiveRecord::Base part but that didn't work either.

How do I need to reference the activerecord connection to the SQL server?

**Comment by metaskills** [comment]
Please use the pattern mentioned at the top of this gist. https://gist.github.com/metaskills/4065702 for full detail, read this blog post. http://technology.customink.com/blog/2015/06/22/rails-multi-database-best-practices-roundup/

**Comment by rept** [comment]
Hi @metaskills,

Thanks for your reply.  I went over it again, and finally found the solution:

Instead of doing:

```ruby
    query = ActiveRecord::Base.connection.select_rows (
        %Q[select * from sys.databases where database_id > 1;])
```

I needed to do this:

```ruby
    query = AzureBase.connection.select_rows (
      %Q[select name from sys.databases where database_id > 1;])
```

Works fine now ;-)
