### ISSUE TITLE
ActiveRecord 5? Error Bundler

### ISSUE THREAD

**Issue by ginolon** [rails-sqlserver/activerecord-sqlserver-adapter#444]
```
ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'activerecord-sqlserver-adapter'. (Bundler::GemRequireError)
```

Error everywhere with Rails 5?

Also if I use:

`gem 'activerecord-sqlserver-adapter', :github => 'rails-sqlserver/activerecord-sqlserver-adapter', :branch => 'master'`

How can I do?

**Comment by metaskills** [comment]
I have not started work on the 5.x support.
