### ISSUE TITLE
Refine nvarchar quoting

### ISSUE THREAD

**Issue by RayBeaumont** [rails-sqlserver/activerecord-sqlserver-adapter#447]
I know there has been a previous issue raised (#124) with regard to the nvarchar string prefix but I believe my problem is a bit different and I would like to raise an issue. 

**Background**
- The SQL Server database I am accessing is 2008 and cannot be updated
- All the varchar columns are `Latin1_General_CI_AS` and cannot be altered
- Since the database cannot be updated to 2012  I am having to use **activerecord-sqlserver-adapter v4.1**
- My database connection config contains `encoding: CP1252` which is a valid iconv encoding

**Problem**

The use of the `N` nvarchar prefix in the `where` clause causes a type mismatch when the query is executed and results in table scans which, on large queries, cripples the performance.  If I coerce my parameters to CP1252 and supply as an Array to the `where` method the `N` prefix is not applied :-). But it is still applied if supplied as a Hash :-(.

```
where("col = ?", 'value'.encode("CP1252"))
```

yields 

```
WHERE (col = ''value'')
```

which is cool. But 

```
where(col: 'value'.encode("CP1252"))
```

yields 

```
WHERE (col = N''value'')
```

which is not. 

This is because the current (v4.1) implementation of `Sqlserver::Quoting.quote` applies the prefix if a string column is given, regardless of the encoding of the value:

```
elsif value.is_utf8? || (column && column.type == :string)
  "#{quoted_string_prefix}'#{quote_string(value)}'"
```

Overriding `ActiveRecord::ConnectionAdapters::Sqlserver::Quoting.quoted_string_prefix` to remove the prefix entirely breaks the adapter.

**Solution**
One solution (below) is to amend the quote method to apply the prefix only if the value is utf8, whether the column is supplied or not. This seems like a rather drastic modification and whilst it seems to be working for me I'm concerned that it might be unwise?  I'd be interested in your thoughts and, if you think this a prudent solution, if it could be added to the 4.1 branch?.

```
elsif ((column && column.type == :string) && value.is_utf8?) ||
        (column.nil?  && value.is_utf8?)
  "#{quoted_string_prefix}'#{quote_string(value)}'"
```

**Comment by metaskills** [comment]
Nice write up! I have to say, your solution looks clean. A few thoughts:

* Yup, that Quoting.quote is needed because the paths in Rails to take predicate values are numerous and quoting happens at different places. That said, I always just assumed you could do something like this nuclear option if you never ver needed smart quoting `ActiveRecord::ConnectionAdapters::Sqlserver::Quoting::QUOTED_STRING_PREFIX.replace('')`
* Another option is to use the `SQLServerColumn#is_utf8?` method which reflects on the data type.

**Comment by RayBeaumont** [comment]
Liking `SQLServerColumn#is_utf8?`, much better idea.

So my patch now looks like 

```
elsif (column && column.is_utf8?) || (column.nil?  && value.is_utf8?)
  "#{quoted_string_prefix}'#{quote_string(value)}'"
```

This seems much better - if the column is **not** a NVARCHAR/NTEXT/NCHAR then **don't** add the prefix (because that would create a type mismatch). If no column is given then fall back to adding the prefix if the value itself is utf8.

I'll run the tests on this patch once I  figure out how to create the test databases (the SQL Server I'm using is not mine).

**Comment by marceloeloelo** [comment]
@metaskills @RayBeaumont could an equivalent fix could be applied to the latest version of the gem? I'm suffering from the same issue and getting big performance implications.

**Comment by marceloeloelo** [comment]
FYI I'm working on a fix for the latest version. In case you want to take a look I'm open to suggestions, it's just a WIP for now https://github.com/marceloeloelo/activerecord-sqlserver-adapter/pull/1

We would need to keep an eye on the `quote` method for `rails-5` though since they are changing how column casting works.

**Comment by metaskills** [comment]
Thanks @marceloeloelo. The same is true for Rails 4.2, we do not have that quote method and this is why this ticket is marked as 4-1-stable. So any PR would have to be against that branch of ours.

**Comment by marceloeloelo** [comment]
I just created a PR compatible with `rails 4.2.6` #461

**Comment by metaskills** [comment]
Closing this issue since it is not needed in 4-2-stable. I'll evaluate he work done in that branch if anyone steps forward with a PR for 4-1-stable. Meanwhile, putting energy to Rails 5 work.
