### ISSUE TITLE
Schema File Issues with tests - Random primary key?

### ISSUE THREAD

**Issue by billr578** [rails-sqlserver/activerecord-sqlserver-adapter#452]
I'm using GUIDs as primary keys in a majority of our models.  To set these up, I'm doing to following type of migration:

```
class CreateApplications < ActiveRecord::Migration
  def change
    create_table :applications, id: false do |t|
      t.uuid :uuid, null: false
      t.string :name, null: false
      t.timestamps
    end

    execute "ALTER TABLE applications ADD PRIMARY KEY (uuid)"

    # Add our reference_id identity column
    execute "ALTER TABLE applications ADD [reference_id] INTEGER IDENTITY NOT NULL"
    add_index :applications, :reference_id, unique: true
  end
end
```

This gives us a primary key on the uuid column and a reference_id column that we can auto increment to look up objects by an integer value when we don't want to use the GUID.  Anywhoo...

When I run rake db:migrate, the schema.rb file has randomly picked reference_id to be my primary_key.  So I end up with something like this:

```
create_table "applications", primary_key: "reference_id", force: :cascade do |t|
    t.uuid     "uuid",                                              null: false
    t.string   "name",               limit: 4000,                   null: false
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "applications", ["reference_id"], name: "index_applications_on_reference_id", unique: true
```

Not exactly what I'm looking for here.  Any ideas how the rake task is randomly deciding to pick up reference_id as my PK?  the primary_key: true directive seems to only work on integer values hence why I'm just setting it with some SQL.  I'm a bit stuck here because, while my app works as it should, my tests don't because the schema structure is off using the wrong PKs.

**Comment by billr578** [comment]
I think the culprit is in sqlserver_adapter.rb:

```
def primary_key(table_name)
   identity_column(table_name).try(:name) || schema_cache.columns(table_name).find(&:is_primary?).try(:name)
end
```

It checks for the identity_column as the primary_key.  I removed it and got what I wanted, but my primary key is an int not a uniqueidentifier.  So only partially there...

**Comment by metaskills** [comment]
Yea, there is a logic in a few places. It really all starts in schema reflection, specifically `column_definitions` where `is_identity` and `is_primary` is set. There is a reason `identity_columns` is first but I would have to run the tests to remember why.

> my primary key is an int not a uniqueidentifier

Is that true? You just told SQL Server when you crated the table that you wanted a uniqueidentifier column and then you manually made it a primary key with that execute statement. Essentially, I think long hand for this?

```ruby
create_table 'applications', id: :uuid do |t|
  # ...
end
```

Also, are you using `self.primary_key = ...` in your model?

**Comment by billr578** [comment]
Yeah, I'm using self.primary_key in the model.  I also switched the migration to use something like:

```
t.primary_key :uuid, :uuid
```

instead of executing the query manually.  

So is my error here trying to use a column name not named :id as my PK?  Am I just pushing the boundaries of what the adapter is designed to do?  For what its worth, I've also noticed some wackiness selecting data at the console and .find where the adapter seems to be selecting against my identity column which is called reference_id instead of the uuid column (named uuid) which is my PK.  Happy to share some more code if it will help.

**Comment by billr578** [comment]
I decided to take a step back and forget about the test schema for a bit and work with migrations without any custom SQL.  If I try to set up a foreign key using t.references or t.belongs_to, should the adapter set up the column type as a uniqueidentifier type if that's what the source table PK is?  I'm finding they just get set to an int type if I do something like:

```
create_table :applications, id: :uuid do |t|
   t.timestamps
end

create_table :application_users, id: :uuid do |t|
   t.references :application, null: false
end
```

Sorry for all the questions...just trying to figure out how to set this up right.

**Comment by billr578** [comment]
So, I cleaned up all of my migrations and I think everything is set up right...except for this custom identity column I'm adding.  rake db:test:prepare still sets it as my PK so none of my foreign keys work properly.  Is this something that's just not supported?  Time to get some sleep before I ask any more silly questions.  :-)

**Comment by metaskills** [comment]
> So is my error here trying to use a column name not named :id as my PK?

ActiveRecord supports that. We have a few tests that build on top of it too. So you are in good territory. That said, when you start building your schema the way you did in the migration, you may expose a few bugs.

> .find where the adapter seems to be selecting against my identity column

Once we sort out the core issue, that should be fixed.

Can you show me your new table creation and schema output? Thanks

**Comment by billr578** [comment]
Ok, cool.  I think I'm in a better place with my migrations now (thanks to some of your questions previously making me dig a little deeper into best practices).  Here are some of my migrations:

https://gist.github.com/billr578/368e127de74ee3e2c3fb

And if you want to look at the complete schema output:

https://gist.github.com/billr578/0d141583a437ae15bd17

Thanks for your help @metaskills - I definitely appreciate it.  I'm probably going to back out the integration of the identity column for now and see if that helps mitigate the issue for now since we're trying to get a version of the app up and running for internal vetting and testing.

**Comment by metaskills** [comment]
No problem. Thanks for posting those gists too. I read them quickly, so I could be off base here, but it feels like your work making the `reference_id` an identity column is something a) you need to do and b) complicates the schema dump. Case in point, the latest Rails/Adapter supports foreign keys and I can see you are using those in your migration. Maybe just make those `reference_id` a foreign key and be done with it. 

<img width="273" alt="screen shot 2016-03-08 at 9 03 31 pm" src="https://cloud.githubusercontent.com/assets/2381/13623051/a4583aee-e571-11e5-8f44-202615fda46c.png">

Screen shot of SMS on the Rails created test table.

```ruby
add_foreign_key :fk_test_has_fk, :fk_test_has_pk, column: "fk_id", name: "fk_name", primary_key: "pk_id"
```

**Comment by billr578** [comment]
We want the reference_id column to autoincrement (basically behave like an integer PK would without being a PK) because we have some clients that require a natural key (i.e. data warehousing, etc.) instead of a surrogate key.  So what we do is just create an integer value that's unique on that reference_id column so it can be used externally.  Using IDENTITY makes it easy to ensure we get that unique value instead of having our Rails app generate it for us (doing reads and writes to ensure that its unique).

I also noticed that the adapter generally wanted to use that reference_id when doing record lookups (i.e. a .find), which while it didn't break the app, also wasn't behaving as we'd expect.  My guess again is because its set as an IDENTITY column.  

I think that we really pushed the envelope of what the adapter is designed to do with that identity column on a non-PK both from a schema dump perspective as well as a record lookup perspective.  We do this same sort of thing with our .NET apps on top of SQL Server and it works without issue.

Anyway, do you know if this would be an easy thing to diagnose and possibly fix in the adapter?  At some point I do plan on learning more about the adapter so I can hopefully contribute on issues like this, unfortunately I just don't have the bandwidth right now as we're getting this app ready for mid-April.  Thanks @metaskills !

**Comment by metaskills** [comment]
> I do plan on learning more about the adapter so I can hopefully contribute on issues like this

That would be awesome. These are the places you want to hit if/when you find the time. We make it really easy to test edge case schema like this.

* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/schema/sqlserver_specific_schema.rb
* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/cases/schema_dumper_test_sqlserver.rb

Closing this issue till then. Cheers.
