### ISSUE TITLE
The target table ... of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause

### ISSUE THREAD

**Issue by haslinger** [rails-sqlserver/activerecord-sqlserver-adapter#453]
I am using:
* Ruby 2.1.8
* Rails 4.2.5.2
* tiny_tds 0.7.0
* activerecord-sqlserver-adapter 4.2.8
and I am getting the error

```
ActiveRecord::StatementInvalid: TinyTds::Error: The target table 'xxx' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause
```

I have added an initializer:
```
if ActiveRecord::Base.connection.class.name.match(/SQLServerAdapter/)
  ActiveRecord::ConnectionAdapters::SQLServerAdapter.use_output_inserted = false
end
```
as described in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/381#issuecomment-76366715

Any ideas what I am doing wrong?

**Comment by haslinger** [comment]
The reason for my problem is, that I use an  ActiveRecord::Base.connection to MySQL, so I have to set 
`ActiveRecord::ConnectionAdapters::SQLServerAdapter.use_output_inserted = false` unconditionally.

**Comment by metaskills** [comment]
May I suggest just using SecondBase for your secondary connection. https://github.com/customink/secondbase

**Comment by haslinger** [comment]
Thanks for the tip, I didn't know that!
