### ISSUE TITLE
primary_key method returns column Identity property instead of primary property

### ISSUE THREAD

**Issue by marceloeloelo** [rails-sqlserver/activerecord-sqlserver-adapter#454]
`ActiveRecord::ConnectionAdapters::SQLServerAdapter#primary_key` ([link to method](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/01c5963ed797faea323df06b9ea14e54adcdd24c/lib/active_record/connection_adapters/sqlserver_adapter.rb#L183)) is performing a lookup on the table's Identity column first and falling back to the Primary column later, only if it can't find the Identity one.

I wonder why we are taking that approach instead of making the look up on the Primary column **first**.

There are scenarios where the PK column for a table is not the same as the Identity column. In that case, the `primary_key` method is returning the wrong value. At least I would expect it to return the Primary and not the Identity.

From Microsoft SQL server [doc](https://msdn.microsoft.com/en-us/library/ms187742.aspx):

> Identity columns are commonly used in conjunction with PRIMARY KEY constraints to serve as the unique row identifier for the table. 

It's not restrictive, they can be used in conjunction but not necessarily in every case, so I think we should change it to be more consistent with the real definition.

Can anyone share thoughts on this?

**Comment by metaskills** [comment]
I think it makes perfect sense. Merged and will release v4.2.9 shortly. Thanks!
