### ISSUE TITLE
Limit method translates to wrong query

### ISSUE THREAD

**Issue by marceloeloelo** [rails-sqlserver/activerecord-sqlserver-adapter#456]
I have the following definition for an `ActiveRecord::Base` model using a legacy table:

```
class Account < ActiveRecord::Base
  self.table_name  = 'Data.dbo.Account'
  self.primary_key = 'DID'
end
```

Performing a `limit` query on that table returns the wrong SQL. Note that the `primary_key` is overridden at the model layer. Check the following code:

```
> Account.where(name: 'AccountName').limit(1).to_sql
"SELECT  [Data].[dbo].[Account].* FROM [Data].[dbo].[HHTVAccount] WHERE [Data].[dbo].[Account].[name] = N'AccountName'  ORDER BY [Data].[dbo].[Account].[RowID] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY"
```

Note that the SQL is ordering by `RowID` rather than `DID`, which is what I would expect.

Seems that limit translates to an ORDER BY statement. The problem is that the [code](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/v4.2.8/lib/arel/visitors/sqlserver.rb#L162) is assuming that the primary key to be used in the ORDER clause is the one extracted from the database, while in some cases that might not be true.

I'm not sure if there's any way of accessing the model defined primary_key within this class. That would be nice. But if it's not possible, another option would be to change the code to use the `TOP` statement rather than the `ORDER BY column ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY`

Thoughts?

**Comment by metaskills** [comment]
Closing, fixed by #455

**Comment by marceloeloelo** [comment]
@metaskills #455 fixes my specific issue (thanks for merging), but that PR not necessarily fixes this one in every case. I don't think we should close this one.

In general, I think the gem should never assume the PK from the database and always rely on the model definition first. That's how the rest of the adapters work, right?

I'm not sure if there's an easy way to accomplish that from the `activerecord-sqlserver-adapter/lib/arel/visitors/sqlserver.rb`. A technique I've seen in activerecord is populating the `orders` array before building the query, at the `relation` world ([example](https://github.com/rails/rails/blob/8f3427125018f59392dc876a8195ee2f54d2b51d/activerecord/lib/active_record/relation/finder_methods.rb#L151)). That way the correct `primary_key` already comes set when you need to build the SQL.

Another approach, which was the one I was suggesting, is using the `TOP` statement rather than `ORDER BY`. Something like:

```
> Account.where(name: 'AccountName').limit(1).to_sql
"SELECT  TOP 1 * FROM [Data].[dbo].[HHTVAccount] WHERE [Data].[dbo].[Account].[name] = N'AccountName' "
```

That way, you eliminate the necessity of having to manually deal with PKs.

**Comment by metaskills** [comment]
> In general, I think the gem should never assume the PK from the database and always rely on the model definition first. That's how the rest of the adapters work, right?

Not sure were are going to get far with that assumption. It works against ActiveRecord defaults and the whole point of DB reflection.
