### ISSUE TITLE
Error converting data type nvarchar to datetime2

### ISSUE THREAD

**Issue by dschneider** [rails-sqlserver/activerecord-sqlserver-adapter#457]
Hi there,

we are using Rails timestamps (updated_at and created_at) on our models. Both fields have the data type `datetime2`. We are also connecting to an Azure SQL database. Every once in a while we see the following error in our system when the `updated_at` timestamp is updated:

```
ActiveRecord::StatementInvalid: TinyTds::Error: Error converting data type nvarchar to datetime2.: EXEC sp_executesql N'UPDATE [bookings] SET [updated_at] = @0 WHERE [bookings].[id] = @1; SELECT @@ROWCOUNT AS AffectedRows', N'@0 datetime2(7), @1 int', @0 = N'06-21-2008 04:30:00.5e-05', @1 = 1
```

We are able to reproduce the issue with this snippet:

```
booking.updated_at = Time.new(2008,6,21, 13,30,0.000015020, "+09:00")
booking.save
```

It occurs whenever the nanoseconds of the timestamp are at some really small fractional value. We are using activerecord-sqlserver-adapter 4.2.8 and tiny_tds 0.7.0. We tried it with 4.2.9 and 0.9.5.rc.3 respectively, but the error still happens.

I saw changes related to the micro/nano second handling (Changelog: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/commit/5342848e6b924a5fbdce2b48872804fcbf78830e#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR22) for version 4.2.7, so I rolled back to 4.2.6 to see if the error still occurs and it does.

**Comment by metaskills** [comment]
Ah, great bug report. The core issue lies in how `TimeValueFractional` module implementation that `datetime` and `datetime2` types use to cast the fractional seconds. See:

```ruby
value = Time.utc 2008, 6, 21, 13, 30, 0, Rational(123456755, 1000)
seconds = (value.send(fractional_property).to_f / fractional_operator.to_f).round(fractional_scale) # => 0.1234568
seconds.to_s.split('.').last.to(fractional_scale-1) # => "1234568"

value = Time.utc 2008, 6, 21, 13, 30, 0, Rational(15020, 1000)
seconds = (value.send(fractional_property).to_f / fractional_operator.to_f).round(fractional_scale) # => 1.5e-05
seconds.to_s.split('.').last.to(fractional_scale-1) # => "5e-05"
```

I think the fix would be to ensure that `Float` is converted to a decimal properly so we can quote it.

```ruby
seconds = (value.send(fractional_property).to_f / fractional_operator.to_f).round(fractional_scale) # => 1.5e-05
seconds.to_d.to_s.split('.').last.to(fractional_scale-1) # => "000015"
```

I'm testing that fix now and will get an update out shortly.

**Comment by metaskills** [comment]
Just pushed v4.2.10. Lemme know how that works.

**Comment by dschneider** [comment]
@metaskills It works like a charm, thanks a lot for the quick fix!
