### ISSUE TITLE
Support Value Too Long Translated Exception

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/activerecord-sqlserver-adapter#458]
See: https://github.com/rails/rails/pull/23522/files

**Comment by metaskills** [comment]
See also this PR https://github.com/rails/rails/pull/23523

This SQL below generated the following exception.

```sql
INSERT INTO [events] ([title]) VALUES (N'123456')

-- Msg 8152, Level 16, State 13, Line 1
-- String or binary data would be truncated.
-- The statement has been terminated.
```

**Comment by jeremy** [comment]
Ping, upstream PRs merged

**Comment by neongrau** [comment]
Hi Ken!
Short question: is there any beta/test version with Rails 5 compatibility available yet?

**Comment by metaskills** [comment]
This is done in the new 5.0.0 release.
