### ISSUE TITLE
Is this gem Thread Safe

### ISSUE THREAD

**Issue by alex-bezek** [rails-sqlserver/activerecord-sqlserver-adapter#459]
I was wondering if there was any documentation around if this gem is thread safe? We are using rails 4.2.5

Thanks

**Comment by metaskills** [comment]
Hey Alex. I think that question is best answered by asking is Rails/ActiveRecord. That answer is YES. They have been for quite some time but sometimes they always find bugs. Most times, non-thread safe code is within out own applications. Another important question is are the raw connections to the DB thread safe. For us, that question is to TinyTDS and again the answer is YES. Hope this helps.

Are you having a specific issue that brought up the questions?

**Comment by alex-bezek** [comment]
There wasn't a specific issue that brought this up. As a team, we are evaluating 3rd party gems before using them and that was a question that came up. 
Thanks for the speedy response @metaskills .

**Comment by metaskills** [comment]
No problem! Let me know if anything comes up. Cheers.
