### ISSUE TITLE
Support of SQL Server 2008 or 2005 for Rails 4.2

### ISSUE THREAD

**Issue by robertleelittleiii** [rails-sqlserver/activerecord-sqlserver-adapter#462]
Are there any plans for this?

 I am upgrading a system to rails 4.2, but I need to do a data pull from another system that's running the older version of SQL server.

**Comment by metaskills** [comment]
Duplicate issues. Please read:

* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/406
* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/388
* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/384

In short, this is not going to happen. It seems simple, but it is not and a year old Rails version being actively patched is just fine for a 8 year old DB. Not meaning to be curt. But just trying to make it clear why this is not happening. It is not trivial.

**Comment by robertleelittleiii** [comment]
Sorry I missed those dups.

The system I am accessing will be upgraded some time next year so I will have to wait till then.  I am creating a small 4.1 app just to do the rake tasks to keep mysql and SQL Server in sync.  

My sysadmin reminded me that SQL 2008 R2 is supported by MS till 2019 (yikes a little long in the tooth)  After I am done with the rewrite, I may take a crack at it.  

Thanks for the quick response.

**Comment by metaskills** [comment]
> My sysadmin reminded me that SQL 2008 R2 is supported by MS till 2019 (yikes a little long in the tooth) After I am done with the rewrite, I may take a crack at it.

Yea, a billion dollar company support a product compared to a small open source project or even Rails is not a fair comparison :)

> I may take a crack at it.

Good luck. Thanks for responding.
