### ISSUE TITLE
Connecting SQL-Server directly to online Database

### ISSUE THREAD

**Issue by ijunaidfarooq** [rails-sqlserver/activerecord-sqlserver-adapter#463]
I have just installed both the gems which mentioned in `README.md` file. I have a query string and i want to connect to the database directly form localhost.. is it possible? 
```

class Timelapse < ActiveRecord::Base
  establish_connection({
    :adapter  => "sqlserver",
    :host     => "myhostname.net",
    :username => "myusername",
    :password => "mypassword",
    :database => "mydbname"
  })
end
```

and I went to `rails c` tried to do `Timelapse.first` and got an error which is 

```
TinyTds::Error: Adaptive Server connection failed
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/tiny_tds-0.7.0/lib/tiny_tds/client.rb:74:in `connect'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/tiny_tds-0.7.0/lib/tiny_tds/client.rb:74:in `initialize'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver_adapter.rb:311:in `new'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver_adapter.rb:311:in `dblib_connect'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver_adapter.rb:302:in `connect'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver_adapter.rb:58:in `initialize'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/sqlserver_base.rb:17:in `new'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/sqlserver_base.rb:17:in `sqlserver_connection'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
	from /home/ijunaidfarooq/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
	from /home/ijunaidfarooq/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:87:in `connection'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/querying.rb:39:in `find_by_sql'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/relation.rb:639:in `exec_queries'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/relation.rb:515:in `load'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/relation.rb:243:in `to_a'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.6/lib/active_record/relation.rb:630:in `inspect'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/ijunaidfarooq/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
```

**Comment by metaskills** [comment]
First... I see you are using Rails. So please use a `database.yml` vs calling `establish_connection` for every model. Especially if SQL Server is the only DB used. 

Your issue is with your what values you are using for connecting. Please try doing an IRB session and just making TinyTDS work to debug. See: https://github.com/rails-sqlserver/tiny_tds#tinytdsclient-usage Let me know what you find out. There is some good info in that ReadMe as well.

**Comment by ijunaidfarooq** [comment]
Have tried this
https://github.com/rails-sqlserver/tiny_tds#tinytdsclient-usage

only thing came out is Adapter connection failed!



Regards


*Junaid Farooq*
Software Developer, Evercam.io
+92347-8666955 | junaid@evercam.io | Evercam <http://evercam.io/> | Skype:
darulehsan1 <https://mail.google.com/mail/u/0/#>
<http://www.facebook.com/iOkay.uOkay>  <http://pk.linkedin.com/in/iamjunnii>
  <http://github.com/ijunaidfarooq>

**Comment by metaskills** [comment]
Using TinyTDS at that level will not output any adapter errors. I'm willing to help, but you are going to have to give me a lot more to go on that the README there suggests is important. As is now, I have nothing other than it does not work. For example:

* SQL Server version?
* Local or remote. Azure, etc? Is the server setup to open TCP connection?
* What version of FreeTDS did you compile against. ?
* What platform are you on?

And so much more. I'm literally blind to help you now.

**Comment by ijunaidfarooq** [comment]
I am on Ubuntu and currently I only have a connection string

Server=tcp:myserver.database.windows.net,1433;Database=TimelapseDB;User
ID=myuser@myserver.;Password=mypassword;Trusted_Connection=False;Encrypt=True;Connection
Timeout=30;

Am trying to connect the Azure, our database is on Azure.



Regards


*Junaid Farooq*
Software Developer, Evercam.io
+92347-8666955 | junaid@evercam.io | Evercam <http://evercam.io/> | Skype:
darulehsan1 <https://mail.google.com/mail/u/0/#>
<http://www.facebook.com/iOkay.uOkay>  <http://pk.linkedin.com/in/iamjunnii>
  <http://github.com/ijunaidfarooq>

**Comment by metaskills** [comment]
> Server=tcp:myserver.database.windows.net,1433;Database=TimelapseDB;User
ID=myuser@myserver.;Password=mypassword;Trusted_Connection=False;Encrypt=True;Connection
Timeout=30;

That looks like a Windows .Net or Java connection string or something. I have no idea how you are using that with TinyTDS?

**Comment by ijunaidfarooq** [comment]
```
require 'tiny_tds'
    client = TinyTds::Client.new username: 'myusername@myserver', password: '1buttonDB1234', host: 'myserver.database.windows.net', port: 1433, database: 'mydbname', azure:true
```

Am trying to use like this in Rails console.

**Comment by metaskills** [comment]
Did you use the proper username format mentioned here?
https://github.com/rails-sqlserver/tiny_tds#using-tinytds-with-azure

Also, you never told me the version of FreeTDS you compiled against? Use `tsql -C` on the command line for that info.

**Comment by ijunaidfarooq** [comment]
i don't have `tsql` because am not doing anything locally..

Connecting DB straightly to AZURE

and as you saw my TinyTds client am doing the same as mentioned in the
given doc you are mentioning for Azure



Regards


*Junaid Farooq*
Software Developer, Evercam.io
+92347-8666955 | junaid@evercam.io | Evercam <http://evercam.io/> | Skype:
darulehsan1 <https://mail.google.com/mail/u/0/#>
<http://www.facebook.com/iOkay.uOkay>  <http://pk.linkedin.com/in/iamjunnii>
  <http://github.com/ijunaidfarooq>

**Comment by metaskills** [comment]
So if you are running commands on a remote Ubuntu box... I need to know the version of FreeTDS on that box. Hence, please run `tsql -C` on that box. What I am looking for is the version of FreeTDS and if that version was compiled against OpenSSL. The output will show that. We/you, need to know that before moving forward. HTH.

**Comment by ijunaidfarooq** [comment]
Sir.. I am on ubuntu 14.. I am not on any box.

I don't have any FreeTDS, in rails app we just need to install gems and I
have installed both gems. and now am using it. I have not compiled
anything. even I don't need to.. why would I do that?



Regards


*Junaid Farooq*
Software Developer, Evercam.io
+92347-8666955 | junaid@evercam.io | Evercam <http://evercam.io/> | Skype:
darulehsan1 <https://mail.google.com/mail/u/0/#>
<http://www.facebook.com/iOkay.uOkay>  <http://pk.linkedin.com/in/iamjunnii>
  <http://github.com/ijunaidfarooq>

**Comment by metaskills** [comment]
Some background. The TinyTDS gem is like the MySQL gem or PG gems. Each compile against shared libraries installed on your platform. Ruby is the same way when installed via rbenv or rvm in your case. What we need to know is what version of FreeTDS compiled and linked to when you installed the gem. It most certainly did this or the gem install would have failed. That means it found FreeTDS on your system and used it. Please show me in a terminal (not rails console) what happens when you do this:

```
$ which tsql
```

**Comment by metaskills** [comment]
Also searched issues on TinyTDS with the keyword "ubuntu". Here is one that pops up as helpful. 

https://github.com/rails-sqlserver/tiny_tds/issues/247#issuecomment-162620871

**Comment by ijunaidfarooq** [comment]
​



Regards


*Junaid Farooq*
Software Developer, Evercam.io
+92347-8666955 | junaid@evercam.io | Evercam <http://evercam.io/> | Skype:
darulehsan1 <https://mail.google.com/mail/u/0/#>
<http://www.facebook.com/iOkay.uOkay>  <http://pk.linkedin.com/in/iamjunnii>
  <http://github.com/ijunaidfarooq>

**Comment by ijunaidfarooq** [comment]
See Sir what all i want to do is to connect to Azure SQL server where my database is.

Locally Yes and my App is hosted at aws so i need to connect there as well.. is there any way to come over this? that i may able to connect Azure DB? even not tinyTds or anyother way?

**Comment by metaskills** [comment]
Sorry, there may be a language barrier. Could you please show me the output of this on your Ubuntu machine?

```
$ which tsql
```

Did you try re-installing like Vin said here? https://github.com/rails-sqlserver/tiny_tds/issues/247#issuecomment-162620871
