### ISSUE TITLE
.select(:public) does not "escape" field

### ISSUE THREAD

**Issue by coin3d** [rails-sqlserver/activerecord-sqlserver-adapter#467]
Hello everyone!

```ruby
UserActivity.select(:public)
```
produces:

`UserActivity Load (1.7ms)  EXEC sp_executesql N'SELECT public FROM [user_activities]'
TinyTds::Error: Incorrect syntax near the keyword 'public'.: EXEC sp_executesql N'SELECT public FROM [user_activities]'
ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near the keyword 'public'.: EXEC sp_executesql N'SELECT public FROM [user_activities]'`

Shouldn't using a symbol convert `:public` into the proper SQL server format, like `.where()` does, for example?

```ruby
UserActivity.where(public: true)
```
produces:

`UserActivity Load (3.4ms)  EXEC sp_executesql N'SELECT [user_activities].* FROM [user_activities] WHERE [user_activities].[public] = 1'
=> #<ActiveRecord::Relation []>`

I'm not sure if it's a bug, or if it is intended to work like that - can someone tell me that? Btw, I'm using Rails 4.0.13 and activerecord-sqlserver-adapter (4.0.0)

**Comment by metaskills** [comment]
> Shouldn't using a symbol convert :public into the proper SQL server forma

Yes, it does do that in the latest version. I just checked Rails 4.2 and the matching adapter and it does indeed use SQL Server quoting for the symbol/column. 

My first assumption would be that Rails 4.0 did not do the quoting and simply passed the symbol as a string. I don't normally support version that far behind, going on 2 years now. But if you find that this is a problem with the adapter and you really want to make a pull request, I would be open to it. Closing for now. Thanks!
