### ISSUE TITLE
@connection.tables won't return full list when using multiple databases

### ISSUE THREAD

**Issue by marceloeloelo** [rails-sqlserver/activerecord-sqlserver-adapter#468]
Hi,

I think there might be a problem when trying to list all the tables if the app domain is using multiple databases. Here's the current code for fetching the table names:

```ruby
module ActiveRecord
  module ConnectionAdapters
    module SQLServer
      module SchemaStatements

        def tables(table_type = 'BASE TABLE')
          select_values "SELECT #{lowercase_schema_reflection_sql('TABLE_NAME')} FROM INFORMATION_SCHEMA.TABLES #{"WHERE TABLE_TYPE = '#{table_type}'" if table_type} ORDER BY TABLE_NAME", 'SCHEMA'
        end
      end
    end
  end
end
```
The simplified source query would be something like 
```sql
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
```

That query does not work when using multiple databases, since it will just default to the master db, excluding the tables from the rest of the dbs.

@metaskills do you know a way to query *all* tables from *all* databases? 

Or, do you think it would make sense to iterate over the declared databases and join to the array? Example:
```ruby
databases.each_with_object([]) do |db, tables|
  db_tables = select_values "SELECT #{lowercase_schema_reflection_sql('TABLE_NAME')} FROM #{db}.INFORMATION_SCHEMA.TABLES #{"WHERE TABLE_TYPE = '#{table_type}'" if table_type} ORDER BY TABLE_NAME", 'SCHEMA'
  tables.concat(db_tables)
end.uniq
```

I'd like to get your thoughts on this. Thanks!

**Comment by metaskills** [comment]
> That query does not work when using multiple databases, since it will just default to the master db, excluding the tables from the rest of the dbs.

That is correct and proper. A connection is to a specific database. If you your app touches a different database, then you would have a model that champions that connection, is set to abstract class and others would inherit from that. They would all see tables in that DB. Using multiple databases has many many ramifications and almost none of them the adapter should be concerned with. This is the scope of gems like [Secondbase](https://github.com/customink/secondbase) and many other open source projects that help glue active record internals up for multiple DBs. Hope that helps.
