### ISSUE TITLE
Cannot install 4.2.12

### ISSUE THREAD

**Issue by aliuk2012** [rails-sqlserver/activerecord-sqlserver-adapter#470]
Hi,

I tried to install v 4.2.12 which is the release on rugbygems but it fails with the following error message

```
Using actionview 4.2.6

Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: (null) (https://rubygems.global.ssl.fastly.net/gems/activerecord-sqlserver-adapter-4.2.12.gem)
Using actionpack 4.2.6
An error occurred while installing activerecord-sqlserver-adapter (4.2.12), and Bundler cannot continue.
Make sure that `gem install activerecord-sqlserver-adapter -v '4.2.12'` succeeds before bundling.
```

I'm using Mac OS X, ruby 2.2.2, rails 4.2.6

On a seperate note the [github version](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/releases)  hasn't been updated to show 4.2.12.

I've been able to bundle install version 4.2.11

**Comment by metaskills** [comment]
Just worked for me:

```
$ gem install activerecord-sqlserver-adapter -v '4.2.12'
Fetching: activerecord-sqlserver-adapter-4.2.12.gem (100%)
Successfully installed activerecord-sqlserver-adapter-4.2.12
1 gem installed
```

**Comment by aliuk2012** [comment]
I didn't gem install it, I used bundle. 
This is what I have in my gemfile

```
# Use sqlserver as the database for Active Record
gem 'activerecord-sqlserver-adapter'
```

This was generated automatically when I did 

```
$ rails new my-application -d sqlserver
```

**Comment by metaskills** [comment]
That command which also does a bundle install worked just fine for me. Closing this issue, but this sounds like it may be something on your end. FYI, please make sure you rubygems is up to date too. Run `$ gem update --system` to get the latest.
