### ISSUE TITLE
Hi Can you use this with rails 5? 

### ISSUE THREAD

**Issue by coderjonny** [rails-sqlserver/activerecord-sqlserver-adapter#474]
I'm trying to use this gem with rails 5, is that possible? If so, how? 

``` ruby
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Bundler could not find compatible versions for gem "activemodel":
  In snapshot (Gemfile.lock):
    activemodel (= 5.0.0.rc1)

  In Gemfile:
    activerecord-sqlserver-adapter (~> 4.2.0) was resolved to 4.2.0, which depends on
      activerecord (~> 4.2.0) was resolved to 4.2.0, which depends on
        activemodel (= 4.2.0)

    web-console was resolved to 3.1.1, which depends on
      activemodel (>= 4.2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by metaskills** [comment]
Rails 5 is not yet supported. Still working on it.

**Comment by metaskills** [comment]
FYI, this explains the versioning if you are interested. https://github.com/rails-sqlserver/activerecord-sqlserver-adapter#versions

**Comment by coderjonny** [comment]
I stepped down the rails version to 4.2 and it's working great, thanks @metaskills !
Any timeline for rails 5 support?

**Comment by BenMcH** [comment]
@metaskills Is there any way we could get an update on this? The company I work for wants to up to rails 5.

**Comment by metaskills** [comment]
Issue #528 was pretty hard but I recently got that done and master passing tests for all core adapter tests. I want to get CircleCI setup on the Linux docker image on master first. Then move on to hit the ~150 errors I see in the ActiveRecord test suite. 

My experience with the process says that ~10 fixes will address 80% of the errors. At that time I would consider the master branch OK'ish to explore using and soliciting for help on squashing those bugs. Few weeks or so. Thoughts?

**Comment by BenMcH** [comment]
@metaskills I've just read the contributing and am going to try to get into the code and help move this along a bit faster. If you have anything you'd like me to look at first, just let me know.

**Comment by metaskills** [comment]
Rails v5 is released.
