### ISSUE TITLE
sub-optimal query for column_definitions

### ISSUE THREAD

**Issue by jonbell** [rails-sqlserver/activerecord-sqlserver-adapter#477]
I noticed the column_definitions method in SchemaStatements was behaving very slow for our project.  Under further analysis, it is missing a join predicate between TABLE_CONSTRAINTS and the COLUMNS table on the TABLE_SCHEMA column.

Extending the predicate to filter with this predicate sped up the query considerably for us.

**Comment by metaskills** [comment]
That's awesome! Can you propose a diff and I can help confirm and run the tests?

**Comment by metaskills** [comment]
Closing with work done in PR #478
