### ISSUE TITLE
Why wiki pages were removed?

### ISSUE THREAD

**Issue by eddeyang** [rails-sqlserver/activerecord-sqlserver-adapter#479]
Are there any reasons for the removing?

**Comment by metaskills** [comment]
Yes, most were out of date.

**Comment by eddeyang** [comment]
Are there any plans to add more up to date info?

**Comment by metaskills** [comment]
What do you think is missing that is most important?

**Comment by l8nite** [comment]
@metaskills we're having trouble connecting to named instances with the "dataserver" attribute, was this changed recently in tds/the adapter?

**Comment by metaskills** [comment]
@l8nite I've never used that feature and we do not test for it in TinyTDS. If it were an issue, it would be at the FreeTDS layer first, then TinyTDS. There are a lot of moving parts in that setup too and not something the adapter would put in a wiki entry. Please open an issue on the TinyTDS repo please and we can talk thru it there. Cheers.
