### ISSUE TITLE
Output Parameters on Stored Procedure calls

### ISSUE THREAD

**Issue by AaronMertes** [rails-sqlserver/activerecord-sqlserver-adapter#480]
This library is great, thanks for your time and efforts in making it as good as it is. I'm wondering what it would take to get input/output parameters to work with this library? I realize that this is a request more than an issue, but i'm not sure where to put a request at.

**Comment by metaskills** [comment]
The effort to make this happen would have to be put into TinyTDS first? See this issue on that repo. https://github.com/rails-sqlserver/tiny_tds/issues/24.
