### ISSUE TITLE
Enable `supports_advisory_locks?`

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/activerecord-sqlserver-adapter#481]
See this [rails core commit](https://github.com/rails/rails/commit/2c2a8755460ec3d32ece91c9766dbd0304ece028) and the following SQL Server resources:
- http://dba.stackexchange.com/questions/72224/implementing-application-locks-within-sql-server-distributed-locking-pattern
- http://aboutsqlserver.com/2013/05/08/locking-in-microsoft-sql-server-part-17-implementing-critical-section-mutexes-in-t-sql/
- https://msdn.microsoft.com/en-us/library/ms189823.aspx

**Comment by jonahgeorge** [comment]
For anyone else coming across this, it appears that `supports_advisory_locks?` is set to false:

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/main/lib/active_record/connection_adapters/sqlserver_adapter.rb#L134-L136

This means the migrator lock from Rails 5.X will not be utilized for this adapter. 

Has anyone tried supporting this via [`sp_getapplock`](https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-getapplock-transact-sql?view=sql-server-ver16) and [`sp_releaseapplock`](https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-releaseapplock-transact-sql?view=sql-server-ver16)?
