### ISSUE TITLE
changed_attributes returning inconsistent data

### ISSUE THREAD

**Issue by marceloeloelo** [rails-sqlserver/activerecord-sqlserver-adapter#487]
Let's say I have an `Account` model which has some `varchar` columns. I'm seeing strange behavior when calling `changed_attributes`:

``` ruby
> Account
# => Account(ID: integer, Name: varchar, Address: string)

> account = Account.find(1)
# => #<Account ID: 1, Name: "ABCDE", Address: "123 Street">

> account.changed_attributes
# => {}

> account.save
# => true

> account.changed_attributes
# => { "Name" => "ABCDE" }
```

As you can see, there was no change to the `Name` attribute but it's still being included in the `changed_attributes` response _after_ the account object was saved.

@metaskills I can't explain this, do you have an idea on what might be going on? Have you experienced any similar issue with varchar?

Thanks

**Comment by metaskills** [comment]
I have not, we certainly would not test the test if this were the case. Did you ever find out what the issue was? Going to close this but feedback still welcome.
