### ISSUE TITLE
Connect Sql server in Ruby on rails

### ISSUE THREAD

**Issue by luis77** [rails-sqlserver/activerecord-sqlserver-adapter#489]
I need to connect to a SQL Server database, I installed gem 'tiny_tds' gem 'activerecord-sqlserver-adapter' gem 'deprecated'
my yml file:

default: &default
  adapter: sqlserver
  host: basddatos.dyndns.org
  username: zu
  password: pass
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: Basdatos_2016

I get this error: TinyTds::Error Server name not found in configuration files WHY? thanks

**Comment by metaskills** [comment]
Have you configured SQL Server to allow for TCP connections. Can you first verify that is true using something like `tsql -S servername:port -U 'servername\username' -P password` first.

**Comment by luis77** [comment]
Hello @metaskills i put this in the console: tsql -S basddatos.dyndns.org -U 'zu' -P pass and i get this: [TinyTds][v1.0.4][tsql]: /home/luis/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tiny_tds-1.0.4/exe/tsql
Error 20012 (severity 2):
	Server name not found in configuration files.
locale is "es_VE.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Error 20013 (severity 2):
	Unknown host machine name.
Error 20009 (severity 9):
	Unable to connect: Adaptive Server is unavailable or does not exist
There was a problem connecting to the server
