### ISSUE TITLE
Includes with references doesn't work

### ISSUE THREAD

**Issue by kirrmann** [rails-sqlserver/activerecord-sqlserver-adapter#490]
The query is build correctly and executed against the database, but I can't access any values/attributes.

Every value just returns nil.

Tried the newest version 4.2.15 with rails 4.2.6

Example:

``` ruby
User.includes(:orders).references(:orders).first[:user_id]
=> nil
```

http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-includes

**Comment by metaskills** [comment]
Sorry for the late reply, pruning old issues. Please do reply back if still needed.
