### ISSUE TITLE
Rails returns an empty active record and failed to initialize the attributes in side the model

### ISSUE THREAD

**Issue by anilkumar-nyros** [rails-sqlserver/activerecord-sqlserver-adapter#492]
I am getting an empty active record when i initialize new model object.I am using rails 3.2.2 and activerecord-sqlserver-adapter (3.2.13)
2.3.0 :030 > user = User.new
=> #<User > 
2.3.0 :031 >

when i access the attributes present in the model it returns an error like

2.3.0 :031 > user.UserName
NoMethodError: undefined method `UsersName' for #<User >

User Modal

class User < ActiveRecord::Base  
    attr_accessible :UserName, :Password, :RoleId, :EmployeeId, :Password_confirmation
end

**Comment by vijayasekharreddy** [comment]
Hi Anil, Can you please provide your complete user model & migration file?

**Comment by anilkumar-nyros** [comment]
Thanks for your replay vijay,

Modal


class User < ActiveRecord::Base

  attr_accessible :UserName, :Password, :RoleId, :EmployeeId,:Password_confirmation

  self.table_name = "Users"
  self.primary_key = "UsersId"

  validates :UserName, :Password, :EmployeeId,:RoleId, presence: true
  validates_confirmation_of :Password
  validates_uniqueness_of :UserName


  belongs_to :role, :class_name => Role, :foreign_key => :RoleId
  belongs_to :employee, :class_name => Employee, :foreign_key => :EmployeeId
  has_many :user_permissions, :class_name => UserPermission, :foreign_key => :UsersId, dependent: :destroy


  validates_presence_of :UserName, :Password, :EmployeeId,:RoleId
  
  def self.authenticate user,password
  	 user.Password == password  
  end

end

Regarding Migration ,I am using existing msql data base.
Field Names are: UserName, Password,RoleId,EmployeeId,Password_confirmation.

Thanks & Regards,
Anil.

**Comment by vijayasekharreddy** [comment]
Ok, Try to access existing records as follows from rails console & let me know the out put.

> user = User.first

**Comment by anilkumar-nyros** [comment]
2.3.0 :009 > user = User.first
  User Load (271.4ms)  EXEC sp_executesql N'SELECT TOP (1) [Users].* FROM [Users]'
 => #<User >

**Comment by vijayasekharreddy** [comment]
ok it seems there is no issue with database connection. Add the following line to your user model:

  attr_accessor: :UserName, :Password, :RoleId, :EmployeeId,:Password_confirmation

After that create a user object from Rails console & try to save it.

Thanks & Regards,
  Vijay

**Comment by anilkumar-nyros** [comment]
Thanks for you help Vijay,

The Issue was solved with that below line.
  self.table_name = "dbo.Users"

Thanks & Regards,
Anil

**Comment by vijayasekharreddy** [comment]
Ok great
