### ISSUE TITLE
Basic Rails 5.0 support

### ISSUE THREAD

**Issue by doits** [rails-sqlserver/activerecord-sqlserver-adapter#493]
I've seen some other issues tagged with `Rails 5.0`, but afaik those are some extended features (at least partly).

I'd like to know if there is already a (broad) timeframe when basic Rails 5.0 support is planned (e.g. for tables with *simple* `Integer`, `String`, ... columns which do not rely on special MSSQL features nor use newer ActiveRecord 5 features like `comment`). I hope it is mostly changing/rearranging some method parameters, but maybe I'm wrong.

I'm willing to help (code) and test it when there's an initial Rails 5.0 branch.

**Comment by metaskills** [comment]
I added a few notes to the README. Hope that helps.

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter#rails-v5-coming
