### ISSUE TITLE
Explicit limit option in schema causes invalid schema in other databases

### ISSUE THREAD

**Issue by PhilT** [rails-sqlserver/activerecord-sqlserver-adapter#505]
Is it necessary to include `limit` in all string, text and integer types in the schema if the driver default limits are used? I think this would make the schema file more portable if they could be omitted for the default limits.

**Comment by PhilT** [comment]
Actually, thinking about I could just put specific limits on the problematic fields so it's not really an issue.

**Comment by PhilT** [comment]
Ah, scratch that, the driver seems to ignore `limit` for `text` type. Given it's ignored why is it set in the schema dump?

**Comment by metaskills** [comment]
Hey, so sorry for the late reply. Yes, limits are included for all string types by default, even in other adapters.
