### ISSUE TITLE
ActiveRecord crash with 'where' query on date type

### ISSUE THREAD

**Issue by davedx** [rails-sqlserver/activerecord-sqlserver-adapter#506]
Query: shifts = SalespeopleShift.includes(:salesperson, :shift).where(shifts: {date: start_date..end_date})

date is type 'date', both in schema.rb and in SQL Server (Azure).

Another part of the app to simply list all the Shifts including their dates does work -- so select'ing from the table works, but it seems doing a 'where' on the date does not work.

ActiveRecord 5.0.0.1

TypeError: sp_executesql_sql_type can not find sql type for attr #<ActiveRecord::Relation::QueryAttribute:0x00000003255780 @name="date", @value_before_type_cast="2016-01-01", @type=#<ActiveModel::Type::Value:0x000000032557a8 @precision=nil, @scale=nil, @limit=nil>, @original_attribute=nil, @value="2016-01-01", @value_for_database="2016-01-01">
	from /home/bronroot/.rvm/gems/ruby-2.2.2/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:256:in `sp_executesql_sql_type'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:242:in `block in sp_executesql_types_and_parameters'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:241:in `each'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:241:in `each_with_index'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:241:in `sp_executesql_types_and_parameters'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:234:in `sp_executesql'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:19:in `exec_query'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:201:in `select'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/gems/activerecord-5.0.0.1/lib/active_record/relation/finder_methods.rb:389:in `find_with_associations'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:699:in `exec_queries'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:580:in `load'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:260:in `records'
	from /home/bronroot/.rvm/gems/ruby-2.2.2/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:683:in `inspect'

**Comment by metaskills** [comment]
The rails v5 adapter is not ready yet.

**Comment by ringe** [comment]
Hi, this problem seems to be solved in commit https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/commit/096e1b778b479a1d28bc73cb582a55acc30799dd

Just found the issue with Google and checked out the newest commit to see if it was good, after seeing the commit message there.

Thanks @metaskills

**Comment by metaskills** [comment]
Thanks, there is still a lot to do in the Rails v5 work. There are about 100 failures that can be clustered into several categories. Right now I am working on a few performance optimizations with using the default schema cache. Once that is done and I quantify the remaining errors, I'll post details and solicit for help.
