### ISSUE TITLE
Do migrations have native data type support

### ISSUE THREAD

**Issue by johnnymo87** [rails-sqlserver/activerecord-sqlserver-adapter#507]
I feel like I'm misunderstanding the [native data types listed in the readme](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter#native-data-type-support). Is there a way to use these in a migration? For instance ...

```
    create_table :SomeTable, primary_key: :SomeTableID do |t|
      t.smalldatetime :StartDate, default: 'getdate()', null: false
      t.smalldatetime :EndDate
    end

```

... throws ...

```
undefined method `smalldatetime' for #<ActiveRecord::ConnectionAdapters::SQLServer::TableDefinition:0x007fde99ea0658>
```

**Comment by metaskills** [comment]
You got the intent right. I thought I had all these tested (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/schema/sqlserver_specific_schema.rb#L7-L36) but I overlooked the smalldatetime one. Marked this to test/fix for 4.2/5.0

**Comment by metaskills** [comment]
I only have enough time to focus on 5.0 and 5.1. This change is now in master and will be in the upcoming v5.0.6 release.

**Comment by BenMcH** [comment]
If anyone needs this on rails 4.x for rake tasks like I did and cannot upgrade to 5.x quite yet, you can add this to the bottom of your Rakefile. It also will not monkey-patch if the method exists (So no worries about remembering to remove it later on)
```ruby
unless ActiveRecord::ConnectionAdapters::SQLServer::TableDefinition.method_defined?(:smalldatetime)
  module ActiveRecord
    module ConnectionAdapters
      module SQLServer
        class TableDefinition
          def smalldatetime(*args, **options)
            args.each { |name| column(name, :smalldatetime, options) }
          end
        end
      end
    end
  end
end
```
