### ISSUE TITLE
TinyTds::Error: 'ANSI_DEFAULTS' is not a recognized option.

### ISSUE THREAD

**Issue by yusdirman** [rails-sqlserver/activerecord-sqlserver-adapter#508]
Hi

I got this error when running rails console

```
$\> rails c
Running via Spring preloader in process 28562
Loading development environment (Rails 4.2.4)
2.2.4 :001 > Staff.limit(10).first
TinyTds::Error: 'ANSI_DEFAULTS' is not a recognized option.
from /home/diman/.rvm/gems/ruby-2.2.4@rails4.2/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver_adapter.rb:341:in `do'
```

I am using rails 4.2, tiny_tds with freetds 1.0 and connectingto sybasease server

But I can connect to the  server in console using `TinyTds::Client.new` method and can run query using this method

database.yml
```
staff: &staff
  adapter: sqlserver
  host: sybasehost.company.com
  port: 5000
  username: username
  password: secret
  database:  dbname
  tds_version: '100'
  # encoding: 'iso_1'
```

please help and thank you

**Comment by metaskills** [comment]
Hey there! Tho TinyTDS was primarily made for the SQL Server adapter, we do not test non-SQLServer DBs with this adapter nor is it meant to be used. There are many things we take advantage of in the adapter that only SQL Server supports (sql wise), least of which are the ANSI defaults during connection. I hope that makes sense. If you need to use Sybase with Rails... TinyTDS can be the "raw connection" but I have not really seen an adapter for that. Maybe use Sequel instead?
