### ISSUE TITLE
SQL Server 2014: TinyTds::Error: Incorrect syntax near 'OFFSET'

### ISSUE THREAD

**Issue by pfefferkorn** [rails-sqlserver/activerecord-sqlserver-adapter#509]
Hello,

I'm using rails 4.2.0 with activerecord-sqlserver-adapter 4.2.0, tiny_tds 0.7.0, activerecord-session_store 1.0. and SQL Server 2014.
Databaseaccess is OK, if I use Rails.application.config.session_store :cookie_store. 

If I use Rails.application.config.session_store :active_record_store there is a problem:

ActiveRecord::StatementInvalid (TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [sessions].\* FROM [sessions] WHERE [sessions].[session_id] = N''3fb7bd4d769baf683f8924b90199e551'' OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY')

SQL Server needs an 'ORDER BY' to use the 'OFFSET' clause.

Can somebody help?
Alt least one tip, please?

**Comment by pfefferkorn** [comment]
not even one tip?

**Comment by metaskills** [comment]
Odd, the default ActiveRecord/Arel stuff should handle that order for us. For example, calling `MyModel.where(...).first` would just work and so should the session stuff. I did some poking around and found that the session store is abstracted into a gem now. Here is https://github.com/rails/activerecord-session_store that repo and it feels like a bug may be in their hands.

* Have you tried using the latest version?
* Have you read the code of that gem to see where it may be going wrong?

I just took a look on master of that gem and they seem to be doing things right. I see `where(session_id: session_id).first` in the source. Can you investigate further and let me know?

**Comment by pfefferkorn** [comment]
added in config/application.rb:
`ActiveRecord::SessionStore::Session.table_name = 'dbo.sessions'`
solved the problems.

How can I set a general Schema 'dbo.'?
`ActiveRecord::Base.table_name_prefix = 'dbo.'`
does not work.

Thank you for your answer.

**Comment by metaskills** [comment]
> How can I set a general Schema 'dbo.'?
> ActiveRecord::Base.table_name_prefix = 'dbo.'
> does not work.

That would be a heavy handed approach. I think the proper way would be to make the DB do this by setting the both the user's default database and role. We made sure to do the same in our test setup (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/appveyor/dbsetup.sql) too. Hope that helps.
