### ISSUE TITLE
Failed to retrieve primary key for SQLServer 12

### ISSUE THREAD

**Issue by doe300** [rails-sqlserver/activerecord-sqlserver-adapter#512]
Running on branch rails5 on latest code (rails5@bec007e), retrieving a primary key (GUID) for a table fails with this error:

> undefined method `second' for nil:NilClass

thrown in

```
lib/arel/visitors/sqlserver.rb, line 193 in method 'primary_Key_From_Table'
```

Debugging shows, that the `schema_cache` is empty (there are no schemas for any table).

This issue only occurs with SQLServer 12. Running the same app against a SQLServer 11 with the same database does not fail, and the `schema_cache` contains correct values.

**Comment by metaskills** [comment]
That branch is not ready for bug reports yet. Still working on it. This is my current target before moving to ~100 AR core failures. https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/504

**Comment by doe300** [comment]
Got it:)
Any estimation (days/weeks/months), when the rails5-version will be stable?

**Comment by metaskills** [comment]
Closing this issue, we have released a v5 gem which passes all ActiveRecord tests.
