### ISSUE TITLE
type_cast_from_database for date field

### ISSUE THREAD

**Issue by michaelrigart** [rails-sqlserver/activerecord-sqlserver-adapter#515]
Hi,

I recently stumbled upon an issue using activerecord-sqlserver-adapter gem in combination with the paper-trail gem.

In short, paper-trail stores changes made on records. I does so by serialising the changeset and stores it in a text field. 

When changes are applied to a Date field, paper-trail will first convert the field to the proper format by calling `type_cast_for_database` .  By doing this, the date will be stored in a serialised structure as a string in the `_sqlserver_dateformat` format.

But when you deserialise the string, it will call `type_cast_from_database`, which is not implemented in activerecord-sqlserver-adapter. 
But due to the fact that the  `_sqlserver_dateformat` format is defined as `mm-dd-yyyy`, a typecast should happen.

I was able to achieve this by creating the `type_cast_from_database` method myself, but I was wondering if this should be included in the library? 

``` ruby
module ActiveRecord
  module ConnectionAdapters
    module SQLServer
      module Type
        class Date < ActiveRecord::Type::Date
          def type_cast_from_database(value)
            return unless value.present?
            return value if value.acts_like?(:date)
            ::Date.strptime(value.to_s, ::Date::DATE_FORMATS[:_sqlserver_dateformat])
          end
        end
      end
    end
  end
end
```

**Comment by metaskills** [comment]
Thanks, the type system was heavily nascent in Rails v4.2 and it got a lot better in v5. Would you mind checking with that version of the adapter now? We implemented a full set of type objects that know how to date/time objects using the format description you described.

>  should be included in the library?

Yes. But it was a nightmare for me to implement in v5. I would be open for a PR to out 4-2-stable branch for this if you had the time. Gonna close this issue for some pruning, but please reply and as needed or open that PR up.
