### ISSUE TITLE
Dumping empty tables makes me sad

### ISSUE THREAD

**Issue by kwerle** [rails-sqlserver/activerecord-sqlserver-adapter#516]
Table with no column fails.

```
class CreateNoColumns < ActiveRecord::Migration
  def change
    create_table(:no_columns, id: false) do |t|
      # t.string :a_column
    end
  end
end
```

If you uncomment the column, it'll work.

```
root@2505983bc667:/tmp/src/empty# rake db:migrate
== 20161010171721 CreateNoColumns: migrating ==================================
-- create_table(:no_columns, {:id=>false})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

TinyTds::Error: Incorrect syntax near ')'.: CREATE TABLE [no_columns] () 
/usr/local/bundle/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:300:in `do'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:300:in `raw_connection_do'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:253:in `block in do_execute'
/usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
...
```

**Comment by rushed** [comment]
Is something without columns a table? Regardless, if you have a use case you might consider adding the table with a throwaway column and then dropping it in a subsequent migration (if MSSQL will allow it).

**Comment by kwerle** [comment]
Legacy database.  DBAs.  Stuff I don't have control over.  I certainly didn't create 'em, and I wouldn't leave 'em around.  If wishes were fishes...

Sane or not, this seems like it should not throw.

**Comment by kwerle** [comment]
Guh.  sqlite behaves the same way.  OK - this seems like my personal problem.  I'll monkeypatch something...

**Comment by kwerle** [comment]
OK - having spent more time looking at the problem, it looks like maybe it should be addressed on the other end.

If you create a database and put a table or two in there that are in the dbo TABLE_SCHEMA, everything works fine.  But if you then add a table whose columns are in a TABLE_SCHEMA other than dbo, when you go to 
`rake db:schema:dump`
it will dump the name of the table into the schema.rb file but it will not save any of the column information.

Then when you go to recreate the table [for test], it will choke on a table with no columns.

**Comment by metaskills** [comment]
@kwerle Do you think we could make any changes to our `column_definitions` method that would help? For example, [this line](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/active_record/connection_adapters/sqlserver/schema_statements.rb#L348) could maybe would be an `IN` check with `schem_name()` and `schema_name(schema_id)` or something? Was reading this article

https://blog.sqlauthority.com/2009/06/17/sql-server-list-schema-name-and-table-name-for-database/

**Comment by metaskills** [comment]
Not finding it easy to change the `column_definitions` method. Going to close this issue, but please do open a pull request if you find time. I have to focus on the Rails 5.1 work.
