### ISSUE TITLE
db:schema:dump overly aggressive with integers?

### ISSUE THREAD

**Issue by kwerle** [rails-sqlserver/activerecord-sqlserver-adapter#517]
rake db:schema:dump creates a schema with integers that have tighter limits than I'd expect.  I'm not at all a SQL Server expert -- at all -- but this doesn't seem right:
```
rails g resource library name:string
rails g resource book title:string library_id:integer
rake db:migrate
rails c
<create a few libraries & books that belong to 'em>
rake db:schema:dump
```

Results in the following schema.rb file with t.integer  "library_id", limit: 4 for the FK:
```
ActiveRecord::Schema.define(version: 20161010173814) do

  create_table "books", force: :cascade do |t|
    t.string   "title",      limit: 4000
    t.integer  "library_id", limit: 4
    t.datetime "created_at",              null: false
    t.datetime "updated_at",              null: false
  end

  create_table "libraries", force: :cascade do |t|
    t.string   "name",       limit: 4000
    t.datetime "created_at",              null: false
    t.datetime "updated_at",              null: false
  end

end

```

The limit:4 seems like a bad thing.  But it also doesn't seem to be enforced when I 
rake db:schema:load
?

**Comment by rushed** [comment]
I think it's referring to four bytes (i.e.: ~ +/- 2 to the 31st, not 1, 2, 3, 4, done), which sounds normal for a MSSQL integer. Was there a problem you ran into?

**Comment by kwerle** [comment]
Ah - 4 bytes seems reasonable.  I thought (since it's a number) it was 4 decimals - which is obviously pretty small.

**Comment by metaskills** [comment]
Right about bytes, that's how other DBs do it too. You can see more about the expected values here: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/cases/schema_dumper_test_sqlserver.rb
