### ISSUE TITLE
Primary Key not being stored

### ISSUE THREAD

**Issue by PAMulligan** [rails-sqlserver/activerecord-sqlserver-adapter#518]
I'm connecting to a legacy database with a Rails API that I'm writing. Currently trying to use FactoryGirl to create models on my test database.

The primary key for the User table is called 'UserId'. In the model, I've set

    self.primary_key = 'UserId'

However, when I try this code:

    user = FactoryGirl.create :user 

I get "TinyTds::Error Cannot insert null value into column 'UserId'". Any thoughts on why this may be happening?

**Comment by metaskills** [comment]
I think the same would be true if you consoled into your app and did the model create! right?

**Comment by PAMulligan** [comment]
Yes, that's accurate

**Comment by metaskills** [comment]
OK, so is this model a view? Have you made sure that your ID is auto-incrementing at the DB layer?

**Comment by PAMulligan** [comment]
It's not a view, this is for an API. I know this isn't necessarily an issue
with the adapter, but I thought I'd start with this forum. Honestly, I'm
used to dealing with Devise and pg, and the way I set things up, there is
always an ID available. For this project, I'm not using Devise, and I'm
connecting to a pre-existing SQL Server database, so I'm not sure that the
ID is auto-incrementing.

**Comment by metaskills** [comment]
> I'm not sure that the ID is auto-incrementing

Ahh... I bet that is the issue. You can tell if you looked at the output of `YourModel.columns_hash['UserId']` I bet it does not have the right info. Maybe reach out to the DB team to see if they can add that. If you have any amount of activity on this table, that would be the way to go.

**Comment by PAMulligan** [comment]
There is no team, it's just me and my boss. He wrote our initial code a few
years ago, so I suppose I'll try asking him. I do know the primary key in
the schema for that model is listed as "UserId", which is why I thought
changing the primary key property in the model would do the trick. Thank
you for the help, I'll see if I can muddle through!

**Comment by PAMulligan** [comment]
I'm still lost on this, the output of User.columns_hash['UserId'] is indeed nil. I know this problem is due to my ignorance, but I have to deliver something usable this week, and I'm about to just create an API from scratch in C# so that I have something to show my boss. Any other insight anyone could provide would be useful.

**Comment by rushed** [comment]
Rails expects database schemas to conform to certain conventions. If yours doesn't you'll need to change it, pretend it does via views, or do additional work. This probably isn't a good forum for your question as it doesn't appear that you're describing a problem with activerecord-sqlserver-adapter. You might consider trying StackOverflow, the Rails channel on IRC, searching for articles about working with legacy DBs in Rails, or (as noted earlier in this thread) changing your primary key to be auto incrementing.

**Comment by PAMulligan** [comment]
What ended up working for me was to create migrations that added the indices that I needed. Make sure to add the name option as well, as outlined here: http://apidock.com/rails/v4.2.1/ActiveRecord/ConnectionAdapters/SchemaStatements/add_index. In the model, make sure to set self.primary_key and self.table_name to the correct values, as well. Now, using FactoryGirl to test my models is working perfectly!
