### ISSUE TITLE
Support for Rails 5

### ISSUE THREAD

**Issue by thomasfedb** [rails-sqlserver/activerecord-sqlserver-adapter#522]
Hi @metaskills, it would be great if you could create a meta-issue or a GitHub project to track the progression towards compatibility with Rails 5.

It would certainly help those of us who are waiting to upgrade our apps to Rails 5 to understand the backlog, and perhaps also to direct us to where we might be able to help.

Thanks!

**Comment by philipedwards** [comment]
Seconded. 

Please advise if we're able to support you. If you can create the tickets we can work on them. Even if you have a specific idea about how to solve a problem. I'd be happy to code to your brief if you have the time to put your thoughts down.

**Comment by metaskills** [comment]
This is now done. We got a 5.0.0 gem out today. Working on 5.0.1 with a few bugs for 2014 and 2012 DBs.

**Comment by clintmiller** [comment]
@metaskills I don't know if this is the place to say this, but I will anyways: Thank you for your work on this, and thanks to the other contributors as well.

**Comment by metaskills** [comment]
Thank you so much!
