### ISSUE TITLE
can't cast ActiveRecord::ConnectionAdapters::SQLServer::Type::Char::Data to varchar

### ISSUE THREAD

**Issue by neongrau** [rails-sqlserver/activerecord-sqlserver-adapter#523]
Getting the error

`can't cast ActiveRecord::ConnectionAdapters::SQLServer::Type::Char::Data to varchar`

when i try to modify or insert a record into a table that has varchar columns, although i'm not sure it's the varchar columns that is causing it.

Googling for the error made me suspect tiny-tds at first but downgrading that did not help.

So i downgraded activerecord-sqlserver-adapter from 4.2.15 insteps until i found that 4.2.10 is the last version working.

**Comment by neongrau** [comment]
could this be a side effect of the fix introduced by #471 ?

**Comment by neongrau** [comment]
OK after testing a bit i found that
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/491/files
seems to fix this issue.

All i needed to change was Data inheriting from String
`class Data < ::String`
Then everything worked as expected again.

**Comment by metaskills** [comment]
Closing this issue as Rails v5 is almost certainly better at this. Please do open a PR or suggest a code change to 4-2-stable if you want too. We still maintain that branch and interested in things that help.
