### ISSUE TITLE
Not able to execute a stored procedure using direct execute with raw sql

### ISSUE THREAD

**Issue by neohunter** [rails-sqlserver/activerecord-sqlserver-adapter#524]
If I do this:

```
MyModel.execute_procedure :SP_TEST_PROCEDURE, '123456'
```

It results some records as an array, which is what is expected, but if I do this:

```
result = ActiveRecord::Base.connection.execute("EXEC SP_TEST_PROCEDURE '123456'")
```

results is `-1`. I've traid with and without exec, adding an `N` before the quote, 

It's not suppose to return the same resultset?

**Comment by neohunter** [comment]
After research more about this I noticed that the `ActiveRecord::Base.connection` `#execute` method calls `do_execute(sql, name)`.

Which uses `raw_connection_do(sql)` instead of `raw_connection_run(sql)`

The difference between one method and the other is that is calls `do` at the end, like doing:

```
ActiveRecord::Base.connection.instance_variable_get('@connection').execute("sql").do
```

`#do` result the affected rows as you can see on the C code from tinytds extension:

```
# File 'ext/tiny_tds/result.c', line 434

static VALUE rb_tinytds_result_do(VALUE self) {
  GET_RESULT_WRAPPER(self);
  if (rwrap->client) {
    rb_tinytds_result_cancel_helper(rwrap->client);
    return LONG2NUM((long)dbcount(rwrap->client));
  } else {
    return Qnil;
  }
}
```

I'm not sure if this is intended behavior (i would prefer to return a `TinyTDS::Result` object instead, which i think is more like mysql2 adapter works.

Returning the affected row makes its unusable to do SELECT queries or execute SP.

Just in case someone needs to do raw sql selects this will work;

```
result = ActiveRecord::Base.connection.instance_variable_get('@connection').execute "SELECT * FROM [TABLE]"
result = result.each.map { |row| row.is_a?(Hash) ? row.with_indifferent_access : row }
```

That will get you an array of results.

**Comment by sixfeetover** [comment]
If you want results back, do this:

```ruby
ActiveRecord::Base.connection.select_all 'select * from whatever'
```

The `execute` method is for executing statements that do not return results (like `connection.execute 'set nocount on;'`).

**Comment by neohunter** [comment]
it will work to execute Stored Procedures?

Thanks

**Comment by sixfeetover** [comment]
I don't remember, try it. :) But why not just use `execute_procedure` in that case?

**Comment by metaskills** [comment]
Closing this issue. As @sixfeetover correctly stated, the `execute` method does not do what you expect. There are in fact many different interfaces in the database statements that are specific to certain tasks. Again, `select_all` is a great example. See here too:

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb

HTH
