### ISSUE TITLE
Misleading Error Message

### ISSUE THREAD

**Issue by l33z3r** [rails-sqlserver/activerecord-sqlserver-adapter#525]
Hi, when an SQL query times out by taking longer than the timeout specified in database.yml, the error message is kind of misleading. 

The error comes in as 'Adaptive Server Timed Out'

We thought it was a network issue at first, but finally nailed it down to a slow query. 

Would it be helpful to beef up this error message to say that a query is taking too long, rather than the server timed out message. 

Here is an example of a stack trace:

```
ActiveRecord::StatementInvalid: Adaptive Server connection timed out
…alizers/active_record_sqlserver_disable_transaction.rb:   57:in `block in save_with_disabled_transaction'
…alizers/active_record_sqlserver_disable_transaction.rb:   26:in `disable_transaction'
…alizers/active_record_sqlserver_disable_transaction.rb:   56:in `save_with_disabled_transaction'
…_radar/app/models/bet_radar/live_odds/parsers/score.rb:  117:in `save_set_score'
…_radar/app/models/bet_radar/live_odds/parsers/score.rb:   47:in `block in parse_score_from_match_node'
…_radar/app/models/bet_radar/live_odds/parsers/score.rb:   40:in `parse_score_from_match_node'
…ns/bet_radar/app/models/bet_radar/live_odds/message.rb:   94:in `process'
(eval):3:in `block in process_with_newrelic_transaction_trace'
(eval):2:in `process_with_newrelic_transaction_trace'
```

**Comment by rushed** [comment]
Sorry you found the message confusing, if you have a suggestion for a better description you might suggest it to one of the lower level projects as that is likely where the message originated (as opposed to the Rails adapter).

**Comment by metaskills** [comment]
There are two parts to your point. First, the message "Adaptive Server connection timed out" comes from SQL Server. That is not going to change. The other is the object which wraps the message. We do have an implementation of the abstract adapters `translate_exception` which has a few cases that Rails would like us to use for the exception object. For example, `InvalidForeignKey`. There is no standard for a timeout and using the proper super class `ActiveRecord::StatementInvalid` is the right thing to do here. Sorry you found it confusing, this is the first I've heard of it. Seems to make sense to me. Either way going to close this as I do not see any action items. Feel free to reply if you have more thoughts or actions. Totally willing to hear those.

**Comment by krzcho** [comment]
@metaskills I finally switched to edge adapter after migrating old databases hoping for better connection handling but I have problems:
(ActiveRecord::StatementInvalid) "TinyTds::Error: DBPROCESS is dead or not enabled: EXEC ..."
(ActiveRecord::StatementInvalid) "TinyTds::Error: Write to the server failed: EXEC ..."
why such errors do not result in reconnection?
