### ISSUE TITLE
Forward :contained login option to TinyTds

### ISSUE THREAD

**Issue by KDGundermann** [rails-sqlserver/activerecord-sqlserver-adapter#526]
The new `:contained` login option introduced in TinyTds with 
[09dc4dc](https://github.com/rails-sqlserver/tiny_tds/commit/09dc4dcc8504f10f353827509ac0ae33f61abd7b)
is ignored by activerecord-sqlserver-adapter

**Comment by metaskills** [comment]
Please see #527
