### ISSUE TITLE
TinyTds::Error: Error converting data type varchar to datetime2

### ISSUE THREAD

**Issue by sharmarahul** [rails-sqlserver/activerecord-sqlserver-adapter#531]
Connecting to remote azure sql server V12 database. One of the table contains a column that holds date. When I retrieve this record in ActiveRecord, I see the date returned in a string format. I want to retrieve all records in a daterange, But I keep getting error `TinyTds::Error: Error converting data type varchar to datetime2`

Have installed FREETDS version `v1.00.23`.
freetds.conf output contains
[global]
        # TDS protocol version
	tds version = auto

and tsql -C returns:

Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.23
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: no
                             GnuTLS: no
                               MARS: no

**Comment by sharmarahul** [comment]
OK from the documentation on tiny_tds:

Below is a list of the data types we support when using the 7.3 TDS protocol version. **Using a lower protocol version will result in these types being returned as strings.**

[date]
[datetime2]
[datetimeoffset]
[time]

tds version is set to auto in freetds.conf file and tsql -C also returns TDSVER=7.3 so wondering why it's still returned as a string!

**Comment by metaskills** [comment]
This type should work fine in the v5 adapter. Technically true for v4.2 or more technically, the TinyTDS version. What version of the following are you using?

* TinyTDS
* SQL Server Adapter
