### ISSUE TITLE
activerecord-sqlserver-adapter-3.2.14 with rails 3.2.22.5, problem in user options

### ISSUE THREAD

**Issue by nielsjansendk** [rails-sqlserver/activerecord-sqlserver-adapter#535]
Activerecord-sqlserver-adapter throws the following error at me:

/gems/activerecord-sqlserver-adapter-3.2.14/lib/active_record/connection_adapters/sqlserver/database_statements.rb:139:in `block in user_options': undefined method `gsub' for ["textsize", "2147483647"]:Array (NoMethodError)

I have tried this on ruby-2.1.10, ruby-2.2.6  and  ruby-2.3.3, same result. 

My database.yml file looks like this

>development:
> adapter: sqlserver
> mode: dblib
> dataserver: my_server
> database: my_database
> username: my_username
> password: xxxxxx
> timeout: 0

My Gemfile looks like this:

>source 'https://rubygems.org'
>gem 'rails', '3.2.22.5'
>
>gem 'tiny_tds', '~> 1.1'
>gem "activerecord-sqlserver-adapter", "~> 3.2.14"
>
>group :assets do
>  gem 'sass-rails',   '~> 3.2.3'
>  gem 'coffee-rails', '~> 3.2.1'
>
>  gem 'uglifier', '>= 1.0.3'
>end
>
>gem 'jquery-rails'

The application has nothing else in it, to isolate the problem. The error is thrown when I attempt to start a console. FreeTDS and Tinytds have been tested and work just fine.

**Comment by metaskills** [comment]
So this line here: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/3-2-stable/lib/active_record/connection_adapters/sqlserver/database_statements.rb#L139

Does your users have permissions to run `dbcc useroptions`? If not, it is needed.

**Comment by nielsjansendk** [comment]
Yes, I can execute "dbcc useroptions" from irb using tinytds, same connection properties.  The reuslts are:

>{"Set Option"=>"textsize", "Value"=>"64512"}
>{"Set Option"=>"language", "Value"=>"us_english"}
>{"Set Option"=>"dateformat", "Value"=>"mdy"}
>{"Set Option"=>"datefirst", "Value"=>"7"}
>{"Set Option"=>"lock_timeout", "Value"=>"-1"}
>{"Set Option"=>"isolation level", "Value"=>"read committed snapshot"}

**Comment by metaskills** [comment]
So `select_rows` is going to return an array of arrays vs the array of hashes like you posted. So technically the first `row` in the loop should be equal to `["textsize", "2147483647"]` but for some reason your error seems to indicate the value from `select_rows` is a double nested array. 

Can you do a `$ bundle open activerecord-sqlserver-adapter` and open this file and do some debugging. I'd like to know the return value for `select_rows("dbcc useroptions",'SCHEMA')` both in structure and the class of that object. TIA.

**Comment by nielsjansendk** [comment]
If I insert a print statement like this:

>def user_options
>          return {} if sqlserver_azure?
>          print select_rows("dbcc useroptions",'SCHEMA')
>
 >         select_rows("dbcc useroptions",'SCHEMA').inject(HashWithIndifferentAccess.new) do >|values,row| 
> ....

I get this output:

[[["textsize", "2147483647"], ["language", "us_english"], ["dateformat", "mdy"], ["datefirst", "7"], ["lock_timeout", "-1"], ["quoted_identifier", "SET"], ["ansi_null_dflt_on", "SET"], ["ansi_warnings", "SET"], ["ansi_padding", "SET"], ["ansi_nulls", "SET"], ["concat_null_yields_null", "SET"], ["isolation level", "read committed snapshot"]], []]

Is that what you were looking for?

**Comment by metaskills** [comment]
Yes... but can you also pring the `.class.name` of that object? I just want to make sure it is an `Array` or an `ActiveRecord::Result` which looks like an array too or even something else.

**Comment by nielsjansendk** [comment]
obejct.class outputs Array.

**Comment by metaskills** [comment]
Thanks! I don't know why, but I suspect TinyTds is returning the data like that which could be it, the server, some client config, or something else.  Can you show me the output from IRB with a TinyTds client connection of the following:

```ruby
@client.execute('dbcc useroptions').each(as: :array) 
```

**Comment by nielsjansendk** [comment]
The output in tinytds is as follows:

> [[["textsize", "64512"], ["language", "us_english"], ["dateformat", "mdy"], ["datefirst", "7"], ["lock_timeout", "-1"], ["isolation level", "read committed snapshot"]], []] 

The class is also an array.

**Comment by metaskills** [comment]
ODD! I get the following. The adapter would have been broken years ago for everyone if your output was normal. I wonder why it is coming back with what appears to be two result sets?

```
[["textsize", "2147483647"], ["language", "us_english"], ["dateformat", "mdy"], ["datefirst", "7"], ["lock_timeout", "-1"], ["quoted_identifier", "SET"], ["ansi_null_dflt_on", "SET"], ["ansi_warnings", "SET"], ["ansi_padding", "SET"], ["ansi_nulls", "SET"], ["concat_null_yields_null", "SET"], ["isolation level", "read committed"]]
```

**Comment by metaskills** [comment]
What version of FreeTDS are you using? The output of `tsql -C` should show it.

**Comment by nielsjansendk** [comment]
Version: freetds v1.00.23
TDS version: 7.3 

I am on a Mac OS Sierra and I just upgraded my homebrew (that is what started this whole thing).

**Comment by nielsjansendk** [comment]
This is the version of mssql server: 11.0.3128.0

**Comment by metaskills** [comment]
> result.each gives me:

For both calls? Or did the second one give you nil?

**Comment by nielsjansendk** [comment]
No, if I do it twice I get the same result both times.

**Comment by metaskills** [comment]
> No, if I do it twice I get the same result both times.

OK, You are going to have to find out why those result set is a multiple. I think it is important because if you do not figure that out then it will cause issues elsewhere. Like you could totally monkey patch your user options method to fix it... but the core issue could mess up other results. I would fire up SMS and see if DBCC USEROPTIONS returns multiple sets in the management studio and then go from there, like some Google searching. Let me know what you find out please.

**Comment by nielsjansendk** [comment]
I doesn't look like it returns multiple result sets in Management Studio.

**Comment by metaskills** [comment]
I wonder if home brew put something in a FreeTDS config or the way it was compiled to make this happen? I use a simple MacPorts install. Nothing special. But I suspect this could be a `1.00.21` bug. I could install that version later and try it.

**Comment by nielsjansendk** [comment]
My version is freetds v1.00.23. So yes, it could definitely be something like that. Or a homebrew thing.

**Comment by nielsjansendk** [comment]
The weirdness continues: I upgraded to rails 4, and used the compatible version of activerecord-sqlserver-adapter. Same Tinytds, same sql server, same freetds. This gives me no problems, and everything works.

**Comment by metaskills** [comment]
Whoa! Seems in 4-2-stable we have changed that method to account for this oddity. 

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/4-2-stable/lib/active_record/connection_adapters/sqlserver/database_statements.rb#L155-L168

Should have looked there first, sorry. I wonder if we should do the same for the `3-2-stable` branch and maybe each in between. I would be open to PRs for that.

**Comment by arbesulo** [comment]
I have fixed that problem, but I can't run the tests. Could anyone help me with that?

**Comment by metaskills** [comment]
I can help with the tests. I noticed this patch for user options first landed in 4-0-stable. I think we should patch it for 2-3-stable up to 3-2-stable.

**Comment by kride** [comment]
I'm facing same issue while upgrading from 4.2.3 to 5.0.1. `select_rows('dbcc useroptions')` returns the following
```
[[["textsize", "2147483647"], ["language", "us_english"], ["dateformat", "mdy"], ["datefirst", "7"], ["lock_timeout", "-1"], ["quoted_identifier", "SET"], ["ansi_null_dflt_on", "SET"], ["ansi_warnings", "SET"], ["ansi_padding", "SET"], ["ansi_nulls", "SET"], ["concat_null_yields_null", "SET"], ["isolation level", "read committed"]], []]
```
while on 4.2.3 it returns only the first array. Same database (SQL Server 2014), freetds (1.00.23) and tiny_tds (1.0.4, tried also with 1.10.0).

`@connection.execute('dbcc useroptions').each(as: :array)` returns same results on both versions.

**Comment by sangpark** [comment]
I see the same issue as kride, 

I just updated to use 5.0.1 and have freetds v1.00.24, SQL Server 2012, tiny_tds 1.1.0.

The result when I run @client.execute('dbcc useroptions').each(as: array) return

[[["textsize", "64512"], ["language", "us_english"], ["dateformat", "mdy"], ["datefirst", "7"], ["lock_timeout", "-1"], ["isolation level", "read committed"]], []]

**Comment by metaskills** [comment]
Just pushed v3.2.16, v4.2.17, and v5.0.3 with this change.

**Comment by nielsjansendk** [comment]
Doesn't look like 5.0.3 is on rubygems.org (latest version is 5.0.1).

**Comment by metaskills** [comment]
Up now!
