### ISSUE TITLE
Rails DDL (Migration DSL) for a unique ID

### ISSUE THREAD

**Issue by j-mcnally** [rails-sqlserver/activerecord-sqlserver-adapter#548]
So i am trying to create a UUID with the DB auto-creating the field.

I cannot figure out how to do this with the rails migration syntax and ended up creating the following migration:

```
class AddGuidToInvoices < ActiveRecord::Migration
  def up
    execute "ALTER TABLE [invoices] ADD [guid] uniqueidentifier DEFAULT NEWID() NOT NULL"
  end

  def down
    execute "ALTER TABLE [invoices] REMOVE [guid] uniqueidentifier DEFAULT NEWID() NOT NULL"
  end

end
```

Is there a simpler way to achieve this?

I tried a few things but could not get NEWID() as the default. Only the string "NEWID()". I tried a proc and a few other things.

**Comment by metaskills** [comment]
We test our Rails uuid type support. Here is the schema setup, model, and tests.

* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/schema/sqlserver_specific_schema.rb#L46-L50
* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/models/sqlserver/uuid.rb
* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/cases/uuid_test_sqlserver.rb

These test pass on both 4.2 as well as 5.0.

**Comment by metaskills** [comment]
@j-mcnally Did you ever figure out why the test and your usage were different?

**Comment by j-mcnally** [comment]
Sorry UUID works fine, the issue is around setting the default to NEWID()

I cant figure out how to set the default as a sql function it seems to just default to the string literal.

**Comment by j-mcnally** [comment]
its hard to change atm, but ill try to do another test later.

**Comment by metaskills** [comment]
OK, remember too, the links I posted show that we create a custom UUID column and default like so.

```ruby
  create_table 'sst_uuids', force: true, id: :uuid do |t|
    t.string :name
    t.uuid   :other_uuid, default: 'NEWID()'
    t.uuid   :uuid_nil_default, default: nil
  end
```

And the test show that it works as expected. Please examine this code and be clear on what is different and what you are expecting.

```ruby
  it 'can create other uuid column on reload' do
    obj = SSTestUuid.create!
    obj.reload
    obj.other_uuid.must_match acceptable_uuid
  end
```

**Comment by metaskills** [comment]
>  the issue is around setting the default to NEWID()

The code above under test does just that, can I close this issue out? Did you ever find out why your app is not working as expected? Maybe you have a gem installed that is breaking something?

**Comment by j-mcnally** [comment]
Sorry ill try to reproduce right now

**Comment by metaskills** [comment]
Feel free to reply and open anytime.

**Comment by j-mcnally** [comment]
I must just be dumb, i recently created a uuid field and it worked fine. thanks!
