### ISSUE TITLE
OFFSET issue

### ISSUE THREAD

**Issue by cyberbruce** [rails-sqlserver/activerecord-sqlserver-adapter#549]
I'm just getting started trying to use the new version of the gem..  Thank you so much for your hard work.   I've been using it with Rails 3 and 4 for quite some time.   I'm trying to upgrade one of our large applications, and I am getting this, when rails tries to check the db environment setting.. table exists, no rows in the table.    I'm sure I am doing something wrong, or have misconfigured something.  I would appreciate any guidance..

- Rails 5.0.1
- Sqlserver 2014
- using: freetds: stable 1.00.24
- prior migrations finish ok.

<details>
<summary>Stacktrace</summary>
<pre>
`ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [ar_internal_metadata].* FROM [ar_internal_metadata] WHERE [ar_internal_metadata].[key] = @0 OFFSET 0 ROWS FETCH NEXT @1 ROWS ONLY', N'@0 nvarchar(4000), @1 int', @0 = N'environment', @1 = 1
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:321:in `each'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:321:in `handle_to_names_and_values_dblib'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:311:in `handle_to_names_and_values'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:290:in `_raw_select'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:285:in `block in raw_select'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:285:in `raw_select'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:226:in `sp_executesql'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:19:in `exec_query'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:377:in `select_prepared'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:39:in `select_all'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/querying.rb:39:in `find_by_sql'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation.rb:702:in `exec_queries'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation.rb:583:in `load'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation.rb:260:in `records'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation/finder_methods.rb:527:in `find_take'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation/finder_methods.rb:100:in `take'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation/finder_methods.rb:78:in `find_by'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation.rb:237:in `find_or_initialize_by'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/querying.rb:6:in `find_or_initialize_by'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/internal_metadata.rb:22:in `[]='
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/migration.rb:1193:in `record_environment'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/migration.rb:1187:in `migrate_without_lock'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/migration.rb:1134:in `migrate'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/migration.rb:1006:in `up'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/migration.rb:984:in `migrate'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/Users/bmartin/projects/rails5/bin/rails:9:in `require'
/Users/bmartin/projects/rails5/bin/rails:9:in `<top (required)>'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
/Users/bmartin/projects/rails5/bin/spring:14:in `require'
/Users/bmartin/projects/rails5/bin/spring:14:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
TinyTds::Error: Incorrect syntax near 'OFFSET'.
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:321:in `each'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:321:in `handle_to_names_and_values_dblib'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:311:in `handle_to_names_and_values'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:290:in `_raw_select'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:285:in `block in raw_select'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:285:in `raw_select'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:226:in `sp_executesql'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:19:in `exec_query'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:377:in `select_prepared'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:39:in `select_all'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/querying.rb:39:in `find_by_sql'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation.rb:702:in `exec_queries'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation.rb:583:in `load'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation.rb:260:in `records'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation/finder_methods.rb:527:in `find_take'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation/finder_methods.rb:100:in `take'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation/finder_methods.rb:78:in `find_by'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/relation.rb:237:in `find_or_initialize_by'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/querying.rb:6:in `find_or_initialize_by'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/internal_metadata.rb:22:in `[]='
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/migration.rb:1193:in `record_environment'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/migration.rb:1187:in `migrate_without_lock'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/migration.rb:1134:in `migrate'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/migration.rb:1006:in `up'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/migration.rb:984:in `migrate'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/Users/bmartin/projects/rails5/bin/rails:9:in `require'
/Users/bmartin/projects/rails5/bin/rails:9:in `<top (required)>'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
/Users/bmartin/.rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
/Users/bmartin/projects/rails5/bin/spring:14:in `require'
/Users/bmartin/projects/rails5/bin/spring:14:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)`
<pre>
</details>

**Comment by cyberbruce** [comment]
using:  freetds: stable 1.00.24

**Comment by cyberbruce** [comment]
Sqlserver 2014

**Comment by metaskills** [comment]
FYI, I edited your comment using GitHub's sweet `<details>` support along with fenced code blocks. Makes reading it so much nicer :)

**Comment by metaskills** [comment]
So there is no order for this and that would be in Rails code. I think we should update our Arel visitor to use `TOP(1)` when any query has:

* Limit == 1
* Offset == [0, nil]
* No order

**Comment by cyberbruce** [comment]
Yes, this also affects my use of the composite-key gem.  belongs_to associations blow up..  unless I just add a default_scope and specify an order first.   Which I would prefer not to do, lol.

**Comment by metaskills** [comment]
Hmmm... so far all my tests are working. For example:

```ruby
ActiveRecord::InternalMetadata['environment']
=> "development"
```

And the SQL it generates is:

```sql
EXEC sp_executesql N'
  SELECT [ar_internal_metadata].[value] 
  FROM [ar_internal_metadata] 
  WHERE [ar_internal_metadata].[key] = @0', 
N'@0 nvarchar(4000)', 
@0 = N'environment'
```

**Comment by cyberbruce** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } I was getting a double bounded array.  I saw another post on that a while back.


Sent from Yahoo Mail for iPhone


On Wednesday, January 18, 2017, 5:25 PM, Ken Collins <notifications@github.com> wrote:


Hmmm... so far all my tests are working. For example:
ActiveRecord::InternalMetadata['environment']
=> "development"
And the SQL it generates is:
EXEC sp_executesql N'
  SELECT [ar_internal_metadata].[value] 
  FROM [ar_internal_metadata] 
  WHERE [ar_internal_metadata].[key] = @0', 
N'@0 nvarchar(4000)', 
@0 = N'environment'

**Comment by metaskills** [comment]
Please do investigate for me. So far I can not trigger this, even when I do `ActiveRecord::InternalMetadata['environment'] = 'test'` with a setter like your stack trace showed.

**Comment by cyberbruce** [comment]
ok, I will do some more checking tomorrow.  Thanks.

**Comment by cyberbruce** [comment]
## Oddness
Seems that if I used my system installed 1.0.24 version of **freetds** it fails, with another type of error.   So maybe my prior error was a red herring.  The error was relating to a double bounded array... when inspecting..
Error:
> NoMethodError: undefined method `gsub' for ["textsize", "2147483647"]:Array
<details>
activerecord-sqlserver-adapter-5.0.1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:141:in `block in user_options'
</details>

## Solution
So I built a fresh rails 5.0.1 app, installed just freetds gem and sqlserver gem, and it worked perfectly....??

Confused, I discovered that the app that was working was using freetds 1.0.21, from within the gems prebuild bins, not system libs.

To get my original app working:
- gem uninstall tiny_tds
- gem install tiny_tds -- --disable-system-freetds
  - this installed with gem based bins, which was **freetds ver 1.0.21**
- ran my tests, and **all was good**.

### Question:
- Could there be an incompatibility with freetds 1.0.24?

And of course.  Thank you guys!

**Comment by cyberbruce** [comment]
## Problem solved.. kinda... 
- Works perfectly until I add this **composite_primary_keys (9.0.6)**
Has a conflict with this gem.  This is when the OFFSET errors occur. 

> OFFSET Error

<details>ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [ar_internal_metadata].* FROM [ar_internal_metadata] WHERE [ar_internal_metadata].[key] = @0 OFFSET 0 ROWS FETCH NEXT @1 ROWS ONLY', N'@0 nvarchar(4000), @1 int', @0 = N'environment', @1 = 1
</details>

So I'm not sure if this is something you would want to address or the authors of the composite_primary_key gem.    

Thanks for responding so quickly.   - Have a great weekend.

**Comment by metaskills** [comment]
Oh yea... that gem has caused a few issues IIRC. No bad on them but supporting composite primary keys requires a fair amount of a) freedom patching rails and b) freedom patching adapters. Not an easy job.

**Comment by cyberbruce** [comment]
Yes, the gem has served us well.  I'm going to see if I can find a fix for it. :)

**Comment by metaskills** [comment]
@cyberbruce Going to close this issue. Please do keep the lines open if there is anything we can do here but I do think this is in the hands of the `composite_primary_keys` gem.
