### ISSUE TITLE
string contains null byte while seed

### ISSUE THREAD

**Issue by YossiCohen** [rails-sqlserver/activerecord-sqlserver-adapter#553]
Im changing the current sqlite DB to Sql-server on MS Azure cloude using the gems:
**activerecord-sqlserver-adapter** and **ruby-odbc**

There where little issues with the migrations that i've solved but now Im stucked with this 

rake aborted!
ActiveRecord::StatementInvalid: ArgumentError: string contains null byte: EXEC sp_executesql N'INSERT INTO [appealers] ([appealer_id], [first_name], [last_name], [created_at], [updated_at]) OUTPUT INSERTED.[id] VALUES (@0, @1, @2, @3, @4)', N'@0 nvarchar(4000), @1 nvarchar(4000), @2 nvarchar(4000), @3 datetime, @4 datetime', @0 = N'043167767', @1 = N'Dani', @2 = N'Shulman', @3 = N'01-24-%  10:29:29.717', @4 = N'01-24-%  10:29:29.717'
C:/**PATH**/seeds.rb:11:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
ArgumentError: string contains null byte
C:/**PATH**/seeds.rb:11:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

Process finished with exit code 1

Any help?

**Comment by metaskills** [comment]
The ruby-odbc support was removed from Rails v5 version and has not been supported/tested by us for a few years. Please use the latest TinyTDS which is the default connection mode instead.
