### ISSUE TITLE
Segmentation fault - SQL Server 2008

### ISSUE THREAD

**Issue by Littlejd1997** [rails-sqlserver/activerecord-sqlserver-adapter#554]
We are using this sqlserver adapter (4.1.4) to communicate with a SQL Server 2008 database. We are using rails 4.1 and ruby 2.3.1. It is running with puma and nginx. Randomly, nginx would error out with a 502, and the rails error log would be empty. Digging into the puma stderr log revealed a Segmentation Fault with this gem. I am pretty baffled to what is causing it, and any insight would be awesome.
I have attached the stderr log below
[stderr.txt](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/files/728060/-.txt)

**Comment by Littlejd1997** [comment]
After hours of debugging, I think it might be related to the connection pool size. It was only 5 and we had up to 64 threads. If that was the issue, the segmentation fault is a very horrible error. Something more robust would be better

**Comment by metaskills** [comment]
Have you read this article? I am not an expert in this area but it does seem to suggest a tighter coupling to thread size and pool size. Latest 5.x default puma config in new rails projects backs that up. 

https://devcenter.heroku.com/articles/concurrency-and-database-connections

> the segmentation fault is a very horrible error. Something more robust would be better

The ActiveRecord docs seem to suggest you should have gotten something like a `ActiveRecord::ConnectionTimeoutError` with a helpful message. Can you investigate why that did not happen?

**Comment by Littlejd1997** [comment]
I did get that occasionally, but I also got segmentation faults, which were very no bueno

**Comment by metaskills** [comment]
Thanks. Have you found anything in here or TinyTDS to suggest that is a problem with either?

**Comment by Littlejd1997** [comment]
I'm feeling good that it was an issue with the pool size. Its been running for an hour with no segmentation faults (admittedly not as much load either at night). I'll keep this ticket open and report back

**Comment by Littlejd1997** [comment]
Well, that didn't hold up. Got another segmentation fault, but this one is different.

[Segmentation Fault](http://pastebin.com/ynuJ557y)

**Comment by metaskills** [comment]
What version of FreeTDS are you using and how did you install it?

**Comment by Littlejd1997** [comment]
Uhhhhhhh, that is an excellent question. As far as I know, its just the `tiny_tds` gem...

**Comment by metaskills** [comment]
One thing we want to change WRT TinyTDS is how it uses Miniportile to install a local static FreeTDS when it can not be found on the system. This system was only meant to be used for building static Windows gems. These CI scripts are how we install OpenSSL and FreeTDS on the Ubuntu (trusty) boxes for both Travis and Circle.

* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/bin/install-openssl.sh
* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/bin/install-freetds.sh

Your mileage may vary, but using the latest versions is advised which these do. Note, these scripts were my first experience installing things like this on Ubuntu. Be kind :)

**Comment by Littlejd1997** [comment]
Freetds is compiling now. Will I need to do anything to relink it or something?

**Comment by Littlejd1997** [comment]
I compiled openssl and freetds, reinstalled the tiny_tds gem using the `-with-freetds-include=/opt/local/include -with-freetds-lib=/opt/local/lib/` flags.  Then I flooded the server with requests and another segmentation fault. It definitely is an issue under load

http://pastebin.com/k0V30Ge4

**Comment by Littlejd1997** [comment]
As a temporary measure, I added lots of nginx caching to help reduce the impact of these segmentation faults, but eliminating them would be ideal

**Comment by metaskills** [comment]
I'd love to help with the segmentation faults. Could you supply a Rails repo with a test script to reproduce? I'd like to test on Darwin and a few other platforms to see if this happens all over the place.

**Comment by Littlejd1997** [comment]
For what it's worth, this issue has not been resolved, due to the severity of the issues, we very quickly moved to a Java jdbc solution.

**Comment by metaskills** [comment]
That's fine... but I need a test case to reproduce it. FYI, TinyTDS recently moved to OpenSSL v1.1.0 for the Windows builds and we test the same for Ubuntu too. Not sure where you issue was and what factors were at play in your env... but I do need your help with solving it. If you find the time, please do reply back here.
