### ISSUE TITLE
eager loading is using joins instead of one fetch/table

### ISSUE THREAD

**Issue by kwerle** [rails-sqlserver/activerecord-sqlserver-adapter#555]
It looks like the new adapter (or rails 5) is using joins instead of one fetch per table for eager loading.  This is destroying my app performance and is a showstopper for updating.

Is this an adapter choice or a change in rails 5?  Is there a way to get the old behavior back?

**Comment by metaskills** [comment]
This would almost certainly be Rails core. Can you investigate and provide more details on:

* Is and where is Rails doing this? Where and when did this change?
* Have there been an issues on rails/rails around this topic? Maybe in PR or issues?

This would give us context on the ability to communicate. I would recommend stating by search rails/rails issues. Then doing a search in the code to find out if when this changed and providing links to PRs and related issues. Cool?

**Comment by kwerle** [comment]
Yeah, I've been digging around and have not come up with anything, yet.  That's why I posted here hoping it was an adapter choice.  I will continue digging.

**Comment by kwerle** [comment]
OK - this is something weird in rails.  I can't put together a minimal test case, but it has something to do with creating an ActiveRecord_Relation and then maybe using it and then maybe using it again to find children.
```
my_query = Parent.where(something: :or_other)
my_query.first
my_query.children.includes(:more, :stuff)

```
Not a sql server adapter issue, I don't think.
I can work around it by changing the last line to something like
`Child.where(parent_id: my_query.ids).includes(:more, :stuff)`

**Comment by metaskills** [comment]
Thanks for following up.
