### ISSUE TITLE
Login Timeout in ms or secs?

### ISSUE THREAD

**Issue by Insood** [rails-sqlserver/activerecord-sqlserver-adapter#556]
Hello,

I have a rails app and I'm puzzling over whether login_timeout for establish_connection is given in ms or secs.

The [code](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/3a68ac378ed03aaf3a761ef01f8622810b005f75/lib/active_record/connection_adapters/sqlserver_adapter.rb#L389) for config_login_timeout & config_timeout says: 

```
      def config_login_timeout(config)
        config[:login_timeout].present? ? config[:login_timeout].to_i : nil
      end

      def config_timeout(config)
        config[:timeout].present? ? config[:timeout].to_i / 1000 : nil
      end
```

Am I correct in writing code like this if I want timeout and login_timeout to both be 5000ms?

```
class ChargeBase < ActiveRecord::Base
		establish_connection(
		adapter: "sqlserver",
		host: ,
		username: ,
		password: ,
		database: ,
		login_timeout: 5,
		timeout:  5000
	)
	self.abstract_class = true
end
```

**Comment by metaskills** [comment]
Both `timeout` and `login_timeout` within TinyTds are supposed to be in seconds. However, only `timeout` is a database connection option convention across all adapters. To that end, Rails supports `milliseconds` for that option. This is why you see a difference and yes it can be confusing. But we thought it was more important to promote a consistent interface when it comes to DB options that are DB agnostic. Hope that makes sense.
