### ISSUE TITLE
Unable to get value for columns with "date" as datatype

### ISSUE THREAD

**Issue by Litty203** [rails-sqlserver/activerecord-sqlserver-adapter#557]
I have a table which has two columns. One stores date (data type given is date), another stores time (data type given is datetime). 
I get the value for date column as nil even if there is a valid date, and some cases the date is returned as "2017-01-1" incorrectly for a date of 2017-01-11. The second digit in date digit gets truncated.
However, the values returned by datetime column is exactly the same as in database.

Please help.

**Comment by metaskills** [comment]
What version of Rails/Adapter are you using?

**Comment by Litty203** [comment]
Rails Version - 4.2.5.1
activerecord-sqlserver-adapter gem version is 4.2.10

**Comment by metaskills** [comment]
Thanks, what version of FreeTDS is TinyTDS compiled against? Also, what version of TinyTDS. My initial guess is one of two things. Either your FreeTDS is low enough that TDSVER 7.3 is not set for you automatically and/or an issue with the date/time formats coming from your connection. Knowing the SQL Server version will help there too. Lemme know what you got/findout.

**Comment by Litty203** [comment]
TinyTDS version 1.0.5 x86-mingw32
SQL Server Version is 2012
Forgot to mention the application is hosted on Windows. So I do not remember installing FreeTDS separately.

**Comment by metaskills** [comment]
> Forgot to mention the application is hosted on Windows. So I do not remember installing FreeTDS separately.

Cool, that means you got FreeTDS statically compiled into the Windows gem. So you did not have to build it yourself. It [seems that version](https://github.com/rails-sqlserver/tiny_tds/blob/master/CHANGELOG#L12) used FreeTDS v1.00.15 which [does support](https://github.com/rails-sqlserver/tiny_tds#data-types) the `date` data type. The TDSVER should default to 7.3, but have you tried adding this to your database.yml to make sure?

```yaml
tds_version: "7.3"
```

**Comment by Litty203** [comment]
Tried it. Its still the behaving the same.

**Comment by metaskills** [comment]
Thanks @Litty203 what is your default language after you connect? In console:

```ruby
ActiveRecord::Base.connection.select_value("SELECT @@language")
```

After that can you tell me what are your date formats set to in a Rails console.

```ruby
ActiveRecord::Base.connection # make sure to run this to initialize connection
```

Now show me your output for these:

```format
Date::DATE_FORMATS[:_sqlserver_dateformat]
Time::DATE_FORMATS[:_sqlserver_dateformat]
Time::DATE_FORMATS[:_sqlserver_time]
Time::DATE_FORMATS[:_sqlserver_datetime]
```

Mine are as follows and I suspect yours are different?

* "%m-%d-%Y"
* "%m-%d-%Y"
* "%H:%M:%S"
* "%m-%d-%Y %H:%M:%S"

**Comment by Litty203** [comment]
Hi @metaskills 

I got the same formats for - 

Date::DATE_FORMATS[:_sqlserver_dateformat]
Time::DATE_FORMATS[:_sqlserver_dateformat]
Time::DATE_FORMATS[:_sqlserver_time]
Time::DATE_FORMATS[:_sqlserver_datetime]

which are as follows - 

- "%m-%d-%Y"
- "%m-%d-%Y"
- "%H:%M:%S"
- "%m-%d-%Y %H:%M:%S"

I got an error for this  - 
ActiveRecord::Base.connection.select_value("SELECT @@language")

`Procedure expects parameter '@statement' of type 'ntext/nchar/nvarchar'.: EXEC sp_executesql 'SELECT @@language'`

**Comment by metaskills** [comment]
@Litty203 Thanks... happy to see the date/time formats looking good. However, kind of freaked out about that language query. I don't have a local copy of 2012 readily available, but I could yank one from backup. Would you mind doing a bit of investigation into how to select your language format and why that error happened? Then let me know the value?

Meanwhile, I will make efforts to pull 2012 from my backups. But FYI, we do test `SQL2012SP1` on Appveyor and the tests are all green. So I am assuming the same would be true for me. Hence why I think looking into why your specific server/setup is different is the key to solving your issue.

**Comment by Litty203** [comment]
@metaskills , I tried getting the language format directly by running `SELECT @@language` in SQL and got `us_english`.
However this query is not working from rails console, not sure why.

**Comment by metaskills** [comment]
Thanks for the report on `us_english`. 

> However this query is not working from rails console, not sure why.

Stuff like this should not be ignored. There is some reason your server is acting differently then  other 2012 servers. Not saying that `@@language`select is 100% related. But it could be a clue - something is different on your machine and I think that difference is lower down than the date/time formats and is keeping SQL statements for them from working as expected. Can you investigate into why that might be?
