### ISSUE TITLE
native_text_database_type and native_string_database_type options don't work the same

### ISSUE THREAD

**Issue by BenKanouse** [rails-sqlserver/activerecord-sqlserver-adapter#562]
It looks to me that native_string_database_type works correctly but native_text_database_type only actually sets a value if enable_default_unicode_types is also set. I would think we would want both options to work the same.

It looks like someone just forgot the parentheses inside of the text method. I have a tested fix here: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/561

I think this is just an issue with 4.0

**Comment by metaskills** [comment]
Thanks! I have pushed new versions into 4-0-stable and 4-1-stable because it affected both. New gems versions are:

* 4.0.3
* 4.1.6

Hope that helps.
