### ISSUE TITLE
Support Subscriptions

### ISSUE THREAD

**Issue by thomasfedb** [rails-sqlserver/activerecord-sqlserver-adapter#563]
Hey @metaskills,

Are you at all interested in offering support subscripts for this project? Would doing so give you more time to work on the project?

This gem is critical to a number of my commercial projects, and I'd be very happy to sign up for paid email support. I wonder how many others feel the same.

Cheers,
Thomas

**Comment by metaskills** [comment]
Hey @thomasfedb I'd love any help. Would you mind explaining subscript support to me? I googled it and only saw this post http://sqlblog.com/blogs/john_paul_cook/archive/2011/10/30/superscripts-subscripts-special-characters-and-unicode.aspx

So I wrote a quick test with the scratchpad test.

```diff
--- a/test/cases/scratchpad_test_sqlserver.rb
+++ b/test/cases/scratchpad_test_sqlserver.rb
@@ -2,8 +2,15 @@ require 'cases/helper_sqlserver'

 class ScratchpadTestSQLServer < ActiveRecord::TestCase

-  it 'helps debug things' do
-    #
+  it 'sub and super script' do
+    value = "H2O 100°"
+    object = SSTestDatatypeMigration.new
+    object.string_col = value
+    object.string_col.must_equal value
+    object.save!
+    object.string_col.must_equal value
+    object.reload
+    object.string_col.must_equal value
   end
```

I then ran the tests and everything was great. 

```
$ bundle exec rake test ONLY_SQLSERVER=1 TESTOPTS="-n=/ScratchpadTestSQLServer/"
Using dblib
Run options: -n=/ScratchpadTestSQLServer/ --seed 61993

# Running:

.

Finished in 0.077261s, 12.9431 runs/s, 38.8294 assertions/s.
```

**Comment by thomasfedb** [comment]
Hey @metaskills. I meant subscriptions, in terms of a mechanism for paying you for supporting this gem.

**Comment by metaskills** [comment]
Oh my! 😊 I am honored. I've never considered such a thing. Do you have any advice on how that is setup?

**Comment by thomasfedb** [comment]
Have a look at what Sidekiq do, that's pretty cool. But ultimately it has to be fee in exchange for some sort of product (extra features, or better access for support) in order for businesses to pay. Most software companies don't let their engineers make donations.

**Comment by metaskills** [comment]
Thanks so much for talking about this with me. I don't think the Sidekiq model is a right fit for the adapter. Love how successfully it has been Mike tho. I looked around and added a Gratipay badge to the README. Cheers.

**Comment by thomasfedb** [comment]
Great!

**Comment by thomasfedb** [comment]
So i tried to use Gratipay but couldn't work it! I could donate to other projects, but not to this one! Is it configured correctly?

**Comment by metaskills** [comment]
Maybe it needed a PayPal setup? Feels weird to say... but try now?
