### ISSUE TITLE
How to build an execute {} migration for an old stored procedure change?

### ISSUE THREAD

**Issue by joshuairl** [rails-sqlserver/activerecord-sqlserver-adapter#564]
Currently I'm running into an issue where doing this is causing TinyTds syntax errors.
I'm wanting to make sure I'm not missing something or I'm not doing anything wrong.

`ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near 'GO'.:`

```ruby
class MakeChangeToStoredProc < ActiveRecord::Migration[5.0]
  def change
   execute %{
               USE [database_name]
		GO
		SET ANSI_NULLS ON
		GO
		SET QUOTED_IDENTIFIER ON
		GO
		ALTER PROCEDURE [dbo].[table_name](@valueList varchar(8000),@system varchar(200),@datetime varchar(200))
		  AS

		DECLARE @sumAmount varchar(100)
		DECLARE @pos INT
		DECLARE @len INT
		DECLARE @value varchar(8000)
		DECLARE @abc DECIMAL

                  ... etc. etc.
    }
  end
end
```

Sorry if this isn't the right place to put this...

**Comment by metaskills** [comment]
> The GO command isn't a Transact-SQL statement, but a special command recognized by several MS utilities including SQL Server Management Studio code editor. The GO command is used to group SQL commands into batches which are sent to the server together.Feb 19, 2010

So essentially, they are not needed and need to be removed for TinyTDS which relies on TSQL. Hope that helps.
