### ISSUE TITLE
SQL Server 2012 TinyTds::Error: Incorrect syntax near 'OFFSET'

### ISSUE THREAD

**Issue by pinak1180** [rails-sqlserver/activerecord-sqlserver-adapter#567]
I'm using rails 5.0.1 with activerecord-sqlserver-adapter 5.0.4, tiny_tds 1.1.0, SQL Server 2012.

`ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [CATALOG_MASTER].* FROM [CATALOG_MASTER] WHERE [CATALOG_MASTER].[instit_div_cde] = @0 OFFSET 0 ROWS FETCH NEXT @1 ROWS ONLY', N'@0 char(2), @1 int', @0 = 'CS', @1 = 1
`

and I have one ActiveRecord relation like

`has_one :ex_catalog,
          class_name: 'Ex::Catalog',
          primary_key: 'institut_div_cde',
          foreign_key: 'instit_div_cde'`

when I try to some_object.ex_catalog it fires above error, but when i add order to my association and query .last it works.

Can somebody help?

**Comment by metaskills** [comment]
Perhaps the `Ex::Catalog` does not see its primary key? What does `Ex::Catalog.primary_key` show? Was this set manually in the model?

**Comment by pinak1180** [comment]
@metaskills  yes, it do have 

`Ex::Catalog.primary_key
 => "appid" 
`

but it still gives  

`ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [CATALOG_MASTER].* FROM [CATALOG_MASTER] WHERE [CATALOG_MASTER].[instit_div_cde] = @0 OFFSET 0 ROWS FETCH NEXT @1 ROWS ONLY', N'@0 char(2), @1 int', @0 = 'CS', @1 = 1
`

**Comment by metaskills** [comment]
Are you using the Composite Primary Key gem?

**Comment by pinak1180** [comment]
@metaskills  yes, i forgot to mention that.

**Comment by metaskills** [comment]
That is the issue. It monkey patches things form ActiveRecord to each adapter which means this is their issue. You can search our previous issues for more details.

**Comment by pinak1180** [comment]
@metaskills yes it was their issue, thanks for your prompt support and   anyone else facing the same issue and using composite primary key gem, I fixed it in my [fork](https://github.com/pinak1180/composite_primary_keys)
