### ISSUE TITLE
another OFFSET issue

### ISSUE THREAD

**Issue by gswartz777** [rails-sqlserver/activerecord-sqlserver-adapter#569]
I'm using rails 5.0.0, tinytds 1.1.0, activerecord-sqlserver-adapter 5.0.5, sql server 2014

The error I get is...
```
CompanyPermission Load (310.0ms)  EXEC sp_executesql N'SELECT  [CompanyPermission].* FROM [CompanyPermission] WHERE [CompanyPermission].[CompanyID] = @0  ORDER BY [CompanyPermission].[CompanyID] ASC OFFSET 0 ROWS FETCH NEXT @1 ROWS ONLY', N'@0 int, @1 int', @0 = NULL, @1 = 1  [["CompanyID", nil], ["LIMIT", 1]]
Completed 500 Internal Server Error in 1175ms (ActiveRecord: 629.9ms)


DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from initialize at /Users/user/.rvm/gems/ruby-2.3.3/gems/better_errors-2.1.1/lib/better_errors/raised_exception.rb:7)
DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from initialize at /Users/user/.rvm/gems/ruby-2.3.3/gems/better_errors-2.1.1/lib/better_errors/raised_exception.rb:8)

TinyTds::Error - Incorrect syntax near 'OFFSET'.:
```

This happens in this code block in the companies_controller.
```
unless @company.company_permission.nil? <-- this line
      @available_posting_count = @company.company_permission.JobAdNumLeft
end
```

I'm not very well versed in ruby/rails but this appears to be one of the last issues I'm having upgrading this from rails 4.1.1/ruby 2.1.2  I looked through the other OFFSET issues but didn't see anything that seemed to relate to my situation.  I'm not using the composite_primary_keys gem.

**Comment by metaskills** [comment]
Are you using the Composite Primary Key gem?

**Comment by metaskills** [comment]
Sorry, I read that last line, you are NOT using that gem. What is the output from each of these lines?

```ruby
CompanyPermission.primary_key # => ?
CompanyPermission.columns # => ?
```

**Comment by gswartz777** [comment]
CompanyPermission.primary_key returns CompanyID
CompanyPermission.columns returns the following
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad51a7fe80>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad51a774d8>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad51a76038>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad51a6d708>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad51a67650>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad51a64608>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad51a5e0f0>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad51a5c638>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad4bcdac58>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad4bcd8a98>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad4bcd2fd0>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad4bcd1888>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad4bccb528>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad4bcc22c0>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad4bcba368>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad51a55518>
#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fad51a54488>

**Comment by gswartz777** [comment]
I realized that we have switched how we record permissions for companies and that the code that originally started this issue was out of date anyway.  I updated it to look at another table and it's working now.  

However, I still have the NoMethodError - undefined method `relation_delegate_class' for ActiveJob:Module: error happening.  As I said before the line above it which loads the orders for a company does work for me.  At first I wondered if it was because orders actually returned data but the view for active jobs didn't return anything.  So I then hooked it up to another record that returned data for both... but still I get the error.  Is it potentially an issue with the data being returned in a view rather than a table?  The orders (the one that works) is a regular table while the active_jobs is a view.  Thanks.

**Comment by gswartz777** [comment]
I'm also getting the OFFSET error now on another model that has no relation to any other.  It's just a simple table in the sql server database defined below...

```
class ApiKey < ApplicationRecord
  establish_connection :db
  self.table_name = "ValidateKey"
end
```

The rails error is

```
ApiKey Load (54.7ms)  EXEC sp_executesql N'SELECT  [ValidateKey].* FROM [ValidateKey]  ORDER BY [ValidateKey].[Key] ASC OFFSET 0 ROWS FETCH NEXT @0 ROWS ONLY', N'@0 int', @0 = 1  [["LIMIT", 1]]
Completed 500 Internal Server Error in 2436ms (ActiveRecord: 1469.7ms)

TinyTds::Error - Incorrect syntax near 'OFFSET'.:
```

And this is being called in the controller as such...
`
@api_key = ApiKey.first["Key"]`

**Comment by metaskills** [comment]
> CompanyPermission.primary_key returns CompanyID
> CompanyPermission.columns returns the following

Thanks, but that output is not helpful. It does not look like the output from IRB and is missing a lot of info. I wanted to see the SQL Types and other info in the full column objects.

> A bit more info - this was working fine

This is helpful. First, thought not directly related, you should really create an abstract class that champions the connection. By doing `establish_connection` multiple times you are creating distinct connection pools and hence transactions are not going to be shared. Please see Topic 1 on this post for more details. http://technology.customink.com/blog/2015/06/22/rails-multi-database-best-practices-roundup/

* Why do I not see a `self.primary_key = 'CompanyID` in the `CompanyPermission` model?
* Why does the `CompanyPermission#company` association have to use `external_id` vs the default `CompanyID` that the model? Doesn't that imply that both are the same?
* Have you explored the fact that your `ActiveJob` class is conflicting with Rails v5's new ActiveJob module/behavior? https://github.com/rails/rails/blob/5-0-stable/activejob/lib/active_job.rb

**Comment by gswartz777** [comment]
Sorry, as I initially said I'm not well versed in ruby/rails so a lot of this is learning as I go.  Here's the IRB output for the CompanyPermission model.

```
CompanyPermission.primary_key => 
CompanyPermission.columns =>  => [#<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad672c48 @sqlserver_options={:ordinal_position=>1, :is_primary=>true, :is_identity=>false}, @name="CompanyID", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad672e00 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>1, :is_primary=>true, :is_identity=>false}}, @sql_type="int(4)", @type=:integer, @limit=4, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad671f50 @sqlserver_options={:ordinal_position=>2, :is_primary=>false, :is_identity=>false}, @name="JobAdNumLeft", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad6720e0 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>2, :is_primary=>false, :is_identity=>false}}, @sql_type="smallint(2)", @type=:integer, @limit=2, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad671c08 @sqlserver_options={:ordinal_position=>3, :is_primary=>false, :is_identity=>false}, @name="StaffingJobAdNumLeft", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad671d98 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>3, :is_primary=>false, :is_identity=>false}}, @sql_type="smallint(2)", @type=:integer, @limit=2, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad671118 @sqlserver_options={:ordinal_position=>4, :is_primary=>false, :is_identity=>false}, @name="JobAdEndDate", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad6712a8 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>4, :is_primary=>false, :is_identity=>false}}, @sql_type="smalldatetime", @type=:smalldatetime, @limit=nil, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad670dd0 @sqlserver_options={:ordinal_position=>5, :is_primary=>false, :is_identity=>false}, @name="StaffingJobAdEndDate", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad670f60 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>5, :is_primary=>false, :is_identity=>false}}, @sql_type="smalldatetime", @type=:smalldatetime, @limit=nil, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad6702e0 @sqlserver_options={:ordinal_position=>6, :is_primary=>false, :is_identity=>false}, @name="JobAdUnlimited", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad670470 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>6, :is_primary=>false, :is_identity=>false}}, @sql_type="bit", @type=:boolean, @limit=nil, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9a6b1fd60 @sqlserver_options={:ordinal_position=>7, :is_primary=>false, :is_identity=>false}, @name="StaffingJobAdUnlimited", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad670128 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>7, :is_primary=>false, :is_identity=>false}}, @sql_type="bit", @type=:boolean, @limit=nil, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9a6b1d358 @sqlserver_options={:ordinal_position=>8, :is_primary=>false, :is_identity=>false}, @name="SearchDaysLeft", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9a6b1dfb0 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>8, :is_primary=>false, :is_identity=>false}}, @sql_type="smallint(2)", @type=:integer, @limit=2, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9a6b1c0c0 @sqlserver_options={:ordinal_position=>9, :is_primary=>false, :is_identity=>false}, @name="LastSearchDate", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9a6b1ca20 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>9, :is_primary=>false, :is_identity=>false}}, @sql_type="smalldatetime", @type=:smalldatetime, @limit=nil, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad67bcd0 @sqlserver_options={:ordinal_position=>10, :is_primary=>false, :is_identity=>false}, @name="SearchEndDate", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad67be60 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>10, :is_primary=>false, :is_identity=>false}}, @sql_type="smalldatetime", @type=:smalldatetime, @limit=nil, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad67b988 @sqlserver_options={:ordinal_position=>11, :is_primary=>false, :is_identity=>false}, @name="SearchUnlimited", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad67bb18 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>11, :is_primary=>false, :is_identity=>false}}, @sql_type="bit", @type=:boolean, @limit=nil, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad67b640 @sqlserver_options={:ordinal_position=>12, :is_primary=>false, :is_identity=>false}, @name="LastModified", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad67b7d0 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>12, :is_primary=>false, :is_identity=>false}}, @sql_type="smalldatetime", @type=:smalldatetime, @limit=nil, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad67b2f8 @sqlserver_options={:ordinal_position=>13, :is_primary=>false, :is_identity=>false}, @name="MarketMaximizer", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad67b488 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>13, :is_primary=>false, :is_identity=>false}}, @sql_type="smallint(2)", @type=:integer, @limit=2, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad67a5d8 @sqlserver_options={:ordinal_position=>14, :is_primary=>false, :is_identity=>false}, @name="AdditionalSiteIds", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad67a768 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>14, :is_primary=>false, :is_identity=>false}}, @sql_type="varchar(50)", @type=:varchar, @limit=50, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation="SQL_Latin1_General_CP1_CI_AS", @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad679b10 @sqlserver_options={:ordinal_position=>15, :is_primary=>false, :is_identity=>false}, @name="msrepl_synctran_ts", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad679ca0 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>15, :is_primary=>false, :is_identity=>false}}, @sql_type="timestamp", @type=:ss_timestamp, @limit=nil, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad678e18 @sqlserver_options={:ordinal_position=>16, :is_primary=>false, :is_identity=>false}, @name="CompanyProfileTypeId", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad678fa8 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>16, :is_primary=>false, :is_identity=>false}}, @sql_type="tinyint(1)", @type=:integer, @limit=1, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, #<ActiveRecord::ConnectionAdapters::SQLServerColumn:0x007fc9ad678ad0 @sqlserver_options={:ordinal_position=>17, :is_primary=>false, :is_identity=>false}, @name="CompanyProfileExpireDate", @table_name="CompanyPermission", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata:0x007fc9ad678c60 @sqlserver_options={:sqlserver_options=>{:ordinal_position=>17, :is_primary=>false, :is_identity=>false}}, @sql_type="smalldatetime", @type=:smalldatetime, @limit=nil, @precision=nil, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>]
```

To answer your other questions the CompanyPermission model is a sql server table which belongs_to a rails mysql model called Company.  The sql server table has CompanyID as the primary key and on the msyql Company table, the foreign key to connect the two is external_id.    
That's what this line is saying (I think:)

  `belongs_to :company, foreign_key: "CompanyID", :primary_key => 'external_id'`

Is that set up incorrectly?  As for the ActiveJob, again I have to plead ignorance but thanks!  I had no idea about that.  Do you have any idea about my last comment for the ApiKey?  That table in sql server simply has a single varchar(max) field in it so there is no primary key.  Would I have to create a primary key for this to work?  Thanks for the help!

**Comment by metaskills** [comment]
> To answer your other questions the CompanyPermission model is a sql server table which belongs_to a rails mysql model called Company. 

Ah! That info would have been helpful up front :) I think what you are suffering from is the way we have architected our Arel visitor where it is not able to get the primary key of the table to "make offset & fetch happen". If true, then the best way to work around this for you multi-DB setup is to add a default order to the association. 

> Do you have any idea about my last comment for the ApiKey? That table in sql server simply has a single varchar(max) field in it so there is no primary key. 
> Would I have to create a primary key for this to work?

No, but it does mean you would have to query it differently for it to work. The `first` method requires an order and that default order needs a key, to which you have none. That simple table setup reminds me of how ActiveRecord stores [internal meta data](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/internal_metadata.rb like migration numbers. In short, use something like `ApiKey.where(Key: key).pluck(:Key)`

**Comment by gswartz777** [comment]
Thank you again for the help.  I added an id field to my ApiKey table and a default order to it but still get the OFFSET error.

class ApiKey < ApplicationRecord
  establish_connection :db
  self.table_name = "ValidateKey"
  self.primary_key = "id"
  default_scope { order(id: :desc) }
end

**Comment by metaskills** [comment]
Can you be specific about the offset error WRT to ApiKey and code you are calling?

**Comment by gswartz777** [comment]
Well I'm not sure what happened but now it's all working and I'm not able to reproduce the error.

**Comment by metaskills** [comment]
@gswartz777 Glad things worked out for you. If anything changes or you have more questions, here to help if I can. Cheers!
