### ISSUE TITLE
bigint primary key support.

### ISSUE THREAD

**Issue by jun85664396** [rails-sqlserver/activerecord-sqlserver-adapter#578]
I want to a primary key of type Bigint.

However, the primary key is fixed as an int.(https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/active_record/connection_adapters/sqlserver/schema_statements.rb#L255)

planning to support a bigint type of primary key?

**Comment by metaskills** [comment]
Yes, in Rails 5.1 when I start work on that in a few days. It is already in my 5.1 TODO list. Supporting that in 5.1 allows us to conform to the reverse schema ruby format. If needed for lower versions, please use raw SQL in your migrations. https://github.com/rails/rails/pull/26266
