### ISSUE TITLE
Support JRuby w/JDBC Connection Mode

### ISSUE THREAD

**Issue by iaddict** [rails-sqlserver/activerecord-sqlserver-adapter#579]
I read in the documentation that this gem has "no strict gem dependencies outside of ActiveRecord".
But the gemspec lists tiny_tds as a dependency.

Would it be possible to remove this dependency?

**Comment by iaddict** [comment]
Some background: I started to modify activerecord-sqlserver-adapter to also support sequel (aka the sequel gem) as a connection mode. With this it's possible to use it with jruby and a jdbc connection. A basic jruby on rails application with some crud actions already works just fine.

I found that this would be an alternative to activerecord-jdbcmssql-adapter which as of now has no support for ActiveRecord 5 and also has several sql issues which are unfixed for quite a while.

Would you be interested in a pull request?

**Comment by metaskills** [comment]
Some history, the adapter for a long time supported 2 and something 3 connection modes. The legacy ODBC mode has never been tested or supported for at least 3 years. So [it was removed](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/502/commits/5e35c779ad8daf1cd95ff41d44c704c8afde0a82) in Rails v5. Before then, I heavily advocated that this adapter could be a rally point for talking to SQL Server from any raw connection as long as we took the high road of using TSQL for everything (can go into that more if needed). During that time I even added IronRuby support. I even created tickets to [reach out to jruby/jdbc](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/106) that were unfruitful. 

A few weeks ago I created (and closed) [a rails-core issue](https://github.com/rails/rails/pull/28115) as part of a series of making getting started with SQL Server vNext/Linux super easy using Rails generators database option. Because we only have one connection mode (and a small constraint in Rails) it was an easy decision to make TinyTDS a dependency. The goal being to allow SUPER EASY setup for those getting started with Ruby/Rails and SQL Server. In a few weeks, we will have Ruby/Rails added to the Microsoft [SQL Server Getting Started](https://www.microsoft.com/en-us/sql-server/developer-get-started/) page and the directions now avoid the "now add TinyTDS to your gem file steps" which is kind of cool.

Where do we go from here? I still believe this adapter would be stronger with more backends and we had a unified approach to talking to SQL Server via ActiveRecord. Part of me thinks that it would take seeing that come to fruition first would be needed to think about removing the dep now on TinyTDS. That trip would not be easy because there may be differences of how to do things for each connection mode that might make this code base quite complex, CI setup, etc. Can you read over this and the links and tell me what you think?

**Comment by iaddict** [comment]
Many thanks for your detailed explanation and thoughts!

Maybe we can keep the dependency on the tiny_tds gem and supply a platform dependent tiny_tds gem for java/jruby. Actually that's what I did. If you bundle with jruby this platform gem is automatically chosen, eg. tiny_tds-0.1.0-java.gem.

My implementation of this gem has almost no code. It just checks if sequel can be required and gives some hints if this is not possible.

What do you think about this approach?

**Comment by metaskills** [comment]
It sounds hot! Mind sharing some code/prs now?

**Comment by iaddict** [comment]
Ok. Here we go:

https://github.com/iaddict/tiny_tds-java
https://github.com/iaddict/activerecord-sqlserver-adapter/tree/sequel-mode

I ran the tests with `jruby -S bundle exec rake test:sequel` on a SQL-Server 2016 which currently finishes with at least some success:
```
221 runs, 847 assertions, 7 failures, 20 errors, 5 skips
```

Some of the failing tests are related to permission denied errors (I'm not the sysadmin of this server).

To make bundle install succeed, you first need to build and install the tiny_tds-java gem:
```sh
jruby -S gem build tiny_tds-java.gemspec
jruby -S gem install tiny_tds-0.1.0-java.gem
```

**Comment by metaskills** [comment]
> Some of the failing tests are related to permission denied errors (I'm not the sysadmin of this server).

Why not use the Docker image for SQL Server that our CI uses? I do the same.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/bin/setup.sh

> https://github.com/iaddict/activerecord-sqlserver-adapter/tree/sequel-mode

Couldnt we use `Jdbc` vis the `Sequel` so the real raw connection is right to the metal? What is the thinking behind use the Sequel's wrapper?

**Comment by iaddict** [comment]
Sorry for the late answer.
Anyway – there is some progress with the sequel mode. The tests already look a lot more promising:
```
222 runs, 1126 assertions, 1 failures, 0 errors, 9 skips
```

The sequel gem already does a lot of the stuff that would have to be implemented a second time, like the type casts, connection pooling, reconnection handling, ...
I think - at least for now - it is much easier to stand on the shoulders of giants ;)

Maybe you can take a brief look at the commits and tell me if you think the route taken is ok from your point of view?

By the way - many thanks for the great work on this piece of software! I find it much more accessible then the AR-jdbc adapter.

**Comment by metaskills** [comment]
> The sequel gem already does a lot of the stuff that would have to be implemented a second time

To be fair, this is work that ActiveRecord would do. Can we explore a solution without it and let ActiveRecord be the giant?

> By the way - many thanks for the great work on this piece of software! I find it much more accessible then the AR-jdbc adapter.

Thanks!!! Means a lot to me and the others that contribute/use this.

**Comment by iaddict** [comment]
>> The sequel gem already does a lot of the stuff that would have to be implemented a second time

> To be fair, this is work that ActiveRecord would do. Can we explore a solution without it and let ActiveRecord be the giant?

Well, I already had a look at the code in sequel and ar-jdbc that is required for the jdbc connection handling and the type conversion stuff. I found it not to be worth to write this once again and not use the battle tested sequel gem. The inspiration to use sequel came from the rom gem, which does the same.

Maybe we can at least see the sequel mode as an intermediate step. I can rename it to jdbc mode, but still delegate the heavy lifting to sequel for now. At a later time I could rewrite it to directly use jdbc. For a user the switch would then be transparent.

What do you think?

I would be very happy if you would consider a merge of this approach, as it brings a stable alternative for sqlserver/jruby users.

The AR test suite now also runs with not that many failures/errors:
```
4876 runs, 14121 assertions, 25 failures, 21 errors, 12 skips
```

**Comment by iaddict** [comment]
A small update on the progress of the imminent sequel mode ;)
```4873 runs, 14159 assertions, 3 failures, 4 errors, 12 skips```

**Comment by metaskills** [comment]
> The inspiration to use sequel came from the rom gem, which does the same.

I think that makes sense for ROM, but not the adapter. The parts we need logically should belong to the adapter. Can we make that happen? I feel there are good interface points for this work and we should let ActiveRecord's type system work for us.

**Comment by iaddict** [comment]
I'm quite happy with the sequel mode so far and fear the burden of maintaining a completely self implemented tiny_tds-java gem a bit. Sequel already does a lot of stuff which essentially would have to be reimplemented. See: https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/jdbc.rb 

Anyway – how would you envision this tiny_tds-java gem should look like? Wouldn't it just be an api compatible implementation of the tiny_tds gem? If this would be the case, can you supply a spec or abstract implementation of the minimal set of required methods to make implementation a bit easier?

**Comment by metaskills** [comment]
> Sequel already does a lot of stuff which essentially would have to be reimplemented.

By contrast the TinyTDS adapter in Sequel is half the size of that jdbc file. The other half seems type related which the adapter should do for us. So I am still not seeing a lot that requiring a competing ORM buys us. I would very much prefer we implement a long `jdbc_connect` method that is our own and work past any connection/type issues as the come up.

> how would you envision this tiny_tds-java gem

If the above were done, I would drop TinyTDS as a runtime dep and go back to the days of requiring a connection mode gem be specified by the end users.

FYI, I am gonna start some hard work in master for 5.1. Ideally, I think this PR should target 5-0-stable. What do you think?

**Comment by iaddict** [comment]
> By contrast the TinyTDS adapter in Sequel is half the size of that jdbc file. The other half seems type related which the adapter should do for us.
That means activerecord-sqlserver-adapter should do the type conversion from Java types (eg. results on select) to ruby types?
I thought it will already return proper ruby types, thus the type conversion (at least from java to ruby) needs to be implemented.

**Comment by metaskills** [comment]
> That means activerecord-sqlserver-adapter should do the type conversion from Java types (eg. results on select) to ruby types? I thought it will already return proper ruby types, thus the type conversion (at least from java to ruby) needs to be implemented.

I assumed that everything that came back from JDBC was or could be a string. In theory, if that was the case, then ActiveRecord would do the type conversions for us and most of `sequel/adapters/jdbc` would be moot. This is how MySQL, PG, etc do things. TinyTDS is a rare breed that does all the casting to Ruby primitives for us. But again, in theory, this is not needed with ActiveRecord's current state.

**Comment by iaddict** [comment]
Ok. This makes sense. I only looked at TinyTDS and thought the type conversion has to be implemented by every mode adapter. I will try to implement something.

**Comment by iaddict** [comment]
I extracted the relevant bits from sequel.
The result values are now all returned ass strings.

```
222 tests, 1126 assertions, 18 failures, 4 errors, 9 skips
```

The failing specs are all related to type issues, eg.:
```
Minitest::Assertion: --- expected
+++ actual
@@ -1 +1 @@
-#<BigDecimal:1ee27d73,'4.2',2(4)>
+"4.2000"
```

Can you give me a hint how to let AR do the type conversion?

**Comment by metaskills** [comment]
> I extracted the relevant bits from sequel. The result values are now all returned as strings.
> 222 tests, 1126 assertions, 18 failures, 4 errors, 9 skips

Now we are talking! Sweet.

> Can you give me a hint how to let AR do the type conversion?

Hmmm... this varies. I often find that AR can not do its work because the schema reflection did not see the DB type properly. But we should be using the same schema reflection for column info, so that can't be it. These are the types of things I have to get in and just look at. Some talking around how to move forward. 

* I have made recent changes to  master for v5.1. Only about 30 tests to go. About a week or so.
* I want to get master green as soon as possible. Top priority before adding new features.
* Once done, I think you should make a PR to master and we get this in a v5.1 release.

Thoughts?

**Comment by iaddict** [comment]
> I have made recent changes to master for v5.1. Only about 30 tests to go. About a week or so.
> I want to get master green as soon as possible. Top priority before adding new features.
> Once done, I think you should make a PR to master and we get this in a v5.1 release.
Ok. Sounds good to me. Then I'll wait until master is green, so afterwards you can take a look at the type casting stuff?

And do you have an idea/preference for the gem name?

**Comment by metaskills** [comment]
> so afterwards you can take a look at the type casting stuff?

YES! Cant wait.

> And do you have an idea/preference for the gem name?

Sorry... do we need one? I assumed tour branch would remove TinyTDS as a run time dep too. Wold we need another gem then?

**Comment by iaddict** [comment]
> Sorry... do we need one? I assumed your branch would remove TinyTDS as a run time dep too. Wold we need another gem then?

Well, I can put the jdbc connection stuff in the tiny_tds gem, but would that be the proper place? I think this code should live in its own gem, something like sqlserver_jdbc or sqljdbc4_adapter.

**Comment by metaskills** [comment]
Negative... it really should go into the adapter. We have methods/interfaces just for this and we use these interfaces (basically methods with case statements) for TinyTDS too. Please see this commit for details.

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/502/commits/5e35c779ad8daf1cd95ff41d44c704c8afde0a82

So there should be a `jdbc_connect` method and all the fun stuff like you see in that commit that removed ODBC. Cool?

**Comment by iaddict** [comment]
Yes. This is what I do. But I have to create a gem like odbc or tiny_tds. This gem contains the methods that are called by the jdbc branches of the case statements.

The question now is how to name this gem? sqlserver_jdbc, sqljdbc4_adapter or ...?

This gem can then be referenced in a Gemfile just like tiny_tds.

**Comment by metaskills** [comment]
> But I have to create a gem like odbc or tiny_tds. This gem contains the methods that are called by the jdbc branches of the case statements.

Please don't. If that were true then the code that is there now would be in a adapter-tinytds gem and that would make things really hard on all of us. We would have to author the two in concerns the dependency management wold be a nightmare. I believe the structure we have had in the adapter fro the past for years is good enough for 1-many connection modes. It has worked really well. Trust me. If it does not look right, we don't make a gem and add dep management issues... we make the code better and more organized in this repo. But for now... please, simple `jdbc_connect` and case statement integration.

**Comment by iaddict** [comment]
Ok. That means I should also put the sqljdbc4-4.0.jar which is the mssql jdbc driver right into the activerecord-sqlserver-adapter repository?

Please look at the code (WIP) which needs to be integrated into activerecord-sqlserver-adapter:
https://github.com/iaddict/tiny_tds-java/blob/master/lib/tiny_tds/java.rb

I certainly just can include this stuff in the patch to activerecord-sqlserver-adapter instead of introducing a new gem  ...

I also changed my current sequel fork and changed some bits to make it work with the above suff:
https://github.com/iaddict/activerecord-sqlserver-adapter/commit/3072cfba15447944e025e886143d665d2a5e3243

**Comment by metaskills** [comment]
> I should also put the sqljdbc4-4.0.jar which is the mssql jdbc 

Ah, great question. That seems to be the heart of you thinking and I was not aware of it. Can you tell me more about where this comes from? So lets jam on that for a bit. I did a bit of Googling. 

* https://rubygems.org/gems/jdbc-sqlserver/versions/0.0.2
* https://github.com/jruby/jruby/wiki/JDBC
* https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server
* http://jtds.sourceforge.net

So now I have a question. To support JRuby best, which driver do we tie our ⭐️ to? There seems to be 2 options and both seem to champion Java v4 vs v5. What led you to use JDBC vs JTDS?

I don't think we should include jars in the repo. That ruby gem that distributes seems like one of many ways people can install the dep. In the end, I think we should do a `require` and leave it up to the individual how they get that jar in place. We can recommend things, just like JRuby did on their page.

I would still like to hear about JDBC vs JTDS?

**Comment by iaddict** [comment]
JTDS seems to be unmaintained: https://sourceforge.net/p/jtds/news/?source=navbar
The ms jdbc driver is maintained, can be bundled, distributed and supports Azure.

**Comment by metaskills** [comment]
Thanks! JDBC it is. Is there any reason not to use this gem https://rubygems.org/gems/jdbc-sqlserver/versions/0.0.2 like are they versions behind?

If so, then maybe we can make a new `sqljdbc4-ruby` gem or some other gem name. Don't see a reason it should be bundled in the adapter but it can have a home under the `rails-sqlserver` account if you want me to make that repo and add you as a collaborator?

**Comment by iaddict** [comment]
> If so, then maybe we can make a new `sqljdbc4-ruby` gem.

Sound good to me.

> Don't see a reason it should be bundled in the adapter but it can have a home under the rails-sqlserver account if you want me to make that repo and add you as a collaborator?

Yes, this would be Ok.

What about the connection and raw result handling code?
Should we include it in the new gem?

**Comment by metaskills** [comment]
> What about the connection and raw result handling code?
> Should we include it in the new gem?

See this comment. https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/579#issuecomment-297687686

**Comment by iaddict** [comment]
Ok. Please take a look at the following repos:

https://github.com/iaddict/sqljdbc4-java
https://github.com/iaddict/activerecord-sqlserver-adapter/tree/jdbc-mode

Most of the tests already pass:
```bash
# jruby -S bundle exec rake test:jdbc
4873 runs, 14220 assertions, 1 failures, 3 errors, 9 skips

# ONLY_SQLSERVER=1 jruby -S bundle exec rake test:jdbc
222 runs, 1349 assertions, 0 failures, 0 errors, 6 skips

```

What do you think?

**Comment by metaskills** [comment]
I think I have time opening up :) the Rails v5.1 work is in master and passing all tests. Getting JDBC connection support feels like a great thing to add now if we each have time? I can dedicate a few hours every week to touch base on this.

Can you make a PR to our master branch now? Summarize what we talked about here and we carry the conversation there?

**Comment by metaskills** [comment]
Moving all conversation to #599 now.
