### ISSUE TITLE
Can anyone come up with a "best practice" for security on SQL Server

### ISSUE THREAD

**Issue by ThorkilG12** [rails-sqlserver/activerecord-sqlserver-adapter#585]
I assume that I should have only one Login User on the SQL server. What is the most limited setting for this user if the user-id should be able to serve rails properly ?

**Comment by metaskills** [comment]
I think best is what makes sense for you. All I can say is that Rails applications (no matter what the DB type) assumes a level of permissions. For example, migrations require the ability to create tables and models typically require read/write. But all this is really up to how you need things. For example, in some cases, some may want their connection to be read-only. Maybe to a data warehouse or something. It really is up to you.
