### ISSUE TITLE
Is it possible to set the length of nvarchar for each column

### ISSUE THREAD

**Issue by ThorkilG12** [rails-sqlserver/activerecord-sqlserver-adapter#586]
I noticed that all text columns is 4000... How can I overrule this on a column level ?

**Comment by metaskills** [comment]
If you create a `:string` type column in a migration then our DB adapter will use `nvarchar(4000)` which is idiomatic Rails in the sense it should be the limit of your typical varchar type. 

Your question is not SQL Server adapter specific tho but more general to Rails. Please see this guide on migrations (http://guides.rubyonrails.org/active_record_migrations.html) which is what I think you are after. Specifically section 3.5 column modifiers... you want the `limit:` option when creating a string column. For example: `t.string :colname, limit: 4` would create a `nvarchar(4)` column. HTH.
