### ISSUE TITLE
Does Rails 5 ar sql server adapter work with sql 2005 and 2008

### ISSUE THREAD

**Issue by TheR2** [rails-sqlserver/activerecord-sqlserver-adapter#589]
From readme doc:
The SQL Server adapter for ActiveRecord v5.0 using SQL Server 2012 or higher.

So there is no way to connect to older versions of SQL server from Rails 5 except staying on Rails 4.

by
TheR

**Comment by metaskills** [comment]
Correct.

**Comment by metaskills** [comment]
### Full Replies

* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/571#issuecomment-283443927
* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/462

### Related

* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/476
* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/462
