### ISSUE TITLE
ActiveRecord 5.0.2 / adapter 5.0.7 - .find(id) results in SQL error `Invalid usage of the option NEXT in the FETCH statement`

### ISSUE THREAD

**Issue by neongrau** [rails-sqlserver/activerecord-sqlserver-adapter#590]
Seemingly due to the implied `limit: 1` without having set any `order` this results in an SQL error with

```
irb(main):019:0* Stuff.find(7)
  Stuff Load (0.0ms)  EXEC sp_executesql N'SELECT  [stuffs].* FROM [stuffs] WHERE [stuffs].[id] = @0 OFFSET 0 ROWS FETCH NEXT @1 ROWS ONLY', N'@0 int, @1 int', @0 = 7, @1 = 1  [["id", 7], ["LIMIT", 1]]
ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [stuffs].* FROM [stuffs] WHERE [stuffs].[id] = @0 OFFSET 0 ROWS FETCH NEXT @1 ROWS ONLY', N'@0 int, @1 int', @0 = 7, @1 = 1
```

Calling `.find` with more than one id will work. Same when explicitly defining an order `Stuff.order(:id).find(7)`.

**Comment by neongrau** [comment]
I'm currently debugging into this issue myself.
Background is my start to migrate an app from Rails 4.2 to 5.0.2.

So far i discovered that in `lib/arel/visitors/sqlserver.rb`: `primary_Key_From_Table` is failing to determine the primary key to use as fallback ORDER BY.

Which is quite odd since my model `Stuff`is using a very Rails-default `id` column. But i got plenty of Models where this fails. Some are using legacy tables with other primary key column names. Some work others don't.

Still quite mysterious.

**Comment by metaskills** [comment]
Are you using SQL Server 2012 or higher?

**Comment by neongrau** [comment]
yes, SQLServer 2016.

interestingly when i call this manually within a rails console it can detect the primary key

```
irb(main):034:0> ActiveRecord::Base.connection.schema_cache.primary_keys 'stuffs'
=> "id"
```

**Comment by neongrau** [comment]
Also a `Stuff.first` will work as well as the logged SQL on console shows that the primary key was detected for the `ORDER BY`

**Comment by metaskills** [comment]
So odd! Is the Stuff model a view or something? Last I checked the `5-0-stable` branch was solid for all ActiveRecord tests and we would not get far if this error was popping up.

**Comment by neongrau** [comment]
Ouch i just found the cause somewhere down below in the backtrace.

i have 
https://github.com/composite-primary-keys/composite_primary_keys
in my Gemfile which i needed for a single model that's using a legacy table.

But this has caused all the problems even though that wasn't used in any of the models that showed the errors.

It claims to be Rails 5 compatible (Gem version 9.0.6) vOv

**Comment by metaskills** [comment]
LOL... Oh yea... I used to ask that question all the time. Search the issues for the gem name and you will see the issues it cased too. Monkey patches on ActiveRecord is dangerous business :)

Glad you found it... gonna close this issue. Here if you need me.
