### ISSUE TITLE
ruby on rails with sql

### ISSUE THREAD

**Issue by bilalahmed144** [rails-sqlserver/activerecord-sqlserver-adapter#592]
1)i m using these gem(gem 'activerecord-sqlserver-adapter'
gem 'tiny_tds'
gem 'ruby-odbc'

gem 'axlsx'

2) @Products = Product.where(ActiveRecord::Base.connection.select_all("execute NR_Daily_Sales '7', '2017-05-08'"))
respond_to do |format|
format.html
format.csv { send_data @Products.to_csv }
end (in products_controller)

3)  in product model 
def self.to_csv
CSV.generate do |csv|
csv << column_names
 all.each do |product|  
csv << Product.attributes.values_at(*column_names)

end
end

4)   ActiveRecord::Base.connection.select_all("execute NR_Daily_Sales '7', '2017-05-08) //////////// that is a query that get data from MS SQL server online.(i make sql connection in database.yml )

5)  i want get csv or xlsx format file download and fetching from sql.

**Comment by metaskills** [comment]
Please switch to TinyTDS. RubyODBC is not supported.

**Comment by metaskills** [comment]
With regard to your question. Could you distill down you issue a bit more? Your question seems more related to general ruby/rails programming vs an issue with the SQL Server adapter. Is that correct?
