### ISSUE TITLE
Error converting nvarchar to datetime using TinyTDS/activerecord-sqlserver-adapter

### ISSUE THREAD

**Issue by YvesR** [rails-sqlserver/activerecord-sqlserver-adapter#594]
Hello Ken,

we recently updated our environment to
- Rails 5.0.2
- Ruby 2.3.3p222 x64-mingw32
- tinyTds 1.2.0
- activerecord-sqlserver-adapter 5.0.7

Test system:
- Windows 2016, english version, regional settings to german location, format, etc.
- SQL Server 2016
<img width="314" alt="dbcc" src="https://cloud.githubusercontent.com/assets/4928882/26446028/bf2bd12c-4142-11e7-8538-6eed54b61480.png">

In this version we run into conversion problems regarding datetime columns in the database.
As we use sql server to store session in table [sessions] we get the following error in our logs:

```
2017-05-25 11:53:45 ERROR [16320] [2017-05-25 11:53:45] <ActionController::Parameters {"ror_referer"=>"/ror/", "controller"=>"login", "action"=>"index"} permitted: false>
TinyTds::Error: Fehler beim Konvertieren des varchar-Datentyps in datetime.: EXEC sp_executesql N'INSERT INTO [sessions] ([session_id], [data], [created_at], [updated_at]) OUTPUT INSERTED.[id] VALUES (@0, @1, @2, @3)', N'@0 nvarchar(4000), @1 nvarchar(max), @2 datetime, @3 datetime', @0 = N'191494c214b49f6a68f13e66c5a3a9d4', @1 = N'BAh7AA==
', @2 = '05-25-2017 11:53:45.077', @3 = '05-25-2017 11:53:45.077'
```
As you can see the dateformat parameter value is wrong.
`@2 = '05-25-2017 11:53:45.077` should be `@2 = '2017-05-25 11:53:45.077`

I tried digging into the code and modified to tests `def initialize_dateformatter` in `sqlserver_adapter.rb` and just made a quick hack like this:

        ::Date::DATE_FORMATS[:_sqlserver_dateformat]     = '%Y-%m-%d' #dateformat
        ::Time::DATE_FORMATS[:_sqlserver_dateformat]     = '%Y-%m-%d' #dateformat

But this changed nothing. I still get the wrong dateformat in the string creating the INSERT statement, so TinyTDS popup error again as expected.

I checked the code where the date values are set in the models and there `Time.Now` is used.

When I copy+paste the created statement into SSMS and fire it it will work.

So do you have any idea where I can check why this happens?
As your tests passed I doubt it a bug in the activerecord-sqlserver-adapter but who knows... if not you :)?.

BTW: Why don't we always regardless any language use ISO 8601 string format to pass it to the sql server? I tried on Azure and all other SQL Server language since 2005, a string like `2009-04-30T12:34:56.790` would always work.

**Comment by YvesR** [comment]
Found out my problem.
In some queries we had special case:

`SET LANGUAGE german` 

But in our current environment this works fine as this is only be used in that specific query.
Does any scopes changed?

**Comment by metaskills** [comment]
So the language setting drives the date format. As you have discovered, we also do a lot of work to read that date format and memoize it. The adapter considers it a constant for the DB session. So that is why a per language query is having issues.

Your assumption about ISO date/time format is a logical one too. But IIRC, it does not work in every situation and it is the reason we use the date format returned from dbcc user options for so many years now. I would be open for trying ISO-8601 again if I or someone had time. It might be easier now more than before with the types all using them. Created #596 to track that specifically.

**Comment by metaskills** [comment]
That said, I'm not sure what the adapter can do for per language queries? Maybe you would have a need for a method that took a block and some date/time format options and change our singletons for the duration of the block as needed? That method would wrap statements when you set the language differently? Or maybe #596 is worth someone's exploration?

**Comment by YvesR** [comment]
Thank you for the feedback. The database I used that run into this issue is already running in production with `activerecord-sqlserver-adapter (4.2.3)` and there I did not run into the problem that the scope of `SET LANGUAGE german` is session-wide. So something must have changed that cause this. I use same Tiny-Tds (1.2.0).

**Comment by metaskills** [comment]
Linking to #600 now and moving all talk there.
