### ISSUE TITLE
Consider ISO-8601 Date/Time Format

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/activerecord-sqlserver-adapter#596]
We use `DBCC USEROPTIONS` to get per session date time formats. In theory, most if not all SQL Server date formats support ISO-8601 formatted strings. Now that we have a clean type simple and strong delegation to out `Time/Date::DATE_FORMATS` we should be able to test what data types can always use ISO-8601 strings. Considerations:

* Some types like smalldatetime may need truncated version of a full ISO time representation.
* Could we guarantee indexes would be re-used?

**Comment by YvesR** [comment]
I made some tests (screenshot) and check about insert in ISO 8601 and so far as we consider earliest possible date for `smalldatetime` and `datetime` we can use ISO 8601 string to insert into a sql database.

![date](https://cloud.githubusercontent.com/assets/4928882/26539344/3481fabc-444c-11e7-9274-01e10b5c8197.png)

What do you mean about indexes re-used? Database indexes are used as after insert the database handles it data.

**Comment by metaskills** [comment]
> What do you mean about indexes re-used? 

For example, I know it is possible that if a non-national char column had an index and a query was formatted like `where foo = N'bar'` then it would not use said index. Another example being type coercion, like using a literal integer when the column is char would bypass an index too.

The general idea is that SQL is full of these gotchas and I was wondering if there could be issues when dates in SQL statements are formatted one way vs another. See what I'm saying?

**Comment by metaskills** [comment]
Also, do you want to take a stab at a PR? Now that master is green, it would be easy to get +/- feedback quickly on this type of change.

**Comment by YvesR** [comment]
In general there would be no difference as we do now. The adapter always create a string that is passed so SQL Server will translate that string into the column format the column is defined.
So passing it generally in ISO 8601 SQL Server will act the same way, it will take the string and converts it into a date-format.

Nevertheless, I will do run some tests with Profiler if any index is used (or not used) using the format and will post back.

About making a PR: I am a big noob using git / github, etc. so I can for take a installation, modify the code there and do tests after. But I need to learn do it the github way :).

**Comment by YvesR** [comment]
I did modified the sqlserver_adapter.rb on my system as follows:

 ```
     def initialize_dateformatter
        #@database_dateformat = user_options_dateformat
        #a, b, c = @database_dateformat.each_char.to_a
        #[a, b, c].each { |f| f.upcase! if f == 'y' }

        # simple change to IS8601 format
        dateformat = "%Y-%m-%d" #"%#{a}-%#{b}-%#{c}"
        ::Date::DATE_FORMATS[:_sqlserver_dateformat]     = dateformat
        ::Time::DATE_FORMATS[:_sqlserver_dateformat]     = dateformat
        ::Time::DATE_FORMATS[:_sqlserver_time]           = '%H:%M:%S'
        ::Time::DATE_FORMATS[:_sqlserver_datetime]       = "#{dateformat}T%H:%M:%S" # ISO 8601 format
        ::Time::DATE_FORMATS[:_sqlserver_datetimeoffset] = lambda { |time|
          time.strftime "#{dateformat} %H:%M:%S.%9N #{time.formatted_offset}"
        }
      end
```
Checked in development and production mode.
Using the SSMS SQL Profiler I checked all sent SQL statements using date, datetime columns and it works as expected.

As positive side effect: I add `SET LANGUAGE german` again on one specific query and it won't affect the system anymore.

**Comment by metaskills** [comment]
> different formats including the ISO 8601 format SQL Server seems smart enough, always uses the defined clustered indexes

Thank you so much for testing that!

> About making a PR: I am a big noob using git / github, etc. so I can for take a installation, modify the code there and do tests after. But I need to learn do it the github way :).

I can help... it is usually a good first time experience. You can also post diffs, do things locally, etc... whatever work. Appreciate any help tho. What you've done already is great!!!

> I did modified the sqlserver_adapter.rb on my system as follows:

Thanks... I'll try a few here too and get back to ya.

**Comment by metaskills** [comment]
Looks like we got this going in #600 now.
