### ISSUE TITLE
Problem in Windows 10 Ruby 2.4 Rails 5.1.2

### ISSUE THREAD

**Issue by andresfranco** [rails-sqlserver/activerecord-sqlserver-adapter#604]
My database.yml is : 
development:
  adapter: sqlserver
  database: railsdb
  username: sa
  password: xxx
  encoding: utf8

when i execute th migrations i have this error:
LoadError: cannot load such file -- tiny_tds/tiny_tds
C:/ProyectosRails/studyrails/config/application.rb:7:in `<top (required)>'
C:/ProyectosRails/studyrails/Rakefile:4:in `require_relative'
C:/ProyectosRails/studyrails/Rakefile:4:in `<top (required)>'
LoadError: 126: The specified module could not be found.   - C:/rubyinstaller-2.4.1-1-x64/lib/ruby/gems/2.4.0/gems/tiny_tds-1.3.0-x64-mingw32/lib/tiny_tds/2
.4/tiny_tds.so
C:/ProyectosRails/studyrails/config/application.rb:7:in `<top (required)>'
C:/ProyectosRails/studyrails/Rakefile:4:in `require_relative'
C:/ProyectosRails/studyrails/Rakefile:4:in `<top (required)>'

it is compatible in this environment?
thank you .

**Comment by metaskills** [comment]
Sorry for the late reply. I've seen this before in some Windows setups. Could you please try to use TinyTDS v2.0.0 or 2.1.0.pre3 instead?
