### ISSUE TITLE
Problem with creating/updating records with null value in "created_at"/"updated_at"

### ISSUE THREAD

**Issue by ahmadagha** [rails-sqlserver/activerecord-sqlserver-adapter#605]
ActiveRecord::StatementInvalid (TinyTds::Error: Cannot insert the value NULL into column 'created_at'; column does not allow nulls. INSERT fails.
I am getting the following error while creating or updating records. The error appeared on all models randomly. The error does not appear every time but randomly and get resolved automatically. I am using Rails 5 on ubuntu with SQL Server Express 13.00.2164.0.v1 and activerecord-sqlserver-adapter (5.0.5) with activerecord (5.0.2).

Any help on this will be appreciated.

**Comment by metaskills** [comment]
Not sure where to start. It sounds like you are having a callback issue... but if that is the case, it would be coupled to how your model code looks. I can say that I've never seen this error in the suite. So the request is that you help understand why you are seeing this error. Can you do some investigation?

**Comment by ahmadagha** [comment]
I have one common callback for all models. I have tried to resolve the issue by disabling that callback but no luck. Many of the models have no callback but issue is arising in those model's create/update operation also.

**Comment by metaskills** [comment]
Odd... sorry for the slow reply. Have you been able to track this down? Is it a threading issue, maybe from a background job or something? Really hard to do anything here other than tell I've never seen an ActiveRecord timestamp not get assigned by their own callbacks, ever. So finding out what is happening on your side or creating a reproducible case for others to see would be the only way to help.
