### ISSUE TITLE
Question about date storage and timezones

### ISSUE THREAD

**Issue by nielsjansendk** [rails-sqlserver/activerecord-sqlserver-adapter#608]
I'd like some advice on the following situation: we are storing data like birthdays in our database. If a person is born on July 11th 2017, this will be stored as either 10-07-2017 22:00:00. If it is November 11th, it will be stored as 10-11-2017 23:00:00 because of daylights saving time (We are either at UTC+2 or UTC+1). When the dates are shown through the rails app, they are shown correctly. However, sometimes we need to extract information directly from the database using sql scripts. This involves having to compute the correct date and is extra work.

Is there any way that date fields can be stored as that date at midnight, regardless of the timezone? I seem to recall that there was a function called "coerce_sql_server_date" but it didn't work. Is there are reason why date-fields behave in this way (taking time-zone into consideration)? Datetime fields make sense, but a date is that particular date, regardless of timezone. 

We are using: 
rails 5.0.1
tiny_tds 1.1.0
activerecord-sqlserver-adapter 5.0.4
Microsoft SQL server 2012

but this is a problem we have had for a long time, through several upgrades, so I don't think is matters.

**Comment by metaskills** [comment]
What data type is the column you are talking about? There are several date/time types?

**Comment by nielsjansendk** [comment]
I think they are stored as datetime. The process is, that there is an input field where a string with the date is input. A save is then called on the object. What I would like to happen is than when a date is input the time is automatically set to midnight, for that particular field. I am guessing that somehow in the save action, Time.zone.parse(input_string) is used, instead of input_string.to_datetime . I guess what I could do is explicitly call to_datetime on the string before save. That might actually solve my problem. Would be nice to have some sort of functionality that says "don't timezone this field", though.

**Comment by metaskills** [comment]
> When the dates are shown through the rails app, they are shown correctly
> However, sometimes we need to extract information directly from the database using sql scripts. This involves having to compute the correct date and is extra work.

So the default ActiveRecord behavior is to assume the values set in the DB are UTC and then the app casts to a specific zone which can even be dynamic per user. It is a pretty neat system. Have you read up on that? Because what you are describing is normal and configurable to a point. Either way, some person will have to do work and the general convention is to pick UTC in the DB. More details here:

* http://guides.rubyonrails.org/configuring.html
* http://www.createdbypete.com/articles/working-with-locales-and-time-zones-in-rails/

**Comment by nielsjansendk** [comment]
It's configurable for the entire app, but I don't think it is for a specific column in a specific table. Maybe I am misremembering, but didn't there use to be an option in activerecord-sqlserver-adapter where you could coerce a datetime column to behave as a date? 

Anyway, thanks for you help. I guess we will have to do some tedious work, then.

**Comment by metaskills** [comment]
> It's configurable for the entire app, but I don't think it is for a specific column in a specific table.

Correct. Not for a table/column.

> but didn't there use to be an option in activerecord-sqlserver-adapter where you could coerce a datetime column to behave as a date?

Yes... but that was to work around an old issue where it was hard to set specific DB types. Check out the 3-2-stable branch readme. https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/tree/3-2-stable#datetime-data-type-hinting

If you want to do that in your own model... super easy. Logic up to you too. But for example:

```ruby
def bonus_time
  super.try(:to_date)
end
```

**Comment by metaskills** [comment]
Closing this issue but do ping back if you need anything
