### ISSUE TITLE
save! not returning the IDENTITY PK

### ISSUE THREAD

**Issue by blgrnboy** [rails-sqlserver/activerecord-sqlserver-adapter#610]
I noticed an issue with save!.  When I save a model, it doesn't seem to return the ID that the database generated to that model.  Other models associated to this model are therefore not getting their foreign_key set .  I therefore have to use the below code, and a workaround of retrieving the ID right after right after save:

```
request.attributes = attributes
request.touch
request.save!

retrievedRequest = self.where(:reqnumber => ac.reqnumber).select(:id).first
request.id = retrievedRequest.id  # I have to do this as a workaround

if ac.case == "Router" then
	request.build_router if request.router.nil?
	request.router.attributes = router_attributes
	request.router.touch if request.router.nil? 
	request.router.save!
end
```

**Comment by metaskills** [comment]
Sorry for the late reply. It would be safe to assume there is something with your specific code/app that is causing this. To that end, I would debug first that you can create/save a new instance of that model outside this code... like open a console, etc. Moving on from there, I would find out if the way you organized the methods is an issue. For example, if `request.persisted?` is false and you call `.touch` on it, maybe you are learning out the `.dirty?` attributes assigned earlier and the save does nothing. Do break this down a bit more to try to find out what is happening on your end. Closing this issue, but please do reply back if needed.
