### ISSUE TITLE
connection to 2 SQL servers with different versions

### ISSUE THREAD

**Issue by mkarganov** [rails-sqlserver/activerecord-sqlserver-adapter#615]
Hi!

Our app uses 2 Microsoft SQL servers DBs. Recently we got one of them updated to 2016. As a result version of the adapter has been also updated to 4.2. But other DB is still on SQL server 2008. 

Is it possible somehow to connect to both of them? I know that latest version of the adapter supports versions of SQL server 2012 and above. Unfortunately we are unable to update the other DB.

**Comment by metaskills** [comment]
Short answer no. There are lots of longer answers in other issues if you care to search as to why. Basically it all comes down to incredible gymnastics needed to make limit and offset work which propagate all the way down to the Arel visitor. If you want your app to talk to the 2008 DB, then you are going to need to make decisions specific to your setup on how to do that. Perhaps using simple TinyTDS connections with ActiveModel to even using a forked and re-namespaced older adapter as another connection. Or even bundling the Sequel gem to manage connections to that DB within the app. Really up to you and how you are using it. HTH!
