### ISSUE TITLE
Querying for bigint columns raises an error

### ISSUE THREAD

**Issue by wpolicarpo** [rails-sqlserver/activerecord-sqlserver-adapter#616]
## Problem

Whenever I try to query for a `bigint` column an error is raised: 

`ActiveRecord::StatementInvalid: TinyTds::Error: Error converting data type numeric to int.`

See reproducible steps below:

**Update:**

Apparently the error only occurs when I try to `count` or use a `uniqueness` validator.

## How to reproduce
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "5.0.4"
  gem "activesupport", "5.0.4"
  gem "tiny_tds"
  gem "activerecord-sqlserver-adapter", "5.0.7"
  gem "pry-byebug"
end

require "active_record"
require "active_support/time_with_zone"
require "minitest/autorun"
require "logger"
require "pry"

ActiveRecord::Base.establish_connection(
  adapter: "sqlserver",
  reconnect: false,
  timeout: 5000,
  pool: 100,
  encoding: "utf8",
  database: ENV["DATABASE_NAME"],
  username: ENV["DATABASE_USERNAME"],
  password: ENV["DATABASE_PASSWORD"],
  host: ENV["DATABASE_HOST"],
  port: ENV["DATABASE_PORT"],
)
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.default_timezone = :local
ActiveRecord::Base.time_zone_aware_attributes = true

ActiveRecord::Schema.define do
  drop_table :bug_tests rescue nil
  create_table :bug_tests, force: true do |t|
    t.bigint :external_id
  end
end

class BugTest < ActiveRecord::Base
  validates :external_id, uniqueness: true
end

class TestBugTest < Minitest::Test
  def setup
    @external_id = 1601122032070100001
    @bug_test = BugTest.create!(external_id: @external_id)
  end

  def test_count
    assert_equal 1, BugTest.where(external_id: @external_id).count
  end
end
```

**Comment by metaskills** [comment]
Yup... seems we need to do more in our sp_executesql types since the SQL looks like this:

```
WHERE [sst_datatypes].[bigint_col] = @0', N'@0 int', @0 = 9223372036854775808
```

**Comment by metaskills** [comment]
Using the current 5.1 master branch and the `ColumnTestSQLServer#biginit` methods as a test sandbox.

```ruby
SSTestDatatype.where(bigint: 9_223_372_036_854_775_807).count
# => 1

SSTestDatatype.where(bigint: 9_223_372_036_854_775_808).count
# ActiveModel::RangeError: 9223372036854775808 is out of range for 
# ActiveRecord::ConnectionAdapters::SQLServer::Type::BigInteger with limit 8 bytes

SSTestDatatype.connection.select_value <<-SQL
  SELECT COUNT(*) FROM [sst_datatypes] 
  WHERE [sst_datatypes].[bigint] = 9223372036854775808
SQL
# => 0
```

So that looks and it appears that the type system in 5.1 is much better than 5.0. It appears that this all works without needing to resort to adding more logic in our `sp_executesql_sql_type` to case the value and use `bigint` depending on its size. I would be open to a PR to 5.0 if there were a way to fix this. Maybe we need to add some value logic in `sp_executesql_sql_type`?

**Comment by metaskills** [comment]
Hmm, I tried this in `5-0-stable` too and it worked fine. I wonder if your `external_id` is really a bigint?

```ruby
SSTestDatatype.where(bigint: 9_223_372_036_854_775_807).count
=> 1
```

**Comment by metaskills** [comment]
BTW, excellent use case of a test script. I used that and everything passed for me. I wonder what is happening on your end?

**Comment by wpolicarpo** [comment]
@metaskills thanks for responding.

I'm not an expert in SQL Server, but it might be related to the [compatibility level](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-compatibility-level). Which version and compatibility level are you running?

I am running against a SQL Server 2016 with compatibility level 100 (yeah, I know 😢 ). Could you try that?

**Comment by metaskills** [comment]
Whoa, that's the lowest for 2016. Not sure I want to do that :)

But the serious question would be what do you think we could do for this and what is happening? Does SQL Server in 100 mode not support the min/max values for bigint in other versions?

**Comment by metaskills** [comment]
Would something like #622 work/help?

**Comment by wpolicarpo** [comment]
I spent a few minutes debugging in the past, but I can't remember what exactly was happening since I was migrating an application from Rails 4 to Rails 5.1 and this issue is gone in 5.1.

To be honest, I've realised now that my example is wrong and you need to uncomment that `uniqueness` validation to get an error. I updated the example and got this:

```bash
  1) Error:
TestBugTest#test_count:
ActiveRecord::StatementInvalid: TinyTds::Error: Error converting data type numeric to int.: EXEC sp_executesql N'SELECT  1 AS one FROM [bug_tests] WHERE [bug_tests].[external_id] = @0  ORDER BY [bug_tests].[id] ASC OFFSET 0 ROWS FETCH NEXT @1 ROWS ONLY', N'@0 int, @1 int', @0 = 1601122032070100001, @1 = 1
    /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-5.0.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:346:in `each'
```

**Comment by metaskills** [comment]
Thanks, but does the work in #622 help?

**Comment by wpolicarpo** [comment]
I applied that patch on my local env and it seems to solve the issue.

**Comment by metaskills** [comment]
Got a commit in master that mirrors what we see in #622, but a little cleaner. See c100d3188739e7941fc0c1b3dea94abad24ddb94 for details. Will be in next release.
