### ISSUE TITLE
Limit lowercase_schema_reflection settings effects

### ISSUE THREAD

**Issue by ilude** [rails-sqlserver/activerecord-sqlserver-adapter#618]
I have a abstract class extending ActiveRecord::Base defined that I use to open a a different database connection for the models that inherit from this abstract class. 

(See https://stackoverflow.com/a/3610057/1973777 for code samples of what I'm doing)

Is there a clean way for me to set lowercase_schema_reflection for just these models and their underlying connections that inheriting my abstract class and leave the global ActiveRecord::ConnectionAdapters::SQLServerAdapter alone?

**Comment by metaskills** [comment]
Well, the adapter uses `cattr_accessor :lowercase_schema_reflection` for that feature which also generates instance methods. Knowing that, you could do a little bit of freedom patching to meet your needs. Maybe something like this, pseudo code...

```ruby
ActiveRecord::ConnectionAdapters::SQLServerAdapter.class_eval do
  private
  def lowercase_schema_reflection
    # your logic here with `self.class.lowercase_schema_reflection`
  end
end
```

That creates a new instance method but I can't think of what to add to it that helps the method operate one way for some tables, classes as needed. Digging more into the code, we can see that this property method is only used by the following two methods.

* data_source_sql(name = nil, type: nil)
* column_definitions(table_name)

Perhaps you could freedom patch those methods using the Module.prepend method (which allows a super call) to only dynamically set `self.lowercase_schema_reflection = true|false` as needed based on the name argument. 

Outside of that, the only thing we could do that I think makes sense is to move this setting to a connection/initialize property. But that would bring new issues like encouraging multiple connections/pools with manual [two phase commits](http://technology.customink.com/blog/2015/06/22/rails-multi-database-best-practices-roundup/) vs a shared one to all models to that DB.

**Comment by ilude** [comment]
Thanks for the feedback. I just wanted to be sure I was not reinventing a solution to a solved problem before I started working on it. 

If I figure something out I'll send a pull request.

**Comment by developish** [comment]
@ilude have you come up with an effective way to do this? I'm looking to do almost exactly the same thing.

**Comment by ilude** [comment]
@developish no sorry I have not. Currently it on my "would be nice to have" list. So other priorities are ahead of it. 

I took a look at freedom patching those methods using Module.prepend, but could not see a way of doing it that would be safe. The column_definitions is the problem as it only gets the tablename and its hard from that to be 100% sure. i.e. same table name in different databases.

The right way to solve this seems to be making the setting into an instance method. But I do not have time right now to dig in and get a solid understanding of the connection pooling to try and create a workable solution that does not cause the problems @metaskills mentioned.

**Comment by metaskills** [comment]
Maybe this is one of those things where we made a small feature outside of ActiveRecord to help a little bit for a few people and it ends up snowballing into more and more needed too support it. For example, maybe views are the answer to this when the global setting is not a good fit.

**Comment by engineersmnky** [comment]
If the intention of `lowercase_schema_reflection` is really just for convention to allow lower case method names and that is all. Then the simplest patch I can come up with is leave this option turned off and then add the following to `ApplicationRecord`: 

    def self.inherited(subclass)
      super
      subclass.class_eval do
        attribute_names.each do |attr|
          alias_attribute attr.downcase, attr
        end
      end
    end

This seems to be the least breaking change while still allowing all method names to be accessed accordingly. Additionally this would allow for conversion to snake case as well. 

     def self.inherited(subclass)
      super
      subclass.class_eval do
        attribute_names.each do |attr|
          alias_attribute attr.gsub(/(?<!^|[A-Z])[A-Z]/){"_#$&"}.downcase, attr
        end
      end
    end

Now if you have columns like "SomeTableNameId" or even "SomeTableNameID" it will be converted to: 

     some_table_name_id
