### ISSUE TITLE
TinyTds::Error: DBPROCESS is dead or not enabled

### ISSUE THREAD

**Issue by skukx** [rails-sqlserver/activerecord-sqlserver-adapter#623]
I have the following setup:

```ruby
# config/my_second_database.yml
default: &default
  adapter: 'sqlserver'
  username: <%= ENV['MSSQL_USER'] %>
  password: <%= ENV['MSSQL_PASSWORD'] %>
  dataserver: <%= ENV['MSSQL_HOST'] %>
  database: <%= ENV['MSSQL_DB'] %>
  pool: 5

# app/models/base_record.rb
class BaseRecord < ActiveRecord::Base
    self.abstract_class = true
    self.ignored_columns = %w(class)

    establish_connection MY_SECOND_DB
end

# app/models/my_model.rb
class MyModel < BaseRecord
end
```

While inside the rails console:
```ruby
MyModel.first
#=> #<MyModel:0x00>

# Leave idle for a few minutes
MyModel.first
#=> ActiveRecord::StatementInvalid: TinyTds::Error: DBPROCESS is dead or not enabled ... gems/activerecord-sqlserver-adapter-5.0.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:354:in `cancel'

MyModel.connection.active?
#=> false
MyModel.connection.reconnect!
MyModel.connection.active?
#=> true

MyModel.first
#=> #<MyModel:0x00>
```

Leaving the connection idle bubbles the error `ActiveRecord::StatementInvalid: TinyTds::Error: DBPROCESS is dead or not enabled`.

Gems:
rails (5.05)
activerecord-sqlserver-adapter (5.0.7)
tiny_tds (0.7.0)

Is there a way to reconnect automatically or prevent the error from being raised?

**Comment by neongrau** [comment]
There is a `reconnect: true` setting that you can put in the database.yml
I'd assume that should do it.

**Comment by metaskills** [comment]
Please read this comment/issue for more information https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/402#issuecomment-107074580

Rails should be doing the work for us. I wonder if this is not the case because you use a manual/second connection that ActiveRecord now needs to get hooked up in a few places. Just like the schema cache. Ex: https://github.com/customink/secondbase#the-activerecord-query-cache

**Comment by metaskills** [comment]
Closing this issue... please read the links above and do reply if you think I should re-open this.
