### ISSUE TITLE
how to connect to a new DB and how to execute a query ?

### ISSUE THREAD

**Issue by Greek007** [rails-sqlserver/activerecord-sqlserver-adapter#628]
i do see  not any user document to use this gem like 'tiny_tds' has.
i need to connect to DB , but i do know how to use this ?

can  any one tell me how to connect to DB and how to run a query ?

**Comment by metaskills** [comment]
If you want to use Rails, then any online resource for creating an app `rails new myapp --database=sqlserver`, migrations, models, etc apply. There is nothing different about using the SQL Server adapter vs any other database with Rails. This is a demo app I used for connecting to SQL Server Docker images if you are curious:

https://github.com/rails-sqlserver/ss_app

If however you want to bypass Rails/ActiveRecord, you can use TinyTDS as a standalone gem, then its documentation would be here. Not sure which you need/prefer. https://github.com/rails-sqlserver/tiny_tds#readme

Hope that helps.
