### ISSUE TITLE
UUID not being added to schema.rb

### ISSUE THREAD

**Issue by landonclark** [rails-sqlserver/activerecord-sqlserver-adapter#629]
This is a simplified bug reproduction recipe of something I am seeing in our project:

* Using Rails 4.2.10 and gem version 4.2.18, create an app like this: `rails new uuid_bug --database=sqlserver`
* Then add tiny_tds to the Gemfile and create the database: `rake db:create`
* Generate a a new model with `rails g model Book` and edit it to look like this:

```ruby
class CreateBooks < ActiveRecord::Migration
  def change
    create_table :books, id: :uuid do |t|

      t.timestamps null: false
    end
  end
end
```

* Here's what the database looks like:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/79019/32930919-69a681b2-cb16-11e7-921c-e4a4c2e8e111.png">
* The bug is with the generated schema.rb which looks like this:

```ruby
ActiveRecord::Schema.define(version: 20171117050853) do

  create_table "books", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
```

Notice that there is no UUID marking there. Thus, if you do this:
`rake db:reset`

You end up with this:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/79019/32931108-45fb962a-cb17-11e7-865d-2b5f55c22eb0.png">

Thanks for this project - it has been a life saver!

**Comment by metaskills** [comment]
Thanks for issue report. Really nice written out too. Pretty sure this is fixed in 5-0-stable or master for 5.1 too. If you are stuck on Rails 4.2, I would take a PR targeting the `4-2-stable` branch.

**Comment by landonclark** [comment]
I confirmed that it's not an issue with Rails 5.1.  I will see what I can do, but it might be enough of an impetus to move us off Rails 4...  I will take a look at what a pull request would look like this weekend and either close or comment.  Thanks!

**Comment by metaskills** [comment]
Thanks for looking into current Rails. If you do a PR, I will find the time to get it merged.
