### ISSUE TITLE
Flooding of SELECT @@version

### ISSUE THREAD

**Issue by rhuanbarreto** [rails-sqlserver/activerecord-sqlserver-adapter#632]
I'm profiling my applications and I see lot's of SELECT @@version running on it.

How to disable it?

**Comment by metaskills** [comment]
Are you in development mode or production?

**Comment by metaskills** [comment]
I created this PR and when the tests go green I will merge to master and push a new gem version. Can you confirm this fixes your issue? https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/633

**Comment by metaskills** [comment]
Released v5.1.5 (master and rubygems) with that update. Please do let me know if that helped.

**Comment by rhuanbarreto** [comment]
@metaskills i'm profiling in development, but it also occurs in production. I will update the gem and test.

Thank you!

**Comment by rhuanbarreto** [comment]
@metaskills can you update it for rails 5.0?

**Comment by metaskills** [comment]
Sure, would you mind doing the pull request for me? Make sure to target the 5-0-stable branch. Also, an update to VERSION and the CHANGELOG would be great. I can then merge and push to rubygems.

**Comment by rhuanbarreto** [comment]
Pull request #634 is ready.

**Comment by rhuanbarreto** [comment]
Solved.
