### ISSUE TITLE
Flood of USE statements

### ISSUE THREAD

**Issue by rhuanbarreto** [rails-sqlserver/activerecord-sqlserver-adapter#637]
In my queries there is o lot of USE [database] queries before the real query. this takes 10 to 15% of the database time.

Could be more useful and fast if you add the database directly to the statement instead of doing this. or doing only one USE statement per page load.

**Comment by rushed** [comment]
You might consider one of the db switching gems (for example MultiDB, or one of its forks if you need ActiveRecord 5 support). Pairing one with a before_action in your application controller sounds like what you're asking for.

**Comment by wpolicarpo** [comment]
@rhuanbarreto can you provide more information? Rails and adapter versions? How are your models organised? Do you have more than 1 database or schema?

Maybe a reproducible script?
