### ISSUE TITLE
ActiveRecord::Base.connection.execute 

### ISSUE THREAD

**Issue by chuck-john** [rails-sqlserver/activerecord-sqlserver-adapter#656]
I'm trying to use `ActiveRecord::Base.connection.execute` to import some MSSQL functions and stored procedures but receiving the following error on the first line of the `.sql` file. Is this functionality supported?

![ddl load error](https://user-images.githubusercontent.com/1545623/44680708-2446a200-aa04-11e8-9af1-2688daf0ffb2.png)

#### Rake task to load raw SQL
```ruby
namespace :db do
  namespace :ddl do
    desc 'Load custom database DDL'
    task load: :environment do
      sql = File.read Rails.root.join('db', 'ddl.sql'), encoding: Encoding::UTF_8
      ApplicationRecord.connection.execute sql
    end
  end
end
```

#### First function in our `db/ddl.sql`
```sql
GO
CREATE OR ALTER FUNCTION [dbo].[BlahBlahBlah]
	(
		@Code varchar(5)
	)
	RETURNS varchar(5)
AS
BEGIN
DECLARE @Return varchar(5)
SELECT @Return=id FROM codes WHERE code=@Code
RETURN @Return
END
GO
...
```

**Comment by metaskills** [comment]
The GO statements are not needed in the FreeTDS/TinyTDS implementation of DBLIB for TSQL IIRC.

**Comment by chuck-john** [comment]
Removing them brings up a different syntax error. Reducing the file to a single function without GO statements processes fine. However, multiple functions in a row produces the error:

![ddl error 2](https://user-images.githubusercontent.com/1545623/44727179-109c4980-aa9f-11e8-98c8-41b615d10081.png)

```sql
CREATE OR ALTER FUNCTION [dbo].[BlahBlahBlah]
	(
		@Code varchar(5)
	)
	RETURNS varchar(5)
AS
BEGIN
DECLARE @Return varchar(5)
SELECT @Return=id FROM codes WHERE code=@Code
RETURN @Return
END

CREATE OR ALTER FUNCTION [dbo].[YaddaYaddaYadda]
	(
		@Code varchar(5)
	)
	RETURNS varchar(5)
AS
BEGIN
DECLARE @Return varchar(5)
SELECT @Return=id FROM codes WHERE code=@Code
RETURN @Return
END
```

**Comment by metaskills** [comment]
Correct, SMS TSQL will not port directly. You have to put these into distinct executes.

**Comment by metaskills** [comment]
If you need compatibility, you can split the file on GO/END and parse those out. But they need to be distinct executes.
