### ISSUE TITLE
numeric(10,0) datatype is translated as a :decimal type

### ISSUE THREAD

**Issue by rip747** [rails-sqlserver/activerecord-sqlserver-adapter#657]
Hi.

Trying to update to Rails v5.1.6 with the latest version of the adapter. It seems that in the previous version I used (v4.1.6) any numeric(10,0) datatype column was translated as an @type=:integer. Now in v5.1.6 of the adapter, they are translated to @type=:decimal.

**Comment by rip747** [comment]
So I managed to fix my issue by creating the following sqlserver_monkeypatch.rb in my config/initializers:

module ActiveRecord
  module ConnectionAdapters
    class SQLServerAdapter < AbstractAdapter
      def initialize_type_map(m)
        super(m)
        m.alias_type 'numeric(10,0)', 'init(4)'
      end
    end
  end
end

**Comment by wpolicarpo** [comment]
According to [SQL Server documentation](https://docs.microsoft.com/en-us/sql/t-sql/data-types/decimal-and-numeric-transact-sql?view=sql-server-2017), "_numeric is functionally equivalent to decimal_", so it does make sense to be declared as decimal in the adapter.

**Comment by owenwiddicombe** [comment]
I am moving a project from Oracle to SQL Server.

Most data types come through correctly however the numeric(10,0) types are coming through as BigDecimals.  So 12345678 in the SQL Server comes through as BigDecimal 0.12345678E8 in RoR.

If I go into SQL Server itself and run

select cast(12345678 as numeric(10,0));

It returns 12345678 without the trailing decimal place .0

12345678 in Oracle comes through as FixNum 12345678.

I have tried the patch provided by rip747 above but this then brings in the number 12345678 as Float 12345678.0 with the decimal place.

Is there anything I can do in the model, activerecord-sqlserver-adapter, tiny_tds or Freetds that will make the data come through into Rails in the correct format?  i.e. FixNum 12345678

Thanks.
Owen

**Comment by owenwiddicombe** [comment]
Thanks metaskills for the quick reply.

Just to add more confusion, Microsoft says this about  Numeric types:

'For the decimal and numeric data types, SQL Server considers each specific combination of precision and scale as a different data type. For example, decimal(5,5) and decimal(5,0) are considered different data types.' (https://docs.microsoft.com/en-us/sql/t-sql/data-types/decimal-and-numeric-transact-sql?view=sql-server-2017)

Regarding modifying the getters there are dozens of models and many Numeric fields to coerce.  I was hoping for a blanket patch that would apply to Numeric(10,0) values only for the selected database connection.  Obviously I would like to leave all Numeric values with decimal places unaffected. Additionally, the fix would have to also work for Oracle if the connection is reverted back to oracle_enhanced

**Comment by metaskills** [comment]
Ah yea, interesting. I do feel the hack would still be needed on your end tho. It could be elegant too and in one place. Like maybe in our Decimal type class?

**Comment by owenwiddicombe** [comment]
Perhaps the behaviour should be to treating Numeric(x,0) types as FixNum and Numeric(x,>0) types as a decimal type?

Or alternatively maybe there could be an official facility to change the mappings and override the default behaviour on a per connector, database, table, or field basis?  One that withstands future changes and development.

Just a layman's idea.  Thanks.

**Comment by rip747** [comment]
That's what my initial idea was. To me any number without precision should
be treated as a Integer.

**Comment by metaskills** [comment]
> Perhaps the behaviour should be to treating Numeric(x,0) types as FixNum and Numeric(x,>0) types as a decimal type?

I think I'm open to that idea but I am hesitant. I think it would be a problem for TinyTDS to do that... or require a lot of core changes which feel risky. So if not there, then in the adapter, that too feels like it has risks with the way ActiveRecord wants to type cast in an out and add un-needed complexity. I feel the logic in the request tho, but still feel it is not the right thing to do or worth the risk to change a nuanced behavior that has existed for so long ... if someone feels differently and can show both sets/gets and everything "just works" in working code?

**Comment by rip747** [comment]
The monkey patch I wrote in my begining comment worked perfect for me and
has been implemented for a bit now. I didnt have to do anything else to get
everything working. Besides, as stated before, this was the default
behavior in the previous versions of the gem and for some reason it was
changed.

**Comment by metaskills** [comment]
Cool, I think for now we can let that be used by others. I'm still learning to keeping it as is but it is up to others too.
