### ISSUE TITLE
Remove retired property: CursorCloseOnCommit

### ISSUE THREAD

**Issue by caseyprovost** [rails-sqlserver/activerecord-sqlserver-adapter#674]
`CURSOR_CLOSE_ON_COMMIT` has been retired from more recent versions of MSSQL. When using this library the resulting error is: `CursorCloseOnCommit is not a recognized option`.

Here is the offending code.

```
client.execute('SET CURSOR_CLOSE_ON_COMMIT OFF').do
```

I'd happily open a PR to remove that line but I am not sure that is the best approach. I don't know what kind of version compatibility this library desires.

**Comment by wpolicarpo** [comment]
Hi @caseyprovost, can you point out where in the documentation it says it will be or was removed and in which version? I could not find this information.

What's you MSSQL version?

**Comment by caseyprovost** [comment]
@wpolicarpo here are the docs I found on it from 2011:

https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms142580(v%3Dsql.105)

**Comment by caseyprovost** [comment]
@wpolicarpo  following up here, the problem as I discovered is actually because the database is the Azure Data Warehouse...which is NOT a vanilla MSSQL Database. Unfortunately, there is not as much parity as I expected.
