### ISSUE TITLE
Very slow performance on Linux

### ISSUE THREAD

**Issue by stibra** [rails-sqlserver/activerecord-sqlserver-adapter#677]
We have started to use activerecord-sqlserver-adapter gem and Rails 5.2.2 on Linux (inside Docker) to connect to Microsoft SQL server and is extremely slow comparing to Windows version. Any idea?
Using latest tiny_tds gem.

**Comment by wpolicarpo** [comment]
Could you send us the `Dockerfile` and a script reproducing the issue?

**Comment by stibra** [comment]
Here is the Docker file, I cannot send you the application, we will try to make some demo app:

FROM ruby:2.5.3-alpine
ADD . /app
RUN apk add --no-cache git nodejs yarn postgresql-client postgresql-dev tzdata curl

#FreeTDS
RUN apk add --no-cache freetds
# RUN apk add --no-cache freetds-common
RUN apk add --no-cache freetds-dev

RUN apk --update add --virtual build-dependencies ruby-dev build-base
RUN cd /app && bundle install
RUN apk del build-dependencies
RUN chmod 644 /usr/local/bundle/gems/nokogiri-plist-0.5.0/lib/core_ext/string.rb || true

ENV RACK_ENV=production RAILS_ENV=production APP_ENV=production DISABLE_SPRING=1
# use dummy SECRET_KEY_BASE for assets precompile
RUN cd /app && SECRET_KEY_BASE=does_not_exist bin/rails assets:precompile

# cleanup and settings
RUN find / -type f -iname \*.apk-new -delete && \
  rm -rf /var/cache/apk/* && \
  rm -rf /usr/lib/lib/ruby/gems/*/cache/* && \
  rm -rf ~/.gem && \
  rm -rf /var/lib/apt/lists/*

RUN chown -R nobody:nogroup /app
USER nobody
WORKDIR /app

ENV RAILS_SERVE_STATIC_FILES=false
ENV RAILS_LOG_TO_STDOUT=true
ENV PORT=3000
EXPOSE 3000

# double-­quotes and brackets are important
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]

**Comment by wpolicarpo** [comment]
@stibra is this still a problem?
