### ISSUE TITLE
Query Notification

### ISSUE THREAD

**Issue by sayuj** [rails-sqlserver/activerecord-sqlserver-adapter#678]
Is there a mechanism for query notification using service brokers? 

I am referring something similar to SqlDependency and SqlNotificationRequest options of .NET framework.

My requirement it to get mealtime notification from sql server database on any change in my database table.

**Comment by wpolicarpo** [comment]
There is no such thing implemented here. You can either use callbacks for doing so or implement a background service querying your database and detecting changes (needless to warn about the overhead this can cause in your database and the fact that it is not real realtime).

**Comment by metaskills** [comment]
Agreed. Even if this were a thing, I think it would really be at the FreeTDS/TinyTDS layer. But someone would have to do some investigation if that is correct and/or even possible. 

Alternatively, I think DB transaction logs might be helpful or if you want to do this in the application layer, maybe explore ActiveRecord's sql listener which can be subscribed to via ActiveSupport's notification system.
