### ISSUE TITLE
FTP server outage blocks the gem installation (1.3.0)

### ISSUE THREAD

**Issue by januszm** [rails-sqlserver/activerecord-sqlserver-adapter#679]
Currently the ftp://ftp.freetds.org/pub/freetds/ is down and it causes all `gem install tiny_tds -v "1.3.0"` commands to fail. Unfortunately in environments like AWS Elastic Beanstalk where servers can be recycled regularly it is causing major problems. In worst cases all servers go down.

Can we use alternative FTP servers? Currently the installation process, at least for 1.3.x version depends on an external server.

**Comment by wpolicarpo** [comment]
This repository is not about `tiny_tds`, but `activerecord-sqlserver-adapter`.

Answering your question, you can use their http mirror at http://www.freetds.org/files/stable.

**Comment by januszm** [comment]
Thank you @wpolicarpo I'm closing this issue. I'll write in tiny_tds repository. There should be a mechanism that switches the ftp automatically if one does not work.
