### ISSUE TITLE
find method tries to use 'LIMIT' clause in Rails >= 3.0.2

### ISSUE THREAD

**Issue by mathershifter** [rails-sqlserver/activerecord-sqlserver-adapter#69]
I get the following syntax error error when trying to do a "find".  This does not happen in Rails 3.0.1.  Does this have something to do with ARel?

[Rails 3.0.1]
$ rails console
Loading development environment (Rails 3.0.1)
ruby-1.9.2-p0 > PingSession.find(822)
 => #<PingSession tmo_ping_session_key: 822, source_probe_ip: "NA", source_probe_name: "AGOWSC01", source_interface: "NA", test_name: "AGOWSC01_to_AGOPHI01", group_name: "CoreNet Mesh", test_tag: "", external_ip: "10.161.255.19", packet_count: 15, packet_size: 512, active: "Y">

[Rails 3.0.3]
$ rails console 
Loading development environment (Rails 3.0.3)
ruby-1.9.2-p0 > PingSession.find(822)
ActiveRecord::StatementInvalid: ODBC::Error: 37000 (102) [unixODBC][FreeTDS][SQL Server]Incorrect syntax near 'LIMIT'.: SELECT [STG_ARGO_TMO_PING_SESSION].\* FROM [STG_ARGO_TMO_PING_SESSION] WHERE ([STG_ARGO_TMO_PING_SESSION].[tmo_ping_session_key] = 822) LIMIT 1
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract_adapter.rb:202:in `rescue in log'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract_adapter.rb:194:in`log'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-sqlserver-adapter-3.0.5/lib/active_record/connection_adapters/sqlserver/database_statements.rb:249:in `raw_select'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-sqlserver-adapter-3.0.5/lib/active_record/connection_adapters/sqlserver/database_statements.rb:193:in`select'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:7:in `select_all'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/query_cache.rb:56:in`select_all'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.3/lib/active_record/base.rb:467:in `find_by_sql'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.3/lib/active_record/relation.rb:64:in`to_a'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.3/lib/active_record/relation/finder_methods.rb:333:in `find_first'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.3/lib/active_record/relation/finder_methods.rb:122:in`first'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.3/lib/active_record/relation/finder_methods.rb:291:in `find_one'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.3/lib/active_record/relation/finder_methods.rb:281:in`find_with_ids'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.3/lib/active_record/relation/finder_methods.rb:107:in `find'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.3/lib/active_record/base.rb:439:in`find'
        from (irb):1
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.3/lib/rails/commands/console.rb:44:in `start'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.3/lib/rails/commands/console.rb:8:in`start'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.3/lib/rails/commands.rb:23:in `<top (required)>'
        from script/rails:6:in`require'
        from script/rails:6:in `<main>'

Gems:
activerecord (3.0.3, 3.0.1)
activerecord-sqlserver-adapter (3.0.5)
rails (3.0.3, 3.0.1)
ruby-odbc (0.99992)
dbd-odbc (0.2.5)
dbi (0.4.5)

The database connection:
development:
  adapter: sqlserver
  mode: odbc
  dsn: TPM
  username: xxxxxxxxx
  password: xxxxxxxx
  encoding: utf8

The model:
$ cat app/models/ping_session.rb 
class PingSession < ActiveRecord::Base
  set_table_name 'STG_ARGO_TMO_PING_SESSION'
  set_primary_key :tmo_ping_session_key
end

The table schema:
CREATE TABLE [dbo].[STG_ARGO_TMO_PING_SESSION]([tmo_ping_session_key]  smallint NOT NULL,
    [source_probe_ip]       varchar%2850%29 NOT NULL,
    [source_probe_name]     varchar%2850%29 NOT NULL,
    [source_interface]      varchar%2850%29 NOT NULL,
    [test_name]             varchar%2850%29 NOT NULL,
    [group_name]            varchar%2850%29 NOT NULL,
    [test_tag]              varchar%2850%29 NULL,
    [external_ip]           varchar%2850%29 NOT NULL,
    [packet_count]          smallint NULL,
    [packet_size]           smallint NULL,
    [active]                char%281%29 NOT NULL,
    CONSTRAINT [pk_stg_argo_tmo_ping_session] PRIMARY KEY%28[tmo_ping_session_key]%29)

**Comment by rmahnovetsky** [comment]
I know I'm 4 years too late :).. I have the exact same problem with rails 4.1.11 on windows(I'm not sure if it works from linux)... Has this issue been resolved?

I'm using the following GEMS for the db.

gem 'rails', '4.1.11'

gem 'activerecord-jdbc-adapter'
gem 'activerecord-jdbcmssql-adapter'
gem 'jdbc-jtds', '~> 1.3.1'
