### ISSUE TITLE
BigDecimal.new is deprecated; use BigDecimal() method instead.

### ISSUE THREAD

**Issue by fessio-software** [rails-sqlserver/activerecord-sqlserver-adapter#695]
Hi all, in ruby 2.6.1 I have this warning: 

> /usr/local/rvm/gems/ruby-2.6.1/bundler/gems/activerecord-sqlserver-adapter-b29603b62baf/lib/active_record/connection_adapters/sqlserver/database_statements.rb:405: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

**Comment by wpolicarpo** [comment]
What version of the adapter are you using?

**Comment by fessio-software** [comment]
5.2.0

**Comment by wpolicarpo** [comment]
Would you be able to create a reproducible script? I can't see what's going on here.

**Comment by emielvanlankveld** [comment]
It looks like the problem originates from using an older version of tiny_tds (TinyTds::Result), upgrading that to 2.1.2 caused the warning to go away for me.

**Comment by wpolicarpo** [comment]
@fessio-software did you try to update `tiny_tds`? Can we close this?

**Comment by fessio-software** [comment]
I confirm update `tiny_tds` has solved the problem.
