### ISSUE TITLE
Azure Data Warehouse Support

### ISSUE THREAD

**Issue by caseyprovost** [rails-sqlserver/activerecord-sqlserver-adapter#697]
Im curious if you guys looked at the amount of work it would take to make this library compatible with the Azure Data Warehouse as well. Behavior wise it appears pretty close. 

I would be interested in assisting with efforts there. If by chance you are not interested, would you be ok with a fork of this library that evolved/mutated into a project to support the Azure Data Warehouse (with original author credits of course)?

**Comment by wpolicarpo** [comment]
Hi,

I know nothing about Azure Data Warehouse, but I see no issues in supporting it here.

Would you be able to gather a list of differences between Azure and SQL Server that you think we might attack? 

Having the tests running against an Azure instance could be a starting point. Any ideas?

**Comment by caseyprovost** [comment]
I absolutely can gather that info. I’ll crack open a fork running against a live warehouse and see what happens.

**Comment by caseyprovost** [comment]
> I absolutely can gather that info. I’ll crack open a fork running against a live warehouse and see what happens.

I'm finally diving into this today.

**Comment by wpolicarpo** [comment]
Any news here @caseyprovost?

**Comment by caseyprovost** [comment]
@wpolicarpo sadly no. Ended up moving on from the project this was an issue for 😬
