### ISSUE TITLE
rails server

### ISSUE THREAD

**Issue by MrArsenic** [rails-sqlserver/activerecord-sqlserver-adapter#705]
Attempting to start up the localhost 3000 with rubyonrails its not working this is what im getting 

C:\Users\Du Le\Desktop\bullshit\webapplication>rails server
=> Booting Puma
=> Rails 6.0.0 application starting in development
=> Run `rails server --help` for more startup options
RAILS_ENV=development environment is not defined in config/webpacker.yml, falling back to production environment
Exiting
Traceback (most recent call last):
        51: from bin/rails:4:in `<main>'
        50: from bin/rails:4:in `require'
        49: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<top (required)>'
        48: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/command.rb:46:in `invoke'
        47: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/command/base.rb:65:in `perform'
        46: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        45: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        44: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        43: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:138:in `perform'
        42: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:138:in `tap'
        41: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        40: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:37:in `start'
        39: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
        38: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
        37: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
        36: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        35: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
        34: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
        33: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
        32: from config.ru:in `<main>'
        31: from config.ru:in `new'
        30: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
        29: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
        28: from config.ru:3:in `block in <main>'
        27: from config.ru:3:in `require_relative'
        26: from C:/Users/Du Le/Desktop/bullshit/webapplication/config/environment.rb:5:in `<top (required)>'
        25: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/application.rb:363:in `initialize!'
        24: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/initializable.rb:60:in `run_initializers'
        23: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        22: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        21: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        20: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:347:in `call'
        19: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:347:in `each'
        18: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        17: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        16: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        15: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        14: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
        13: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/initializable.rb:32:in `run'
        12: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/initializable.rb:32:in `instance_exec'
        11: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/webpacker-4.0.7/lib/webpacker/railtie.rb:84:in `block in <class:Engine>'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/webpacker-4.0.7/lib/webpacker.rb:27:in `bootstrap'
         9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/webpacker-4.0.7/lib/webpacker/commands.rb:14:in `bootstrap'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/webpacker-4.0.7/lib/webpacker/manifest.rb:18:in `refresh'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/webpacker-4.0.7/lib/webpacker/manifest.rb:83:in `load'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:47:in `public_manifest_path'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:43:in `public_output_path'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:39:in `public_path'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:80:in `fetch'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:84:in `data'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:87:in `load'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:91:in `rescue in load': Webpacker configuration file not found C:/Users/Du Le/Desktop/bullshit/webapplication/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - C:/Users/Du Le/Desktop/bullshit/webapplication/config/webpacker.yml (RuntimeError)

**Comment by wpolicarpo** [comment]
Hi,

The adapter is not ready for Rails 6 yet. Please follow #683 for more information on when it will become available.

**Comment by MrArsenic** [comment]
> Hi,
> 
> The adapter is not ready for Rails 6 yet. Please follow #683 for more information on when it will become available.

wait so what exactly do you mean by this sorry im new to coding so what exactly should i do in this scenario if the adapter is not ready for rails 6

**Comment by wpolicarpo** [comment]
From your logs I can see you created an application using latest version of Rails, which is 6.

This adapter does not support Rails 6 yet and you will need to install Rails 5.2 if you want to use SQL Server as your database.
