### ISSUE TITLE
Rake tasks not supported by 'sqlserver' adapter

### ISSUE THREAD

**Issue by batmanbury** [rails-sqlserver/activerecord-sqlserver-adapter#709]
I'm on a legacy rails project with this gem version 4.1.2

I can't get around this `Rake tasks not supported by 'sqlserver' adapter`

Are there some custom tasks I'm supposed to put in /lib/tasks? That page is gone in the wiki, since anyone can edit.

**Comment by edward-ellis** [comment]
I have this problem as well.  I have looked into the active record code and see that the adapter has db:create and db:drop rake tasks and that it is supposed to call register_task.  I also see that the adapter calls register_task in sqlserver_database_tasks.rb.  But for some reason that isn't happening in my Rails application and active record complains whenever I try to create or drop a database.
Can you offer any suggestions on how to troubleshoot this issue?

**Comment by wpolicarpo** [comment]
I restored some of those wiki pages. You can see them on the [`4-1-stable` branch](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/tree/4-1-stable). Hope that helps.
