### ISSUE TITLE
ActiveRecord Sqlserver Adapter Support for SQL Server 2019

### ISSUE THREAD

**Issue by sithara** [rails-sqlserver/activerecord-sqlserver-adapter#715]
Does tinytds -v 0.7.0 running on ruby 1.9.3,rails 3.x support sql server -v 2019 ? It worked for me till sql server -v2017 but not beyond that. 
 My activerecord-sqlserver-adapter version is 3.2.18

**Comment by wpolicarpo** [comment]
This is a really old version of the adapter. I suggest you upgrade your Rails version if possible or stick with an older version of SQL Server.
