### ISSUE TITLE
Tests from Rails fail with `TinyTds::Error: Ambiguous column name 'id'`

### ISSUE THREAD

**Issue by lcreid** [rails-sqlserver/activerecord-sqlserver-adapter#722]
A number of the Rails tests fail with `TinyTds::Error: Ambiguous column name 'id'` (or something similar). It appears that the tests were added to Rails 5.2 by: https://github.com/rails/rails/pull/35360, and https://github.com/rails/rails/pull/35441 to test a fix to an issue in the Rails code (https://github.com/rails/rails/issues/35359).

I believe this issue is related to #713. 

I'm happy to take a stab at a PR. I will report back if I get blocked on the PR.

**Comment by lcreid** [comment]
I've opened https://github.com/rails/rails/pull/38337, and submitted https://github.com/rails/rails/pull/38338 to Rails as a proposed fix for this issue.

**Comment by lcreid** [comment]
The PR to Rails was merged to master and backported. I haven't had a chance to test the MS SQL Server adapter against Rails since the merge. If anyone gets a chance, please post here if it worked or if there were problems. 

The Rails PR doesn't fix *all* the test failures, but it fixes the ambiguous column name errors.

**Comment by wpolicarpo** [comment]
Closing this as per #745. Thanks @lcreid and @aidanharan.
