### ISSUE TITLE
Lateral support using CROSS/OUTER APPLY?

### ISSUE THREAD

**Issue by sdahlbac** [rails-sqlserver/activerecord-sqlserver-adapter#738]
I've been trying to implement support for Arel::Nodes::Lateral by doing a CROSS/OUTER APPLY

This is nowhere near ready to be merged upstream, (it now always does an outer apply, no tests). For my usecase it seems to work with no ill effects, but before I put in the effort to make a proper PR, I want to gauge interest, does this make sense, is it a good idea etc...?

The comment in the PR lacks quite a bit of context.

https://github.com/jensnockert/activerecord-sqlserver-adapter/pull/1

**Comment by wpolicarpo** [comment]
Hi @sdahlbac. I would be happy to review a PR.

**Comment by sdahlbac** [comment]
Alright, I'll try to create a real PR.

Btw, the https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/RUNNING_UNIT_TESTS.md points to 

Here's how (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/https:/github.com/rails-sqlserver/activerecord-sqlserver-adapter-dev-box) that is a 404. Are the instructions available somewhere?

**Comment by sdahlbac** [comment]
@wpolicarpo I finally got around to creating the PR now: #845
