### ISSUE TITLE
update test suites

### ISSUE THREAD

**Issue by PaulCharlton** [rails-sqlserver/activerecord-sqlserver-adapter#742]
Test suites have not passed on Travis in about a year [since build # 278]

see: https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/builds
see also: https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/builds/508636840

**Comment by PaulCharlton** [comment]
@wpolicarpo seems like the last passing travis run was for 5.2.0-stable ...  I would love to get a download on context before I dive in and start clearing issues.

**Comment by PaulCharlton** [comment]
note: even pulling 5.2.0-stable tag and running the tests is not passing -- the dependencies are not sufficiently pinned to prevent feature creep.

**Comment by wpolicarpo** [comment]
SQL Server adapter test suite also runs the whole ActiveRecord test suite along with its own tests. When 5.2.0 adapter was released, the stable Rails version was 5.2.2.1 ans tests were passing at that time.

Rails was updated in the next months and I didn't have time to look into the failing tests here. Master is passing again and I will release a new version targeting 5.2 soon.
