### ISSUE TITLE
Insert failing on table with trigger adapter version 5.1.7

### ISSUE THREAD

**Issue by bwbasheer** [rails-sqlserver/activerecord-sqlserver-adapter#760]
We are migrating a SQL Server application from Rails 4.2 to 5.1.7.  We are now seeing this failure that we did not see before the migration.

ActiveRecord::StatementInvalid (TinyTds::Error: The target table 'assistive_features_ve' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.: EXEC sp_executesql N'INSERT INTO  . . .

Why is this happening now, given that it did not occur in earlier versions?  The SQL Server version information is as follows:
Microsoft SQL Server 2017 (RTM-GDR) (KB4505224) - 14.0.2027.2 (X64)   Jun 15 2019 00:26:19   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 17763: )

**Comment by wpolicarpo** [comment]
Please see the documentation [here](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter#identity-inserts-with-triggers) on how to fix that.

**Comment by bwbasheer** [comment]
Apologies for not checking on the doc first.  On reading the doc, I recall having seen it a month ago.
