### ISSUE TITLE
undefined method `prepare'

### ISSUE THREAD

**Issue by reyza-ps** [rails-sqlserver/activerecord-sqlserver-adapter#770]
when I run
st = ActiveRecord::Base.connection.raw_connection.prepare("update table set f1=? where f2=? and f3=?")
for execute
st.execute(f1, f2, f3)

but appeared error
**NoMethodError (undefined method `prepare' for #<ActiveRecord::ConnectionAdapters::SQLServerAdapter:0x00000000074bb110>)**

i am using sqlserver database, any solution ?

**Comment by wpolicarpo** [comment]
Hi, can you give us more information? What version of Rails are you using?

**Comment by wpolicarpo** [comment]
`ActiveRecord::Base.connection.raw_connection` retuns the underlying connection handler for the database, which for the SQL Server adapter is `TinyTDS`.

`TinyTDS` client does not implement `prepare`.

If you want to run parameterized queries using TinyTDS, you can do something like this:

```ruby
statement = "UPDATE table SET f1 = @0 WHERE f2 = @1 AND f3 = @2"
definitions = "@0 nvarchar(4000), @1 int, @2 tinyint"
values = ["Foo", 42, 1]

ActiveRecord::Base.connection.execute_procedure(:sp_executesql, statement, definitions, *values)
```
