### ISSUE TITLE
Binary column type is being treated as a String type

### ISSUE THREAD

**Issue by jeremysenn** [rails-sqlserver/activerecord-sqlserver-adapter#842]
## Issue
A table's image/binary type column is being treated as a string type column, which results in the following error when saving blob image data to that column:

ActiveRecord::StatementInvalid: ArgumentError: string contains null byte

The same exact image/binary column is correctly shown as a binary column in earlier versions (SQL Server adapter version 4.1.4 and TinyTDS version 1.0.5), allowing for successful saving of blob image data to the column.

## Expected behavior
The column should correctly be viewed as a binary type, allowing for blob image data to successfully be saved, even if it contains a null byte.

## Actual behavior
Blob image data, which contains null bytes, cannot be saved to the column because the column is being treated as a string type, and results in an error:

ActiveRecord::StatementInvalid: ArgumentError: string contains null byte

## How to reproduce
Connect to an MS SQL database table that has an "image" column type, and attempt to save blob image data containing a null byte.

## Details

- **Rails version**: `6.0.3`
- **SQL Server adapter version**: `6.0.0`
- **TinyTDS version**: `2.1.2`
- **FreeTDS details**:
- **SQL Server**: 2012

  ```
Version: freetds v1.00.21
freetds.conf directory: /usr/local/Cellar/freetds/1.00.21/etc
MS db-lib source compatibility: no
Sybase binary compatibility: no
Thread safety: yes
iconv library: yes
TDS version: 7.3
iODBC: no
unixodbc: no
SSPI "trusted" logins: no
Kerberos: no
OpenSSL: yes
GnuTLS: no
MARS: no
  ```

**Comment by jeremysenn** [comment]
Turns out this issue was similar to this one:

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/643

I created a custom attribute in an initializer (rails_sqlserver_types.rb):

ActiveRecord::Type.register(:var_binary_max, ActiveRecord::Type::SQLServer::VarbinaryMax)

And then applied the custom attribute in the model:

attribute :jpeg_image, :var_binary_max

**Comment by PadawanBreslau** [comment]
@jeremysenn Thank you very much, sir, worked as charm for my problem too! :)
