### ISSUE TITLE
use_output_inserted = false fails to return new guid id on inserts

### ISSUE THREAD

**Issue by gisborne** [rails-sqlserver/activerecord-sqlserver-adapter#926]
## Issue
Rails does not get back the id of a new row in a table with a guid primary key with use_output_inserted set to false.

## Expected behavior
The id should be returned

## Actual behavior
The id comes back null

## How to reproduce
Working on a test. This should work:

schema.rb:

  create_table "test" do |t|
    t.uuid     "id", null: false
    t.string  "x"
  end

test.rb
  class Test < ActiveRecord::Base
  end

t = Test.create x: 'foo'

t.id # nill; should be guid

The problem is in sql_for_insert:

```
        def sql_for_insert(sql, pk, id_value, sequence_name, binds)
…
          sql = if pk && use_output_inserted? && !database_prefix_remote_server?
…                
                else
                  "#{sql}; SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident"
                end
          super
        end
```

This works if the last inserted id is an integer, but fails for a guid — in two ways: scope_identity() can only return an integer, and we're casting it to an integer anyway.

I understand that `OUTPUT INSERTED` fails in the presence of triggers, which is our situation. So I'm not sure what the fix is.

## Details

- **Rails version**: `6.0`
- **SQL Server adapter version**: `6.0`

  ```
  run `tsql -C` and paste here the output.
  ```

```                            Version: freetds v1.2.20
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: yes
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: yes
```

**Comment by gisborne** [comment]
This in uuid_test_sqlserver.rb replicates the problem:
```  
it "can create with a new pk with use_output_inserted = false" do
    with_use_output_inserted_disabled do
      obj = SSTestUuid.create!
      _(obj.id).must_be :present?
      _(obj.id).must_match acceptable_uuid
    end
  end
```

**Comment by mgrunberg** [comment]
If you forbid the usage of `output inserted` I don't think there is a good way to return the guid value. Maybe that's why the adapter [has a test](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/main/test/cases/uuid_test_sqlserver.rb#L44) showing that id should be nil in that case.

If you are setting `use_output_inserted = false` because your table has triggers then you should follow the [README intructions](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/tree/v6.0.2#identity-inserts-with-triggers) instead.

So, I don't know how to solve this issue but maybe the readme suggestion solves your problem

**Comment by gisborne** [comment]
D'Oh! I hadn't seen that.

Could we not automatically detect the condition where the table has a trigger and a GUID id and do the right thing, without needing all these settings?

**Comment by wpolicarpo** [comment]
@gisborne the configuration is done that way to avoid penalising inserts ran against tables that don't have that limitation.

It would be expensive to check for when we should use the temporary table and that's why we let devs configure when to use that.

**Comment by gisborne** [comment]
Why would it be expensive? We could use cached information about the table, just as we do in plenty of other places.
