### ISSUE TITLE
Do the monkey patches in this gem interfere with the Rails built-in PostgreSQL adapter?

### ISSUE THREAD

**Issue by mattbrictson** [rails-sqlserver/activerecord-sqlserver-adapter#929]
## Issue

This is more of a question than a reproducible issue.

My team is considering using the [multiple database support](https://guides.rubyonrails.org/active_record_multiple_databases.html) built into Rails to connect our Rails app to two databases simultaneously: a PostreSQL database and a SQL Server database. Does this gem supports such a scenario?

For example, Rails 6.1 supports a `database.yml` like this:

```yaml
production:
  primary:
    adapter: postgresql;
    # postgres config goes here
  secondary:
    adapter: sqlserver
    # sql server config goes here
```

Then one can use [establish_connection](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionHandling.html#method-i-establish_connection) to connect to one or the other database on demand. Alternatively, one can declare models using [connects_to](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionHandling.html#method-i-connects_to) to "bind" models to a certain database.

However, **I see that this gem applies monkey patches to several ActiveRecord internal classes.** Which has me worried. See here:

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/tree/v6.1.0.0/lib/active_record/connection_adapters/sqlserver/core_ext

Some of these patches seem to imply that compatibility with other databases is being removed (notably PostgreSQL in [this example](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/v6.1.0.0/lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb#L11)) in favor of supporting SQL Server. This is not explicitly stated in the code or documentation, so I can't be sure of that.

**Is it problematic to use the SQL Server adapter and the PostgreSQL adapter in the same Rails application?** It seems like conflicts are a real possibility, because the monkey patches are scoped to affect ActiveRecord as a whole.

## Expected behavior

I'd like like to be able to use the SQL Server adapter and PostgreSQL adapter in the same Rails app without them conflicting with each other. Is it possible that the monkey patches in this gem could somehow be scoped so they only apply based on the database connection?

In other words, in pseudo code:

> if connection.adapter is sqlserver then patched_version else original_version

## Details

- **Rails version**: `6.1.4`
- **SQL Server adapter version**: `6.1.0.0`
- **TinyTDS version**: `2.1.5`
- **FreeTDS details**:

 ```
 $ tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.2.21
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: yes
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: yes
  ```

**Comment by aidanharan** [comment]
Yes, I think it would be problematic using the SQL Server adapter with other adapters in the same Rails application for the reasons you say. 

Your `if connection.adapter is sqlserver then patched_version else original_version` solution would probably work although I'm not sure how we can test the code to confirm it. Running the SQL Server adapter tests will confirm that we don't break the SQL Server adapter but that wouldn't prove that we haven't introduced bugs into the PostgreSQL/MySQL/SQLite adapter if used together in the same application.

Multiple database support was added in Rails 6.0 and the SQL Server adapter hasn't yet been updated to accommodate it.

**Comment by wpolicarpo** [comment]
I think we can change the SQL Server adapter to make it compatible with multiple database connections using multiple adapters. This adapter is partially compatible as it does support multiple databases, but like you observed, using multiple adapters may cause issues.

I will gladly review PRs fixing that behaviour if you want to help.
