### ISSUE TITLE
gem activerecord-sqlserver-adapter latest plugin not working to log message in database

### ISSUE THREAD

**Issue by vishwasFullStack** [rails-sqlserver/activerecord-sqlserver-adapter#942]
## Issue
To store log in the database we are using td-aget 4.1.1 with the gem **activerecord-sqlserver-adapter**  with version '6.1.0.0'  but yesterday when we reinstall gem **activerecord-sqlserver-adapter**  installed with the latest version 6.1.2.0.

This version is throwing "Uninitialized Constant Rails"  Error .

![image](https://user-images.githubusercontent.com/90322669/132504720-43693fb7-8b42-4380-b9af-9c48f521e1bd.png)

We are trying to install the previous version, but it was also not available.

**Comment by harsh288** [comment]
I'm getting the same error with fluentd configuration, it was working with the package "fluent-plugin-sql" but not getting error.

**Comment by wpolicarpo** [comment]
This was a regression coming from #941.

Sorry about that. I'll fix it and release a new version soon.

**Comment by harsh288** [comment]
Sure @wpolicarpo, I'm waiting for the new version, just curious how can this be avoided in future since the previous version is gone, this will surely impact the production if the latest version is taken.

**Comment by wpolicarpo** [comment]
@harsh288 not sure what you mean with previous version is gone. I'm not yanking 6.1.2.0 for now (but maybe I should).

**Comment by harsh288** [comment]
@wpolicarpo I mean the version 6.1.1.0 & 6.1.0.0 ([https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/commit/6276e1b0f72561d1bec385d7aa712ffac5128458#diff-7b60b8e351cbb80c47459ffe2c79f1a26404871f49294780fe47ad0e58c09350](url)

I believe the previous version is overridden, but if there is a way where I can still download the old version of the package like "gem install activerecord-sqlserver-adapter 6.1.0" then it would be safe since this has been tested.

**Comment by wpolicarpo** [comment]
@harsh288 No, previous versions are not removed, they are available in [RubyGems](https://rubygems.org/gems/activerecord-sqlserver-adapter/versions) unless they are yanked.

You can either pin it down to `6.1.1.0` for now or wait a few minutes until I release a new version.

**Comment by wpolicarpo** [comment]
Version [6.1.2.1](https://rubygems.org/gems/activerecord-sqlserver-adapter/versions/6.1.2.1) was released and contains a fix for that.

Can you please update your deps and let me know if you find any issues?

**Comment by harsh288** [comment]
@wpolicarpo Thanks a lot for fixing this on priority.

And regarding installing the specific version, I tried but at the end it installs the latest one, you can see the snapshot below.

![image](https://user-images.githubusercontent.com/19948144/132558390-de90b48b-d438-42d4-995c-84cc0fda8997.png)
