### ISSUE TITLE
Connection option "trustServerCertificate" seems broken/not supported

### ISSUE THREAD

**Issue by brantz** [rails-sqlserver/activerecord-sqlserver-adapter#946]
activerecord-sqlserver-adapter (6.1.0.0)
tiny_tds (2.1.5)

I am trying to set the connection option `trustServerCertificate` but it seems i can't get it to work.

I have tried adding the option as a query parameter to `DATABASE_URL`, like so:

`sqlserver://<user>:<pwd>@<host>:<port>/<db_name>?trust_server_certificate=true`

That didn't work so i tried various spellings of `trustServerCertificate` like `trust_server_certificate` or `trustservercertificate`.

Neither had done the trick, they simply seem to be ignored.

Then i found https://github.com/rails-sqlserver/activerecord-sqlserver-adapter#configure-connection and tried setting it via an rails initializer like so:

```
module ActiveRecord
  module ConnectionAdapters
    class SQLServerAdapter < AbstractAdapter
      def configure_connection
        raw_connection_do "SET TRUST_SERVER_CERTIFICATE ON"
      end
    end
  end
end
```

This resulted in `TinyTds::Error: 'TRUST_SERVER_CERTIFICATE' is not a recognized SET option`.

Well, it was worth a shot ;)

Documentations for both TinyTds & AR sqlserver adatper do not mention mention anything about that connection option.

Any help on this would be greatly appreciated :)

**Comment by wpolicarpo** [comment]
Sorry, I haven't heard about that config before. Isn't that option only for the [jdbc driver](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder.trustservercertificate?view=dotnet-plat-ext-5.0)?

I didn't find any mentions in freetds for that option so I don't think you will be able to use here.

**Comment by gucki** [comment]
There's an option for it in the config file of freetds: https://www.freetds.org/userguide/freetdsconf.html. But it doesn't seem like https://github.com/rails-sqlserver/tiny_tds supports setting the options on the fly. So I just created https://github.com/rails-sqlserver/tiny_tds/issues/504.

**Comment by brantz** [comment]
Thanks, @wpolicarpo for your input, it pointed me to the right direction. Some digging into the FreeTds config options showed that, as @gucki pointed out, the default behavior is to accept any server certificate.  Indeed our issues turned out to be related to our firewall and not to the handling of the certificate.
