### ISSUE TITLE
Oracle CLOB and BLOB datatype are not supported

### ISSUE THREAD

**Issue by harsh288** [rails-sqlserver/activerecord-sqlserver-adapter#949]
Hello Everyone,

I'm using fluentd and using fluent SQL plugin along with oracle_enhanced adapter, but the datatype clob and blob are not working, please help.

```
<match MIOLogMessage>
	@type sql
    flush_interval 10
	host localhost
	database GOAORA
	port 1521
	adapter oracle_enhanced
	username admin
	password admin
	<table>
		table logmessage
		column_mapping 'miologid:miologid,timestamputc:timestamputc,messageid:messageid'
	</table>
	flush_interval 1s
</match>
```

**Comment by harsh288** [comment]
@wpolicarpo Do you have an idea about this ??

**Comment by wpolicarpo** [comment]
@harsh288 you might want to ask for help on the fluentd plugin repo or Oracle adapter repo. I don't think we will be able to help you here, sorry.
