### ISSUE TITLE
Rails 7.0 support

### ISSUE THREAD

**Issue by aidanharan** [rails-sqlserver/activerecord-sqlserver-adapter#962]
The SQL Server Adapter needs to be updated to support Rails 7.0. 

The steps will be to:

1. Cut `6-1-stable` branch from `main` and make `main` the development branch for Rails 7.
2. Get the test suite running, which @mgrunberg is working on in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/961
3. Update the adapter so that the tests all pass
4. Fix any outstanding bugs that the tests didn't cover

**Comment by mgrunberg** [comment]
@aidanharan I made a series of PR that should make all tests pass. I need help reviewing and merging them.

**Comment by aidanharan** [comment]
Many thanks to @mgrunberg for all his work upgrading the adapter to work with Rails 7.0 and making all the tests pass! 

@wpolicarpo Would you be able to push a beta release of the adapter to RubyGems? Also, do you know how to install new Ruby versions onto the Appveyor CI image? Rails 7 requires Ruby >= 2.7.0 and the CI image does not appear to have any version greater than 2.6.

**Comment by wpolicarpo** [comment]
I'll cut a release this weekend and update the Docker images to their latest versions. On the Appveyor, we need to check if they support the versions we need. I can look into that too.

And thanks @mgrunberg for all the hard work.

**Comment by wpolicarpo** [comment]
I released [7.0.0.0.rc1](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/compare/6-1-stable...v7.0.0.0.rc1) now.

If nothing big arises in the upcoming days, I will release a final version. Please report any bugs/issues.

**Comment by mgrunberg** [comment]
@wpolicarpo is it safe to release a final version now? Sorry if this is not the proper place to ask

**Comment by wpolicarpo** [comment]
> @wpolicarpo is it safe to release a final version now? Sorry if this is not the proper place to ask

Yes. I'll release a final version later today.

**Comment by wpolicarpo** [comment]
@mgrunberg v7.0.0.0 was released.

**Comment by mgrunberg** [comment]
@wpolicarpo thanks!
